Bss 209 add tron to blockchain sdk
tangem/blockchain-sdk-swift pull request #113
Opened 2022-04-27 05:47 UTC by megakoko

2022-04-28 14:59 UTC, tureck1y requested changes

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk.xcodeproj/xcshareddata/xcschemes/BlockchainSdkExample (start & scan).xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
Имхо это лишнее. Блокчейн сдк в общем-то мало что о карте знает и пусть так остается, а example должен быть максимально простой и чистый.

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/Common/BaseManager.swift
>          return amount.value > 0
видимо позавчерашний фикс не подлит

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +            return "Tron" + testnetSuffix
Дефолтный кейс подойдет тут

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .ethereum,
мне больше нравилось как было, компактнее :)

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Tron/TronAddressService.swift
> +    }
```suggestion
    init() {}
```

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Tron/TronAddressService.swift
> +        try walletPublicKey.validateAsSecp256k1Key()
валидация произойдет при расжатии, эту можно удалить

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Tron/TronAddressService.swift
> +        let decompressedPublicKey = try Secp256k1Key(with: walletPublicKey).decompress()
Трон не умеет работать со сжатыми ключами?

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Tron/TronWalletManager.swift
> +    var txBuilder: TronTransactionBuilder!
```suggestion
    var networkService: TronNetworkService!
    var txBuilder: TronTransactionBuilder!
    
    var currentHost: String {
        networkService.rpcProvider.host
    }
    
    var allowsFeeSelection: Bool {
        false
    }
```

2022-04-28 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Tron/TronWalletManager.swift
> +}
```suggestion
extension TronWalletManager: ThenProcessable {}
```

2022-04-29 06:26 UTC, megakoko commented on BlockchainSdk/Common/BaseManager.swift
>          return amount.value > 0
Подлил, удалил добавленный метод

2022-04-29 06:27 UTC, megakoko commented on BlockchainSdk.xcodeproj/xcshareddata/xcschemes/BlockchainSdkExample (start & scan).xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
Это я для своего удобства делал. Удалил из списка расшаренных схем

2022-04-29 06:30 UTC, megakoko commented on BlockchainSdk/WalletManagers/Tron/TronAddressService.swift
> +        try walletPublicKey.validateAsSecp256k1Key()
Удалил

2022-04-29 06:33 UTC, megakoko commented on BlockchainSdk/WalletManagers/Tron/TronAddressService.swift
> +        let decompressedPublicKey = try Secp256k1Key(with: walletPublicKey).decompress()
Если на основе сжатого ключа создавать адрес то начинает ругаться на подпись.

Ошибка типа "Аккаунт TLH7rGxfpQUd2eCTVJC12EqG4nsTwS5DHp не подписал транзакцию", где TLH7rGxfpQUd2eCTVJC12EqG4nsTwS5DHp — это адрес, который генерировался с несжатым ключем.

2022-04-29 07:08 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .ethereum,
какие конфликты? XCode же подсветит если что будет не так

2022-04-29 07:08 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case .ethereum,
При мердже. Если писать в столбик то вероятность конфликтов уменьшается.

2022-04-29 07:14 UTC, tureck1y approved these changes

2022-05-04 08:50 UTC, gre4ixin approved these changes

2022-05-05 07:49 UTC, lazutkin-andrey approved these changes

2022-05-05 08:48 UTC, merged