IOS-1738 Add dash testnet
tangem/blockchain-sdk-swift pull request #135
Opened 2022-06-14 09:22 UTC by Balashov152

Добавлен Dash в Blockchain с логикой получения баланса и зачисления тестнет койнов.
Создание и отправка транзакций буду делать в другой задаче, что бы реквест не был огромным

2022-06-14 09:38 UTC, Balashov152 commented on BlockchainSdkTests/DashTests.swift
> +    }
Могу удалить, использовал для тестов и дебага)

2022-06-14 09:43 UTC, megakoko commented on BlockchainSdkTests/DashTests.swift
> +    }
А `apiKey` — это секрет?

2022-06-14 09:44 UTC, Balashov152 commented on BlockchainSdkTests/DashTests.swift
> +    }
ну это apiKey на моем аккаунте, который для приложения, он в `config`

Не знаю, может лучше удалить, тут и тестовый кошелек тоже

2022-06-14 09:57 UTC, gre4ixin requested changes

2022-06-14 10:16 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/CryptoAPIs/CryptoAPIsMoyaProvider.swift
> +class CryptoAPIsMoyaProvider: MoyaProvider<CryptoAPIsMoyaProvider.Target> {
у CryptoAPI тоже свой получается, просто что бы постоянно не передавать apiKey в Moya.TargetType я расширил сам провайдер

2022-06-14 10:19 UTC, megakoko commented on BlockchainSdk/BlockchainService/CryptoAPIs/ResponseModels/CryptoAPIsTransaction.swift
> +struct CryptoAPIsTransaction : Codable, TransactionParams {
У других посмотри тоже, пожалуйста

2022-06-14 10:19 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +
Пустая строка

2022-06-14 10:19 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +            var providers: [AnyBitcoinNetworkProvider] = []
Можно сделать константой и инициализировать внутри каждой ветки. Будет говорить нам, что массив задается один раз и не меняется.

2022-06-14 10:20 UTC, Balashov152 commented on Podfile.lock
> +PODFILE CHECKSUM: 484bf2c3b53dd035c5a71bf6e29b871999ffae13
вообще нет, не знаю откуда это изменение взялось, проверю

2022-06-14 10:21 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/CryptoAPIs/CryptoAPIsMoyaProvider.swift
> +                "X-API-Key": apiKey
а так разве компилятор не ругается?

2022-06-14 10:23 UTC, megakoko commented on BlockchainSdk/BlockchainService/CryptoAPIs/CryptoAPIsMoyaProvider.swift
> +                "X-API-Key": apiKey
Неа, это вообще чуть ли не главная причина почему я с плюсов на свифт перешел.

2022-06-14 10:34 UTC, Balashov152 commented on Podfile.lock
> +PODFILE CHECKSUM: 484bf2c3b53dd035c5a71bf6e29b871999ffae13
Согласен, в приницпе .lock файл можно вообще в .gitignore добавить, он же генерится сам

2022-06-14 10:49 UTC, gre4ixin submitted a review, later dismissed

2022-06-14 10:50 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Blockchair/BlockchairTarget.swift
> +            return .dash(testnet: false)
Так а это же из 

 ```
enum BlockchairEndpoint {
    case bitcoin(testnet: Bool),
         bitcoinCash,
         litecoin,
         dogecoin,
         ethereum(testnet: Bool),
         dash
 }
 ```
 
 тут нет переменной, так как Blockchair не поддерживает testnet

2022-06-14 10:50 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Blockcypher/BlockcypherTarget.swift
> +        case .dash: return .dash(testnet: false)
и тут так же, только 


```
enum BlockcypherEndpoint {
    case bitcoin(testnet: Bool)
    case ethereum, litecoin, dogecoin, dash
    }
    ```

2022-06-14 10:51 UTC, megakoko commented on BlockchainSdk/BlockchainService/Blockchair/BlockchairTarget.swift
> +            return .dash(testnet: false)
Окей

2022-06-14 11:33 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/CryptoAPIs/ResponseModels/CryptoAPIsBase.swift
> +    let data: Data
Сделал `T`

2022-06-14 11:33 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/CryptoAPIs/ResponseModels/CryptoAPIsTransaction.swift
> +struct CryptoAPIsTransaction : Codable, TransactionParams {
вроде все глянул, убрал

2022-06-14 11:33 UTC, Balashov152 commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +
✅

2022-06-14 11:33 UTC, Balashov152 commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +            var providers: [AnyBitcoinNetworkProvider] = []
✅

2022-06-14 11:34 UTC, Balashov152 commented on Podfile.lock
> +PODFILE CHECKSUM: 484bf2c3b53dd035c5a71bf6e29b871999ffae13
✅

2022-06-27 12:23 UTC, merged

2022-06-27 16:02 UTC, Balashov152 commented
Произошло что то странно не ожиданое для меня

Я закрыл MR #137 с `Dash Mainnet` в который была ранее влита ветка с testnet, и все что было связанно с testnet было удаленно. Далее после мерджа #137 MR, этот MR был автоматически закрыт GitHub'ом по логике того, что эта ветка была слита в mainnet ветку. 
Всех изменений что есть в этой ветке, по добавлению CryptoAPIs нет в `develop`.