Create optimism wallet manager
tangem/blockchain-sdk-swift pull request #169
Opened 2022-10-04 13:49 UTC by gre4ixin

2022-10-04 13:54 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +            }
Без копипасты не получится сделать?

2022-10-04 15:11 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +
Очень много копипасты получилось. Нужно переопределять методы точечно, наследуюясь от EthreumWalletManager.

Портянку l1FeeABI лучше  как-то отдельно положить, чтобы в глаза не бросалась.

2022-10-05 04:32 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +
копипасты и правда много, но она может быть оправдана, если нужно изменять этот код независимо в будущем)

2022-10-05 06:10 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +
Для примера можно посмотреть на "DucatusWalletManager". Тут на выходе должно получиться что-то подобное.

2022-10-05 07:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        return wallet.blockchain.getJsonRpcURLs(infuraProjectId: "613a0b14833145968b1f656240c7d245")![0]
хардкод ключа?!

2022-10-05 07:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        let destinationInfo = formatDestinationInfo(for: destination, amount: amount)
можно же у базового класса дернуть фи, а тут просто прибавить l1

2022-10-05 09:27 UTC, megakoko commented on BlockchainSdk/WalletManagers/Ethereum/EthereumWalletManager.swift
> +
Что тут поменялось?

2022-10-05 09:27 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    private let l1FeeContractMethodName: String = "getL1Fee"
Может везде сделать "level1" вместо "l1"? Последнее тяжело читается.

2022-10-05 09:27 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                return [minAmount, normalAmount, maxAmount, l2FeeResponse]
`l2FeeResponse` здесь тоже надо отдавать? У нас интерфейс не сойдет с ума из-за четырех возможных комиссий?

2022-10-05 09:27 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                contractInteractor.read(method: self.l1FeeContractMethodName, parameters: params) { result in
Может сразу сделать комбайновскую обертку над `read`?

2022-10-05 09:33 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                return [minAmount, normalAmount, maxAmount, l2FeeResponse]
Кстати, приложению совсем необязательно знать о всяких там l1 l2.

2022-10-05 13:02 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        return wallet.blockchain.getJsonRpcURLs(infuraProjectId: "613a0b14833145968b1f656240c7d245")![0]
поправил

2022-10-05 13:03 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Ethereum/EthereumWalletManager.swift
> +
Ничего, просто нельзя переопределять методы в extension

2022-10-05 13:05 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    private let l1FeeContractMethodName: String = "getL1Fee"
переименовал на layer1 и layer2

2022-10-05 13:06 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                return [minAmount, normalAmount, maxAmount, l2FeeResponse]
поправил

2022-10-05 13:11 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                contractInteractor.read(method: self.l1FeeContractMethodName, parameters: params) { result in
я не против, если Саша одобрит, можно в этой задаче сделать

2022-10-05 13:12 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        let destinationInfo = formatDestinationInfo(for: destination, amount: amount)
поправил

2022-10-05 13:16 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                contractInteractor.read(method: self.l1FeeContractMethodName, parameters: params) { result in
Там немного работы, один Promise и все. Зато код наряднее.

2022-10-05 13:55 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                contractInteractor.read(method: self.l1FeeContractMethodName, parameters: params) { result in
сделал

2022-10-06 07:21 UTC, tureck1y requested changes

2022-10-06 07:21 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismLayer1GasFeeABI.swift
> +let OptimismLayer1GasFeeABI: String =
Давай в какую-нибудь утилиту завернем, только не static, чтобы в памяти все время не висело. И с неймингом надо повнимательнее. Тут переменная с большой буквы

2022-10-06 07:21 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    private func formatDestinationInfo(for destination: String, amount: Amount) -> (to: String, value: String?, data: String?) {
эта штука не используется

2022-10-06 07:21 UTC, tureck1y commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +                $0.rpcURL = blockchain.getJsonRpcURLs(infuraProjectId: config.infuraProjectId)![0]
blockchain.getJsonRpcURLs(infuraProjectId: config.infuraProjectId)! уже вызывается двумя строчками выше

2022-10-06 09:12 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Ethereum/ContractInteractor.swift
> +                    let contract = try self.makeContract()
✅

2022-10-06 09:12 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    private func formatDestinationInfo(for destination: String, amount: Amount) -> (to: String, value: String?, data: String?) {
✅

2022-10-06 09:12 UTC, gre4ixin commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +                $0.rpcURL = blockchain.getJsonRpcURLs(infuraProjectId: config.infuraProjectId)![0]
✅

2022-10-06 10:37 UTC, tureck1y approved these changes, later dismissed

2022-10-06 10:37 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        guard let transactionWithCorrectFee = try? createTransaction(amount: transaction.amount, fee: Amount(with: wallet.blockchain, value: transaction.fee.value - (lastLayer1FeeAmount?.value ?? 0))
NP: Строка имхо длинновата

2022-10-06 21:44 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                }
поправил

2022-10-06 21:44 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +        guard let transactionWithCorrectFee = try? createTransaction(amount: transaction.amount, fee: Amount(with: wallet.blockchain, value: transaction.fee.value - (lastLayer1FeeAmount?.value ?? 0))
укоротил

2022-10-06 21:44 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Ethereum/ContractInteractor.swift
> +                }
поправил

2022-10-06 21:44 UTC, gre4ixin commented on BlockchainSdk/Common/Utils/ContractABI.swift
> +    func optimismLayer1GasFeeABI() -> String {
поправил

2022-10-07 04:45 UTC, tureck1y approved these changes, later dismissed

2022-10-07 05:58 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +            }
@gre4ixin ?

2022-10-07 06:08 UTC, Balashov152 submitted a review, later dismissed

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +
Лишний код

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
>          case .bitcoinCash(let testnet):
Надо вернуть

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
>          case .bitcoinCash(let testnet):
И перед этим блоком тоже

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/Common/WalletManagerFactory.swift
> +            let blockchair: BlockchairNetworkProvider?
blockcypherProvider, blockchairProvider

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    var rpcURL: URL!
let rpcURL

Инициализируется в конструкторе

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +
Лишняя пустая строка

2022-10-07 10:14 UTC, megakoko commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                    return amount
Можно сразу и возвращать

2022-10-07 10:18 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +                    return amount
✅

2022-10-07 10:19 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +
✅

2022-10-07 10:19 UTC, gre4ixin commented on BlockchainSdk/WalletManagers/Optimism/OptimismWalletManager.swift
> +    var rpcURL: URL!
✅

2022-10-07 10:19 UTC, gre4ixin commented on BlockchainSdk/Common/WalletManagerFactory.swift
>          case .bitcoinCash(let testnet):
✅

2022-10-07 10:24 UTC, megakoko approved these changes

2022-10-07 10:26 UTC, Balashov152 approved these changes

2022-10-07 10:44 UTC, tureck1y approved these changes
лучше уже и не напишешь

2022-10-07 10:44 UTC, merged