Bss 70 parsing pending transactions
tangem/blockchain-sdk-swift pull request #31
Opened 2021-06-16 10:13 UTC by Andoran90

2021-06-16 10:33 UTC, lazutkin-andrey submitted a review, later dismissed

2021-06-17 11:20 UTC, tureck1y requested changes
В целом все ок. Пулл-реквест очень большой, надо поработать над  неймингом, комментами  и подчистить артефакты. Может что-то можно отрефакторить и упростить?  Очень много всяких промежуточных структур в принципе по сдк появилось, протоколов. Много добавилось публичных методов, непонятно, что они делают.  Мне не нравится, что сдк переусложняется. Пару фич добавили и я вообще перестаю понимать что там к чему. Похоже настало время провести  рефакторинг сдк по области видимости и вложенности типов.

2021-06-17 11:20 UTC, tureck1y commented on BlockchainSdk/Common/WalletManager.swift
> +    func updateRecentTransactionsBasic(_ transactions: [BasicTransactionData]) {
Со стороны перестало быть понятно что происходит вообще. Предлагаю либо доку к методу добавить либо название другое. Что такое BasicTransactionData? Что такое TransactionsBasic? Если это одно и то же, то предлагаю назвать одинаково

2021-06-17 11:20 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Bitcoin/BitcoinNetworkProvider.swift
> +//    init(balance: Decimal, hasUnconfirmed: Bool, recentTransactions: [BasicTransactionData], unspentOutputs: [BitcoinUnspentOutput]) {
стираем?

2021-06-17 11:20 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Ethereum/EthereumNetworkService.swift
> +//<<<<<<< HEAD
удаляем? Тут конфликт какой-то был

2021-06-17 11:38 UTC, Andoran90 commented on BlockchainSdk/Common/WalletManager.swift
> +    func updateRecentTransactionsBasic(_ transactions: [BasicTransactionData]) {
это все произошла из-за синхронизации с андроидовским блокчеином, план был затестить все в моем исполнении и если будет плохо переключиться на андроидовскую версию

2021-06-17 11:44 UTC, Andoran90 commented on BlockchainSdk/WalletManagers/Bitcoin/BitcoinNetworkProvider.swift
> +//    init(balance: Decimal, hasUnconfirmed: Bool, recentTransactions: [BasicTransactionData], unspentOutputs: [BitcoinUnspentOutput]) {
то же что и предыдущий коммент. это для перехода на андроидовскую версию, план Бе

2021-06-18 06:17 UTC, lazutkin-andrey approved these changes

2021-06-18 07:54 UTC, tureck1y approved these changes

2021-06-18 07:54 UTC, merged