IOS-3664 Add implementation after review comments
tangem/blockchain-sdk-swift pull request #343
Opened 2023-06-21 14:16 UTC by skibinalexander

Поправил с учетом комментариев закрытого МР

2023-06-21 14:38 UTC, tureck1y approved these changes, later dismissed

2023-06-21 14:38 UTC, tureck1y commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +        let nextProviderIndex = currentProviderIndex + 1 >= providers.count ? 0 : currentProviderIndex + 1
Просил curentProviderindex + 1 написать один раз)

2023-06-21 14:38 UTC, tureck1y commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +                    ExceptionHandler.shared.handleAPISwitch(
Еще момент заметил, что у тебя отправляется событие переключения, хотя само переключение случается позже, а может и вовсе не случиться, если уже было переключение. Видимо надо поправить метод needRetry.

2023-06-21 14:39 UTC, tureck1y requested changes
Не то нажал

2023-06-21 14:40 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +        let nextProviderIndex = currentProviderIndex + 1 >= providers.count ? 0 : currentProviderIndex + 1
> Просил curentProviderindex + 1 написать один раз)

А окей, не так понял "отрефачить"

2023-06-21 15:09 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +    private func switchProviderHostOnNextIndex(for errorHost: String) -> Int? {
Здесь не очень красиво выглядит, но чтобы совсем механизм не отломать оставил как было с return

2023-06-22 09:48 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +                    Log.network("Switching to next publisher on host")
Думал оставить как было , чтобы логику не менять , сейчас помещу :)

2023-06-22 09:57 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +    private func switchProviderHostOnNextIndex(for errorHost: String) -> Int? {
> switchProviderIfNeeded

В целом да можно, так думаю будет удобнее, не думаю что понадобится как то менять

2023-06-23 07:13 UTC, tureck1y approved these changes

2023-06-23 07:36 UTC, Balashov152 approved these changes

2023-06-23 07:56 UTC, merged