Feature/ios 3987 add chia address service
tangem/blockchain-sdk-swift pull request #363
Opened 2023-07-13 09:02 UTC by skibinalexander

Add integration chia blockchain

2023-07-13 10:32 UTC, Balashov152 commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    private static let BECH32_CONST = UInt32(1)
```suggestion
    private static let bech32mConst = UInt32(0x2bc830a3)
    private static let bech32Const = UInt32(1)
```
в идеале хоть какой нибудь коммент, почему так, откуда взялось

2023-07-13 10:32 UTC, Balashov152 commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    @discardableResult
а зачем декодить, если не смотришь результат?)

2023-07-13 10:32 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +        let puzzle = Data(hex: "ff02ffff01ff02ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff0bff80808080ff80808080ff0b80ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff0
тоже бы документацию, почему именно такой puzzle )

2023-07-13 10:32 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    func testChiaAddressService() throws {
Вот тут вроде как можно поглядеть адреса, для тестов
https://github.com/irulast/chia-crypto-utils/blob/f4ab826579d19b2d2fe99d8395b3ea9b5fe8c35b/test/util/test_data.dart#L43

2023-07-13 10:32 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    func testChiaAddressService() throws {
или вот тут есть разная документация
https://github.com/Chia-Network/chia-docs/blob/4f4cf5d4f07e77cef62e9cc8822ea7d632c9d593/docs/guides/crash-course/signatures.md?plain=1#L56

2023-07-13 10:35 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +    func testChiaAddressService() throws {
Тесты пока не финалил, это было для того чтобы пазл проверить. Добавлю в текущий МР - окс

2023-07-13 10:36 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +        let puzzle = Data(hex: "ff02ffff01ff02ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff0bff80808080ff80808080ff0b80ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff0
> тоже бы документацию, почему именно такой puzzle )

Добавлю ссылку на доку

2023-07-13 10:37 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    private static let BECH32_CONST = UInt32(1)
Ну коммент думаю не нужен, потому что это по стандарту taproot адреса, могу ссылочку закрепить, но в целом это в официальной доке в заголовке указано

2023-07-13 10:37 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    @discardableResult
> а зачем декодить, если не смотришь результат?)

Проверю, может на валидацией крутил throw

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    private static let bech32mConst = UInt32(0x2bc830a3)
Оформи пожалуйста как enum Constants в extension у Bech32.

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +        let puzzle = Data(hex: "ff02ffff01ff02ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff0bff80808080ff80808080ff0b80ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff0
тоже тогда надо в константы вынести, некрасиво болтается

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +        let encodeValue = Bech32(isBech32m: true).encode(HRP(isTestnet: isTestnet).rawValue, values: puzzleHash)
давай как-то облагородим. Или на переменные разнести или интерфейс надо упростить

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(isBech32m: Bool = false) {
что такое isBech32m?

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +import BitcoinCore
можно убрать BitcoinCore?

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    public enum HRP: String {
public прям обязательно?

2023-07-14 08:14 UTC, tureck1y commented on BlockchainSdk/Common/Utils/ClvmProgram.swift
> +    struct Iterator<T>: IteratorProtocol {
не получится приватным сделать?

2023-07-14 08:21 UTC, skibinalexander commented on BlockchainSdk/Common/Utils/ClvmProgram.swift
> +    struct Iterator<T>: IteratorProtocol {
> не получится приватным сделать?

Вообще хотел вынести в общий ShelIterator, если общий не нужен , Давай запривачу

2023-07-14 08:21 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    private static let bech32mConst = UInt32(0x2bc830a3)
> Оформи пожалуйста как enum Constants в extension у Bech32.

Да, ок, сделаю

2023-07-14 08:22 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +import BitcoinCore
> можно убрать BitcoinCore?

Да, спс, осталось после проб и ошибок

2023-07-14 08:22 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +        let puzzle = Data(hex: "ff02ffff01ff02ffff01ff04ffff04ff04ffff04ff05ffff04ffff02ff06ffff04ff02ffff04ff0bff80808080ff80808080ff0b80ffff04ffff01ff32ff02ffff03ffff07ff0580ffff01ff0bffff0102ffff0
> тоже тогда надо в константы вынести, некрасиво болтается

Да, окей разобью

2023-07-14 08:24 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(isBech32m: Bool = false) {
> что такое isBech32m?

Формат декода сделал для 2х стандартов, bech32 это который segwit и есть новый стандарт taproot, в доке выше они 2 закреплены. Отличаются по факту константой при декодинге, нужен флаг какой, выбора константы

2023-07-14 08:30 UTC, skibinalexander commented on BlockchainSdk/Common/Utils/ClvmProgram.swift
> +class ClvmNode {
> Если это нужно только для Chiа, то давай перенесем это в папку с Chia, не надо в Common

Вообще это универсальный механизм, поэтому вынес в common, пока используется в Chia, давай действительно пока переложу

2023-07-14 09:15 UTC, skibinalexander commented on BlockchainSdk/Common/Utils/ClvmProgram.swift
> +    private(set) var right: ClvmNode?
Сделал приватными, на структуру не получится там рекурсия

2023-07-26 07:54 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain+AllCases.swift
> +            .chia(testnet: false)
`.telos` пропал как будто

2023-07-26 07:54 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +    }
```suggestion
    func hash() throws -> Data {
        if let value = atom {
            return Data([1] + value).sha256()
        } else if let left = try left?.hash(), let right = try right?.hash() {
            return Data([2] + left + right).sha256()
        }
        
        throw NSError()
    }
```

Так попроще как будто)

2023-07-26 07:54 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +        typealias Element = T
```suggestion
    private struct Iterator<Element>: IteratorProtocol {
```

Можно вот так сразу без `typealias`

2023-07-26 07:54 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +    }
```suggestion
    mutating func next(byteCount: Int) throws -> Array<Element> {
        (0 ..< byteCount).map {
            guard let next = next() else {
                throw IteratorError.undefinedElement
            }
            
            return next
        }
    }
```

можно вот так, ну и как есть тоже норм для дебага

2023-07-26 07:54 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +        ).value
Вообще супер если есть ссылка откуда инфа взята)
Если сам делал, то пофиг )

2023-07-26 07:59 UTC, tureck1y requested changes

2023-07-26 07:59 UTC, tureck1y commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(constant: Constant = .bech32) {
Constants используем когда приватный тип. А раз в конструкторе торчит, то лучше читаемое название.  Например type, algorithm итп

2023-07-26 09:00 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +        ).value
Генерили тесты с андроидом

2023-07-26 09:03 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +    }
> Так попроще как будто)

Поправил, дебажил, поэтому пришлось на условия разбить

2023-07-26 09:03 UTC, skibinalexander commented on BlockchainSdk/Common/Blockchain+AllCases.swift
> +            .chia(testnet: false)
Подтянул последние изменения

2023-07-26 09:23 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(isBech32m: Bool = false) {
Дока Вначале файла:

//  Base32 address format for native v0-16 witness outputs implementation
//  BECH32 - https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
//  BECH32M - https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki#L4

2023-07-26 13:36 UTC, Balashov152 approved these changes, later dismissed

2023-07-26 15:22 UTC, tureck1y commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(type: ConstantType = .bech32) {
Предлагаю так
`init(variant: Variant = .bech32)`
Основываясь на этом предложении из доки: 
This document defines an improved variant of Bech32 called Bech32m

2023-07-26 15:48 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(type: ConstantType = .bech32) {
Да , давай

2023-07-27 10:57 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        XCTAssertEqual("txch14gxuvfmw2xdxqnws5agt3ma483wktd2lrzwvpj3f6jvdgkmf5gtq8g3aw3", expectedAddress)
нет теста на валидацию адреса, проглядел когда ревьювил в прошлый раз

2023-07-27 10:57 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let expectedAddress = try addressService.makeAddress(
тогда это не expected же)

2023-07-27 11:01 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let expectedAddress = try addressService.makeAddress(
Угу тут поменяю , тестам мало внимание уделял , в следующих МР еще добавятся. Поменяю

2023-07-27 11:20 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    enum Constans: String {
enum Constants {
static let puzzleReveal = ....
static let  fingerprint = "ff018080"
}

2023-07-27 11:20 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    private let constans = ChiaAddressService.Constans.self
что-то лишнее

2023-07-27 12:15 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +        XCTAssertEqual("txch14gxuvfmw2xdxqnws5agt3ma483wktd2lrzwvpj3f6jvdgkmf5gtq8g3aw3", expectedAddress)
На тесты завожу отдельную задачу всегда, на адрес, транзакцию , размер, там еще все равно жирный МР будет и изменения в тестах будут

2023-07-27 12:26 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        XCTAssertEqual("txch14gxuvfmw2xdxqnws5agt3ma483wktd2lrzwvpj3f6jvdgkmf5gtq8g3aw3", expectedAddress)
ну на создание есть, на валиацию тоже надо сразу. Отдельно не надо. Льем только протезированный код юнитами

2023-07-27 12:30 UTC, skibinalexander commented
В виду того что ревью что уже в другой ветке, есть изменения с аффектом на текущие , подтащил от туда изменения + учел комменты

2023-07-27 12:38 UTC, tureck1y requested changes

2023-07-27 12:38 UTC, tureck1y commented on BlockchainSdk/Common/Address/AddressTypesConfig.swift
> +            :
так оставим двоеточие?

2023-07-27 12:38 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    private let constants = ChiaConstant.self
зачем?

2023-07-27 12:38 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
- не надо все константы со всех файлов собирать в одном месте
- я же написал уже паттерн, посмотри пожалуйста как мы делаем с enum Constants
- методам тут не место, пусть будут только там, где вызываются

2023-07-27 15:33 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
Эти методы нужны будут как в адрес сервисе , так в билдере транзакций , можно просто переименовать как-то ChiaHelpers?

2023-07-27 15:35 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    private let constants = ChiaConstant.self
Уберу, но так тоже можно же , чтобы класс не отсвечивал большими буквами, если режет глаз , напишу через обращение к классу

2023-07-27 15:36 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
Нужно где - то хранить статичные элементы , название константы окей не подходит , надо другое , либо предложение как разнести ? Константы отдельно методы дублировать по сущностям ?

2023-07-27 15:41 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
И для наеймспейса говорили enum ок использовать

2023-07-31 07:15 UTC, skibinalexander commented on BlockchainSdk/Common/Address/AddressTypesConfig.swift
> +            :
После рефакторинга вроде решилось

2023-07-31 07:21 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    private let constants = ChiaConstant.self
это что-то совсем лишнее) Constants.constant1 ничего не режет)

2023-07-31 07:21 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
Если переиспользуется, то надо cделать какую-нибудь ChiaUtils и там все сделать

2023-07-31 07:58 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
> Если переиспользуется, то надо cделать какую-нибудь ChiaUtils и там все сделать

Ага разнес по файлам, и сделал ChiaPuzzle сущность

2023-07-31 08:09 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    private let constants = ChiaConstant.self
> это что-то совсем лишнее) Constants.constant1 ничего не режет)

Урал

2023-07-31 08:11 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaAddressService.swift
> +    enum Constans: String {
> enum Constants {
> static let puzzleReveal = ....
> static let fingerprint = "ff018080"
> }

Вынес в Отдельный файл констант только по фингерпринтам

2023-07-31 08:11 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +        XCTAssertEqual("txch14gxuvfmw2xdxqnws5agt3ma483wktd2lrzwvpj3f6jvdgkmf5gtq8g3aw3", expectedAddress)
> ну на создание есть, на валиацию тоже надо сразу. Отдельно не надо. Льем только протезированный код юнитами

Добавил по 3 теста на валидацию

2023-07-31 08:11 UTC, skibinalexander commented on BlockchainSdk/Extensions/BlockchainUtils/Bech32.swift
> +    init(constant: Constant = .bech32) {
> Constants используем когда приватный тип. А раз в конструкторе торчит, то лучше читаемое название. Например type, algorithm итп

Поменял на понятный variant

2023-08-02 08:28 UTC, tureck1y requested changes

2023-08-02 08:28 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaConstant.swift
> +enum ChiaConstant {
Так этот то файл зачем остался, его надо спрятать в ChiaPuzzle. Посмотри пожалуйста как константы оформлены в BLSUtils. Надо сделать также

2023-08-02 08:28 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaGenesisChallenge.swift
> +enum ChiaGenesisChallenge {
нигде не используется, поэтому я не могу понять в каком виде эта структура должна существовать, давай добавим когда уже будет использование

2023-08-02 08:28 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaHRP.swift
> +enum ChiaHRP: String {
1) используется только в адрес сервисе? Тогда пусть внутри и будет.
2) Странная конструкция enum c init. Даже просто статик функция будет компактнее выглядеть

2023-08-02 08:28 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaPuzzle.swift
> +        return try Data(bech32.convertBits(data: dataBytes.bytes, fromBits: 5, toBits: 8, pad: false))
вместо Data(hex: лучше использовать Extensions из TangemSdk

2023-08-02 08:28 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaPuzzle.swift
> +    static func getPuzzle(walletPublicKey: Data) -> Data {
может лучше
getPuzzle(from/for walletPublicKey: Data)
getPuzzleHash(from/for address: String)

Я бы еще статику убрал

2023-08-02 09:30 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaGenesisChallenge.swift
> +enum ChiaGenesisChallenge {
> нигде не используется, поэтому я не могу понять в каком виде эта структура должна существовать, давай добавим когда уже будет использование

Убрал

2023-08-02 09:31 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaPuzzle.swift
> +        return try Data(bech32.convertBits(data: dataBytes.bytes, fromBits: 5, toBits: 8, pad: false))
> вместо Data(hex: лучше использовать Extensions из TangemSdk

- Переделал

2023-08-02 11:02 UTC, tureck1y approved these changes

2023-08-02 11:24 UTC, Balashov152 approved these changes

2023-08-02 11:27 UTC, merged