Feature/3913 add chia transaction builder
tangem/blockchain-sdk-swift pull request #381
Opened 2023-08-02 12:06 UTC by skibinalexander

2023-08-02 12:09 UTC, skibinalexander commented on BlockchainSdk/Common/Factories/WalletFactory.swift
Тут лишнее уберу, добавил для игнорирования до дебага

2023-08-07 07:53 UTC, skibinalexander commented
Не мерджить!
Мне нужно будет после ревью, сменить тег в TangemSdk

2023-08-10 07:58 UTC, tureck1y commented on Podfile.lock
> +  - TangemSdk (from `https://github.com/Tangem/tangem-sdk-ios.git`, tag `develop-bls-signature`)
в сдк нужен мр уже тоже

2023-08-10 07:58 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkUrl.swift
> +    case fireacademy(isTestnet: Bool)
NP: fireAcademy

2023-08-10 07:58 UTC, tureck1y commented on BlockchainSdk/Common/BlockchainSdkConfig.swift
> +    struct FireacamyApiKeys {
надо public наверное добавить?

2023-08-10 07:58 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/Chia+Array.swift
> +    func toSolution() throws -> Data {
такие специфичные штуки лучше делать fileprivate в файле где используется (ChiaTransactionBuilder).

Пройдись плиз по остальным Chia+ файлам.

2023-08-10 09:27 UTC, skibinalexander commented on BlockchainSdk/Common/BlockchainSdkConfig.swift
> +    struct FireacamyApiKeys {
> надо public наверное добавить?

Вроде как договаривались public у extension делать + форматер кажется настроен

`public extension BlockchainSdkConfig `

2023-08-10 09:29 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkUrl.swift
> +    case fireacademy(isTestnet: Bool)
Обновил

2023-08-10 10:19 UTC, tureck1y commented on BlockchainSdk/Common/BlockchainSdkConfig.swift
> +    struct FireacamyApiKeys {
ну ты как проинициализируешь эту структуру из приложения?

2023-08-10 13:22 UTC, tureck1y commented on BlockchainSdk/Common/BlockchainSdkConfig.swift
> +    struct FireAcamyApiKeys {
Очепятка

2023-08-10 13:25 UTC, megakoko commented on BlockchainSdkExample/BlockchainSdkExampleViewModel.swift
> +            .chia(testnet: false)
Запятая

2023-08-10 13:32 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/Chia+Int64.swift
> +    func chiaEncode() -> Data {
> Эта осталась. Можно тоже спрятать под fileprivate?

Не выходит, сущности которые используют не видят сигнатуру. При установлении спека все равно не видно будет, потому что нет public, поэтому думаю ок

2023-08-10 13:35 UTC, skibinalexander commented on BlockchainSdkExample/BlockchainSdkExampleViewModel.swift
> +                                                                          fireAcademyApiKeys: .init(
Да, давай выровняю в строчку одну

2023-08-10 13:40 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/Chia+Int64.swift
> +    func chiaEncode() -> Data {
Понял, давай тогда плиз сделаем по гайдам эпл chiaEncoded, добавим описание что метод конкретно делает и может стоит на var переделать?

2023-08-10 13:42 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/Chia+Int64.swift
> +    func chiaEncode() -> Data {
> Понял, давай тогда плиз сделаем по гайдам эпл chiaEncoded, добавим описание что метод конкретно делает и может стоит на var переделать?

Да, окей, сейчас посмотрю

2023-08-10 14:11 UTC, skibinalexander commented
- [ ] https://github.com/tangem/tangem-sdk-ios/pull/317

2023-08-10 16:43 UTC, Balashov152 requested changes

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                }
```suggestion
                .map { response in
                    return response.coinRecords.map { $0.coin }
                }
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                }
Надо бы `hash` транзакции вернуть

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                }
```suggestion
                .map { response in
                    let fees = response.estimates.map { estimate in 
                    let value = estimate /  self.blockchain.decimalValue
                    let amount = Amount(with: self.blockchain, value: value)
                    return Fee(amount)
                    }
                    return fees
                }
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkUrl.swift
> +enum ChiaEndpointType {
Не думал, может друг в друга засунуть ?

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaNetworkProvider.swift
> +    // MARK: - HostProvider
```suggestion
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaProviderTarget.swift
> +            jrpcRequest = (try? body.asDictionary(with: encoder)) ?? [:]
может в одном месте только `?? [:]` сделать ? Почище будет

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaProviderTarget.swift
> +
```suggestion
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain+AllCases.swift
> +            .chia(testnet: false)
```suggestion
            .chia(testnet: false),
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain.swift
>              }
что то не то

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/Common/WalletAssembly/ChiaWalletAssembly.swift
> +        )
```suggestion
        var providers: [ChiaNetworkProvider] = [
            ChiaNetworkProvider(
                node: .init(
                    apiKeyValue: input.blockchainSdkConfig.fireAcademyApiKeys.getApiKey(for: input.blockchain.isTestnet),
                    endpointType: .fireAcademy(isTestnet: input.blockchain.isTestnet)
                ),
                networkConfig: input.networkConfig
            )
        ]
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +    }
так а метод вышел сделай с параметром (encoder: JSONEncoder = JSONEncoder()) 
и все норм будет)

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    private let blockchain: Blockchain
Давай может без blockchain, просто decimalValue здесь рассчитываемой сделаем, а вот isTestnet передать можно просто в init

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    }
```suggestion
    enum Constants {
        static let coinSpendCost: Int = 4500000
        static let createCoinCost: Int = 2400000
    }
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +}
```suggestion
    enum GenesisChallenge {
        private static let mainnet = "ccd5bb71183532bff220ba46c268991a3ff07eb358e8255a65c30a2dce0e5fbb"
        private static let testnet = "ae83525ba8d1dd3f09b277de18ca3e43fc0af20d20c4b3e92ef2a48bd291ccb2"
        
        static func challenge(isTestnet: Bool) -> String {
            return isTestnet ? testnet : mainnet
        }
    }
}
```
по факту в названии же есть `genesisChallenge` можно и не писать

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +        let conditions = ClvmProgram.from(list: self.map { $0.toProgram() })
```suggestion
        let conditions = ClvmProgram.from(list: map { $0.toProgram() })
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +        do {
может лучше 
Just(())
.receive(on: DispatchQueue.global())
.tryMap { }

и как раз все будет в глобальной очереди и через tryMap ошибки обработаются

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +    private func update(with coins: [ChiaCoin], completion: @escaping (Result<Void, Error>) -> Void) {
```suggestion
private extension ChiaWalletManager {
    func update(with coins: [ChiaCoin], completion: @escaping (Result<Void, Error>) -> Void) {
```

2023-08-10 16:43 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +        }
```suggestion
        } else if let left = left, let right = right {
                return try Data(Byte(0xff)) + left.serialize() + right.serialize()
         } else {
                throw EncoderError.undefinedEncodeException
         }
```

2023-08-10 18:47 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                }
Обсудили пока не получится

2023-08-11 07:14 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/Chia+Int64.swift
> +    var chiaEncode: Data {
chiaEncoded

2023-08-11 08:06 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +}
В целом да, но делал также чтобы с Андроидом совпадало. Твой вариант выглядит симпатичней

2023-08-11 08:50 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +        do {
Ага Обернул

2023-08-11 09:00 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkUrl.swift
> +enum ChiaEndpointType {
> Не думал, может друг в друга засунуть ?

В прошлый раз, как раз оставляли комменты чтобы разбить на сущности :)

2023-08-11 09:09 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +        }
А можешь объяснить, почему тут при выполнении этих условий дропаем все транзакции? Никак не могу понять логику(

2023-08-11 09:09 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaCondition.swift
> +    var conditionCode: UInt64 = 51
1 и 51 тоже какие-то константы из доки?

2023-08-11 09:09 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaModels.swift
> +    // Has to be encoded as a number in JSON, therefore Long is used. It's enough to encode ~1/3 of Chia total supply.
nit: Max/total supply разве не 29кк? Если да - то как-то непонятен и сбивает коммент)

2023-08-11 09:09 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Chia/Common/ClvmProgram.swift
> +        case manyBytesToEncode
nit:
```suggestion
        case tooManyBytesToEncode
```

2023-08-11 09:12 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    }
> А откуда эти значения? Мб коммент + линк на доки добавить сюда?
> А то без нее выглядит как будто они подобраны экспериментальным путем)

Дело в том что они выбраны экспериментальным путем Денисом Батуриным

2023-08-11 09:13 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +                self?.wallet.add(transaction: transaction)
> Похоже на странный сайд-эффект в `map`, как-то можно от этого избавиться, не очень заморачиваясь?
> 
> Мне приходит на ум только подписка самого менеджера на этот сигнал (через `.share` чтобы не гонять два раза запрос) или же выполнять `self?.wallet.add(transaction: transaction)` в `.handleEvents(receiveOutput:)` (что проще)

Подрефачил, договорились с @Balashov152 сделать через Just, выглядит вроде симпатичней, и по остальным менеджерам также

2023-08-11 09:17 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +        }
> А можешь объяснить, почему тут при выполнении этих условий дропаем все транзакции? Никак не могу понять логику(

Это логика сброса отправленных транзакций, в случае если у нас сумма не сошлась , считаем что отправленные выполнились, потому что по логике мы не можем отправлять новую , пока не отправилась текущая

2023-08-11 09:18 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaModels.swift
> +    // Has to be encoded as a number in JSON, therefore Long is used. It's enough to encode ~1/3 of Chia total supply.
> nit: Max/total supply разве не 29кк? Если да - то как-то непонятен и сбивает коммент)

Тут не очень что ты имеешь в виду?

2023-08-11 10:01 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +        let changeAmount = fullAmount - (transactionAmount.uint64Value + transactionFeeAmount.uint64Value)
> Тут вычитание из unsigned - нет ли вероятности напороться на переполнение?
> Если есть - можно заюзать `subtractingReportingOverflow`

64 unsigned должно хватать

2023-08-11 10:02 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaCondition.swift
> +    var conditionCode: UInt64 = 51
> 1 и 51 тоже какие-то константы из доки?

Да, при сборке транзакции

2023-08-11 10:05 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaProviderTarget.swift
> +        ]
> А в этом вообще есть необходимость?
> 
> Вроде же Moya (точнее Alamofire под капотом) сама проставляет как минимум правильный content-type, соответствущий типу `task` (в `ParameterEncoder.swift` например)

Да, удобно видеть явно, что нужно апишке чтобы работать корректно, если мы съедем с alamofire например , придется разбираться проставлять или нет

2023-08-11 10:06 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaNetworkProvider.swift
> +                    throw WalletError.empty
> Эта кинутая ошибка не будет далее безусловно замаплена в `WalletError.failedToParseNetworkResponse`? Если да - то это ожидаемое поведение?

Не суверен, что эта ошибка предназначена для таких целей, @tureck1y подскажи пожалуйста?

2023-08-11 10:24 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaProviderTarget.swift
> +
Пустые строки тут )

2023-08-11 10:25 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +    var allowsFeeSelection: Bool = false
Это требование протокола для экрана Send, показывать или не показывать segment control

2023-08-11 10:26 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +                self?.wallet.add(transaction: transaction)
ну можно как вариант в `.handleEvents(receiveOutput:)` перенести, будет лучше даже)

2023-08-11 12:58 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    }
Тогда можно так и написать, что вычислено эмпирически)

2023-08-11 13:00 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +    var allowsFeeSelection: Bool = false
А такой синтаксис же позволит мутировать снаружи? Надо бы вычисляемой сделать или let

2023-08-11 13:31 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    }
> Тогда можно так и написать, что вычислено эмпирически)

Ок, добавлю

2023-08-11 13:49 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +        let changeAmount = fullAmount - (transactionAmount.uint64Value + transactionFeeAmount.uint64Value)
Так вопрос именно в unsigned, а не в размере - переполнение будет при `1 - 2` например

Или тут такого не может быть в принципе и `(transactionAmount.uint64Value + transactionFeeAmount.uint64Value)` всегда меньше или равно `fullAmount`?

2023-08-11 14:05 UTC, skibinalexander commented
https://github.com/tangem/blockchain-sdk-swift/pull/381#discussion_r1291084452

Completion выкидываю наружу по стеку метода, для удобства
self.update(with: response, completion: completion)

2023-08-13 20:53 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +        let changeAmount = fullAmount - (transactionAmount.uint64Value + transactionFeeAmount.uint64Value)
> Так вопрос именно в unsigned, а не в размере - переполнение будет при `1 - 2` например
> 
> Или тут такого не может быть в принципе и `(transactionAmount.uint64Value + transactionFeeAmount.uint64Value)` всегда меньше или равно `fullAmount`?

В целом согласен, спасибо, посмотрел как у https://github.com/tangem/blockchain-sdk-kotlin/pull/283 Long знаковый, так что вероятно была бы ошибка

2023-08-14 07:13 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +    private func update(with coins: [ChiaCoin], completion: @escaping (Result<Void, Error>) -> Void) {
> А тут вообще нужен комплишен и резалт? Кажется все происходит синхронно и не может зафейлится

Тут, оставил как в остальных местах, выкидываю сразу success через completion

2023-08-14 07:14 UTC, Balashov152 commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +    func asDictionary(with encoder: JSONEncoder) throws -> [String: Any] {
давай с методом на 23 строке объединим) Одинаковые же)

2023-08-14 07:21 UTC, skibinalexander commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +    }
> так а метод выше сделай с параметром (encoder: JSONEncoder = JSONEncoder())
> и все норм будет)

Делал отдельно, чтобы не цепляло остальные изменения, если мы так ок - ок сделаю )

2023-08-14 07:24 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +    private let blockchain: Blockchain
> Давай может без blockchain, просто decimalValue здесь рассчитываемой сделаем, а вот isTestnet передать можно просто в init

да окей

2023-08-14 07:36 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +                self?.wallet.add(transaction: transaction)
> ну можно как вариант в `.handleEvents(receiveOutput:)` перенести, будет лучше даже)

Мне честно сказать через мапу более понятно, ну и собственно в остальных менеджерах также сделано, + там хеш может добавиться и будет совсем хорошо

2023-08-14 07:36 UTC, Balashov152 commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +        let dictionary = try JSONSerialization.jsonObject(with: data, options: .fragmentsAllowed)
`options: .fragmentsAllowed` а это не отстрельнет в местах где раньше было? в чем вообще отличие? только порядок слов поменялся))

2023-08-14 07:40 UTC, skibinalexander commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +        let dictionary = try JSONSerialization.jsonObject(with: data, options: .fragmentsAllowed)
> `options: .fragmentsAllowed` а это не отстрельнет в местах где раньше было? в чем вообще отличие? только порядок слов поменялся))

В документации ничего из особенностей не увидел 
https://developer.apple.com/documentation/foundation/jsonserialization/readingoptions/1416042-allowfragments

2023-08-14 07:45 UTC, Balashov152 commented on Podfile
> +#  pod 'TangemSdk', :path => '../tangem-sdk-ios'
тут получается лишнее изменение )

2023-08-14 07:45 UTC, Balashov152 commented on Podfile
> +
И тут )

2023-08-14 07:45 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/ChiaWalletManager.swift
> +    var allowsFeeSelection: Bool = false
Поправил

2023-08-14 07:47 UTC, skibinalexander commented on Podfile
> +#  pod 'TangemSdk', :path => '../tangem-sdk-ios'
> тут получается лишнее изменение )

Жду еще от @tureck1y тег в TangemSdk можно пока пропустить

2023-08-14 08:03 UTC, m3g0byt3 commented on BlockchainSdk/Extensions/JSONDecoder+.swift
> +        let dictionary = try JSONSerialization.jsonObject(with: data, options: .fragmentsAllowed)
Да вроде просто ренейм без подводных:
```
@available(iOS, introduced: 5.0, deprecated: 100000, renamed: "JSONSerialization.ReadingOptions.fragmentsAllowed")
public static var allowFragments: JSONSerialization.ReadingOptions { get }
```

2023-08-14 08:05 UTC, m3g0byt3 approved these changes, later dismissed

2023-08-14 08:06 UTC, Balashov152 commented on Podfile
> +#  pod 'TangemSdk', :path => '../tangem-sdk-ios'
я просто 7 строку) `#` мы же теперь всегда в плотную держим )

2023-08-15 07:28 UTC, skibinalexander commented on Podfile
> +#  pod 'TangemSdk', :path => '../tangem-sdk-ios'
Все так, Саня обещал ругаться )

2023-08-15 08:20 UTC, Balashov152 commented on Podfile
> +#  pod 'TangemSdk', :path => '../tangem-sdk-ios'
Да давайте в плотную, что бы точно одинаково было)

2023-08-15 08:29 UTC, tureck1y submitted a review, later dismissed

2023-08-15 08:57 UTC, Balashov152 submitted a review, later dismissed

2023-08-15 15:03 UTC, Balashov152 approved these changes

2023-08-15 15:20 UTC, tureck1y approved these changes

2023-08-15 15:32 UTC, merged