IOS-3978 Add BitcoinTransactionHistoryProvider
tangem/blockchain-sdk-swift pull request #382
Opened 2023-08-03 15:25 UTC by Balashov152

2023-08-08 11:13 UTC, Andoran90 requested changes

2023-08-08 11:13 UTC, Andoran90 commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +        guard !transactions.isEmpty else {
```suggestion
        if transactions.isEmpty {
```

2023-08-08 11:13 UTC, Andoran90 commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +                      let address = input.addresses.first else {
хм, странно, а зачем тут массив?.. и в аутпуте тоже массив адресов. В каких случаях там может быть несколько адресов и почему мы можем брать только первый?

2023-08-10 08:21 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookResponses.swift
> +    let page: Int
это не заафектит уже имеющиеся запросы? У них все запросы с пейджингом?

2023-08-10 08:21 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +    }
что-то можно private сделать?

2023-08-10 08:37 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookTarget.swift
> +        /// page: specifies page of returned transactions, starting from 1. If out of range, Blockbook returns the closest possible page.
✅

2023-08-10 08:39 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookTarget.swift
> +        /// pageSize: number of transactions returned by call (default and maximum 1000)
✅

2023-08-10 08:42 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +        guard !transactions.isEmpty else {
✅

2023-08-10 08:42 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +                      let address = input.addresses.first else {
честно хз, в документации не нашел, по факту может для других блокчейнов актуально, не может же быть output с двумя адресами

2023-08-10 08:43 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookResponses.swift
> +    let page: Int
Ну вообще по документации в ответе всегда есть page, totalPages, itemsOnPage

2023-08-10 08:44 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Bitcoin/TransactionHistory/TransactionHistoryMapper.swift
> +    }
Оба можно, ✅

2023-08-10 11:07 UTC, tureck1y approved these changes

2023-08-10 11:17 UTC, Andoran90 approved these changes

2023-08-14 17:40 UTC, merged