Ios 3914 add chia tests
tangem/blockchain-sdk-swift pull request #384
Opened 2023-08-06 21:36 UTC by skibinalexander

Вливать после. feature/3913-add-chia-transaction-builder
Поэтому драфт. Также есть проблема с десириализацией, разбираюсь

2023-08-15 16:08 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaModels.swift
> +class ChiaCoinSpend: Codable {
А чего на класс поменялось?

2023-08-15 16:37 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Chia/Common/ChiaModels.swift
> +class ChiaCoinSpend: Codable {
Там нужно менять значение у модели , соотвественно должна быть мутабильна , и обращение ссылке

2023-08-15 16:38 UTC, tureck1y submitted a review, later dismissed
Бегло посмотрел

2023-08-15 18:00 UTC, skibinalexander commented
> Бегло посмотрел

Ага , добавлю @megakoko

2023-08-16 08:06 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        XCTAssertTrue(buildToSignResult.contains([expectedHashToSign1]))
Почему contains?

2023-08-16 08:06 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        ].map { Data(hexString: $0) }
```suggestion
        let hashesToSign = [          "A45B057958AF4E155FDF2470F43BE8E2B26A9084EC28A34021FBE0F288881E197A73CC27FF88E82DB4C6BD0DD9D5A55A0B080381D4C4314C2473B2C4325BED52989D810869D7466540B0A896EF79011550E34C0B0AB6BB61429A7AA7699DF9EF",
"AED861A416CD4B3F06B80658C86B5A66B7998988382F5BE448CAC67C4097F78E3F25E1976F70C033370DDF84A69AA7C0186B1EC7D693D87B21B5B03B35C3B1A0E6BDF1487D70994D05E5F151D3F84F70EEE322D1662B19F8873011392823950B"
        ].map { 
        Data(hexString: $0) 
        }
```

2023-08-16 08:06 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +    }
Лучше бы в соответствующие кейсы сверху положить, чтобы с вычисляемой подписью работать

2023-08-16 08:15 UTC, Balashov152 requested changes

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Chia/ChiaTransactionBuilder.swift
> +        return spendBundle
можно и ревертнуть как будто )

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let feeValue = Decimal("0.000000164238")!
```suggestion
        let sendValue: Decimal = 0.0003
        let feeValue: Decimal = 0.000000164238
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +    func testTransactionVector1() {
```suggestion
    func testTransactionVector1() throws {
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let sourceAddress = try! addressService.makeAddress(from: walletPublicKey)
```suggestion
        let sourceAddress = try addressService.makeAddress(from: walletPublicKey)
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let signedTransaction = try! transactionBuilder.buildToSend(signatures: [signature1])
```suggestion
        let buildToSignResult = try transactionBuilder.buildForSign(transaction: transactionData)
        let signedTransaction = try transactionBuilder.buildToSend(signatures: [signature1])
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        XCTAssertTrue(buildToSignResult.contains([expectedHashToSign1]))
По логике `XCTAssertEqual` должно быть

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        try! XCTAssertEqual(jsonEncoder.encode(signedTransaction), jsonEncoder.encode(expectedSignedTransaction))
```suggestion
        try XCTAssertEqual(jsonEncoder.encode(signedTransaction), jsonEncoder.encode(expectedSignedTransaction))
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let feeValue = Decimal("0.000000027006")!
```suggestion
        let sendValue: Decimal  = 0.02
        let feeValue: Decimal = 0.000000027006
```

2023-08-16 08:15 UTC, Balashov152 commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +    func testTransactionVector2() {
```suggestion
    func testTransactionVector2() throws {
```
тоже добавь throws и у всех `try!` убери плиз `!`
Будем норм хэндлить все ошибки

2023-08-16 08:18 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +    func testTransactionVector2() {
Почему кстати ios16+?

2023-08-16 09:21 UTC, Balashov152 approved these changes

2023-08-16 09:22 UTC, skibinalexander commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let feeValue = Decimal("0.000000164238")!
Проверили, правильнее делать из строки

2023-08-16 09:22 UTC, skibinalexander commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +        let feeValue = Decimal("0.000000027006")!
Проверили , из строки должно быть

2023-08-16 09:23 UTC, megakoko commented on BlockchainSdk/BlockchainService/Chia/Provider/ChiaProviderResponses.swift
> +    let estimates: [Int64]
Может лучше наоборот все на беззнаковые перевести? В два раза больше влезет

2023-08-16 09:24 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
А в официальных / 3rdparty репозиториях связанных с чией нет тестов на транзакции? Не спрашивали у ребят из чии?

Мы для каспы брали из исходников ноды

2023-08-16 09:27 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
> +    }
Я имею в виду сделать так, чтобы мы в testTransactionVector1 / 2 проверяли это. Сейчас ты захардкодил какие-то хеши и их проверяешь. А так будет понятно, что хеши — результат сборки транзакций.

2023-08-16 09:38 UTC, skibinalexander commented on BlockchainSdkTests/Chia/ChiaTests.swift
Можно Посмотреть в других референсах конечно подойдет ли что нибудь не знаю , но точно в рамках другой задачи уже

2023-08-16 09:42 UTC, megakoko commented on BlockchainSdkTests/Chia/ChiaTests.swift
@tureck1y не будем сейчас на этом останавливаться?

2023-08-16 10:24 UTC, tureck1y commented on BlockchainSdkTests/Chia/ChiaTests.swift
В тесты надо передать как есть и поискать данные для тестов параллельно. Не стоит задерживать релиз

2023-08-16 11:27 UTC, megakoko approved these changes

2023-08-16 11:56 UTC, tureck1y approved these changes

2023-08-16 12:52 UTC, merged