IOS-4203 IOS-4175 Update implementation sending parameters for analytics
tangem/blockchain-sdk-swift pull request #389
Opened 2023-08-08 16:15 UTC by skibinalexander

Исправил передачу понятно url для аналитики. Поэтому пришлось добавить префиксы. И изменил проверку MultinetworkProvider. Старался делать так , чтобы не сильно менялись контракты

2023-08-09 08:38 UTC, skibinalexander commented
Пока не закидывал в ревью чтобы посмотреть имплементацию и собрать сборку для QA

2023-08-16 15:20 UTC, tureck1y requested changes

2023-08-16 15:20 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
> +    private let basicHost = "getblock.io"
надо наоборот, не блокчейн тащить в GetBlockBlockBookConfig,
а в BlockBookUtxoProvider его дополнять. Там вот такой код

    var host: String {
        config.host
    }

и знание о блокчейне есть

2023-08-16 15:20 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/NowNodesBlockBookConfig.swift
> +    init(currencySymbol: String, apiKey: String) {
тут то же самое соответственно

2023-08-16 15:20 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Blockcypher/BlockcypherNetworkProvider.swift
> +        return getTarget(for: .fee).baseURL.absoluteString
return не пишем в var

2023-08-16 15:20 UTC, tureck1y commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +        if errorHost.hostOrNil != self.host.hostOrNil { // Do not switch the provider, if it was switched already and hostOrNil compare only host value
Вроде hostOrNil не нужен, потому что сравнивать надо полностью по строке в host. Например мы ходим к некоторым провайдером с капи ключом и без. В твоем случае будет баг и не переключится

2023-08-23 14:40 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
> +    private let basicHost = "getblock.io"
Да, хорошее замечание, переделал + выдернул знание о блокчейне совсем

2023-08-23 14:40 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Blockcypher/BlockcypherNetworkProvider.swift
> +        return getTarget(for: .fee).baseURL.absoluteString
Поправил

2023-08-23 14:41 UTC, skibinalexander commented
Еще протестирую, пока перевьюить изменения можно

2023-08-23 14:43 UTC, skibinalexander commented on BlockchainSdkExample/BlockchainSdkExampleViewModel.swift
> +        let publicKey = Wallet.PublicKey(seedKey: wallet.publicKey, derivationType: .none)
Фикс, потому что падает в девелопе, уйдет видимо когда соберемся заливать, иначе не протестировать

2023-08-24 07:54 UTC, megakoko commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +
Лишние изменения пробелов

2023-08-24 07:54 UTC, megakoko commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/NowNodesBlockBookConfig.swift
> +
Лишнее

2023-08-24 07:54 UTC, megakoko commented on BlockchainSdk/BlockchainService/Blockcypher/BlockcypherNetworkProvider.swift
> +        getTarget(for: .fee).baseURL.absoluteString
А зачем это изменения?

2023-08-24 07:54 UTC, megakoko commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        "\(blockchain.currencySymbol).\(config.host)"
Давай сделаем config.domain, там то же самое

2023-08-24 07:54 UTC, megakoko commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
А зачем эти изменения?

2023-08-24 08:17 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
> А зачем эти изменения?

По комменту выше, не тащить сюда блокчейн

2023-08-24 08:18 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        "\(blockchain.currencySymbol).\(config.host)"
> Давай сделаем config.domain, там то же самое

Коммент от @tureck1y "не тащим блокчейн в конфиг, а дополняем его здесь,  в виду наличия инфы"

2023-08-24 08:19 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Blockcypher/BlockcypherNetworkProvider.swift
> +        getTarget(for: .fee).baseURL.absoluteString
От какого блокчейна

2023-08-24 08:23 UTC, megakoko commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        "\(blockchain.currencySymbol).\(config.host)"
Уверен, что Саша это имел в виду?

2023-08-24 09:42 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        "\(blockchain.currencySymbol).\(config.host)"
https://github.com/tangem/blockchain-sdk-swift/pull/389#discussion_r1296071796

2023-08-24 10:22 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +
Хотя стоп почему лишние?

2023-08-24 10:48 UTC, megakoko commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +
Почему две строчки подсвечиваются если менял одну?

2023-08-24 10:55 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +
Добавил чтобы не слипалось

2023-08-24 14:34 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
Надо убрать вообще функцию domain for. Лепи префикс к хосту в потребителе и все. Зачем такие сложности.

2023-08-24 14:50 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
Эти получаются лишние в рамках задачм

2023-08-24 14:51 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        "\(blockchain.currencySymbol).\(config.host)"
Domain не подойдет. Нужен стабильный айди хоста, не зависящий от запроса

2023-08-24 14:55 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
Я бы откатил их, в остальном ок

2023-08-24 16:55 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
Да, окей откачусь

2023-08-25 16:02 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/BlockBook/Config/Implementations/GetBlockBlockBookConfig.swift
>      }
Зарезолвилось при мердже последних изменений из develop

2023-08-25 16:30 UTC, skibinalexander commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +
> Что не слипалось? Тут пробелы удалены
> 
> <img alt="Screenshot 2023-08-24 at 14 05 20" width="297" src="https://user-images.githubusercontent.com/12209839/262953609-f3fe4e1a-dcd2-452e-9e4f-bdbe39b97287.png">

Ревертнул

2023-08-25 16:39 UTC, tureck1y approved these changes

2023-08-28 08:10 UTC, megakoko approved these changes

2023-08-28 08:19 UTC, merged