IOS-4172 Add ability to choose `ed25519` or `ed25519_slip_0010` curve
tangem/blockchain-sdk-swift pull request #391
Opened 2023-08-10 08:07 UTC by Balashov152

2023-08-10 08:14 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
А обратная совместисость с тем, что уже сохранено на диске есть?

2023-08-10 08:14 UTC, megakoko commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +                    )
А эти изменения нужны?

2023-08-10 08:14 UTC, megakoko commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +        Blockchain.stellar(curve: .ed25519_slip0010, testnet: isTestnet)
Почему захардкожено?

2023-08-10 08:31 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
ну да, получается что если сохранилась старая кривая ed25519, то она и будет

2023-08-10 08:33 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +                    )
очень много мест, где для получения `decimalValue` нам нужен целый блокчейн создать, жутко не удобно 

Эти по факту не нужны, но надо что то делать с этим

2023-08-10 08:34 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +        Blockchain.stellar(curve: .ed25519_slip0010, testnet: isTestnet)
очень много мест, где для получения decimalValue нам нужен целый блокчейн создать, жутко не удобно

2023-08-10 08:34 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +                    )
Откатил

2023-08-10 10:57 UTC, tureck1y requested changes

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdkTests/TON/TONTests.swift
> +    private var blockchain = Blockchain.ton(curve: .ed25519_slip0010, testnet: true)
надо все подобные тесты на таких блокчейнах делать на двух кривых теперь

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Stellar/StellarNetworkProvider.swift
> +        Blockchain.stellar(curve: .ed25519_slip0010, testnet: isTestnet)
надо будет потом рефачить на decimalValue

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdk/Extensions/TWPublicKeyType+.swift
> +            case .ed25519, .ed25519_slip0010:
интересно как это разрулить для карданы то. Получается нельзя будет это расширение использовать, может коммент напишем?

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdk/Extensions/TWCurve+.swift
> +        case .ed25519, .ed25519_slip0010:
и тут тоже по кардане надо писать коммент тогда

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain+AllCases.swift
>              .rsk,
allMainnetCases надо вообще удалять получается. Или чтобы сет id возвращался. Вот это в приложении работать не будет же

```
/// Blockchains which don't include in supported blockchains by default
    static var testable: Set<Blockchain> {
        Set(Blockchain.allMainnetCases)
            .subtracting(SupportedBlockchains(version: .v1).mainnetBlockchains())
    }
```

2023-08-10 10:57 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        guard curve == .secp256k1 || curve == .ed25519 || curve == .ed25519_slip0010 else {
давай сделаем через curve.supportsDerivation

2023-08-10 11:16 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
Хм, то есть если у меня сейчас есть блокчейн на главной, я его удалю и добавлю заново, то добавится он уже на другой кривой. Верно? Ничего от этого не сломается?

Первый вопрос был скорее про то, что у нас ведь сейчас параметр curve для этих блокчейнов не сохраняется. А тут мы ожидаем что он есть. Оно нормально загрузится, значение по-умолчанию правильное будет?

2023-08-10 11:34 UTC, megakoko commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
Давай в функцию выше загоним чтобы копипасты не было, с циклом по кривым. Оно же на 100% так же должно работать с точки зрения блокчейна?

2023-08-10 11:34 UTC, megakoko commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
И с другими тоже

2023-08-10 11:34 UTC, megakoko commented on BlockchainSdkTests/VectorTests/PublicKeyDerivationAddressTests.swift
> +//        }
А это что?

2023-08-10 11:34 UTC, megakoko commented on BlockchainSdkTests/Vectors/blockchain_vectors.json
> +        "curve": "ed25519_slip0010",
Только одно будем проверять?

2023-08-10 11:59 UTC, megakoko commented on BlockchainSdkTests/Vectors/blockchain_vectors.json
> +        "curve": "ed25519_slip0010",
Так, из того что я понял нужно же и то, и то в тестах сохранить

2023-08-10 12:14 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain+AllCases.swift
>              .rsk,
да, согласен
`allMainnetCases` убрал`public` 
Он останется только для example и для тестов

На уровне приложения получается надо будет самим добавлять в `testable: Set`, по другому что-то никак(

2023-08-10 12:43 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
> Хм, то есть если у меня сейчас есть блокчейн на главной, я его удалю и добавлю заново, то добавится он уже на другой кривой. Верно? Ничего от этого не сломается?

не, в рамках одного конфига = карты будет одна и та же кривая

2023-08-10 12:52 UTC, Balashov152 commented on BlockchainSdk/Extensions/TWCurve+.swift
> +        case .ed25519, .ed25519_slip0010:
тут переделал на blockchain по аналогии с TWPublicKeyType+

2023-08-10 12:54 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain.swift
> +        guard curve == .secp256k1 || curve == .ed25519 || curve == .ed25519_slip0010 else {
✅

2023-08-10 12:55 UTC, Balashov152 commented on BlockchainSdkTests/VectorTests/PublicKeyDerivationAddressTests.swift
> +//        }
это случайно, в рамках тестов залетело

2023-08-10 13:05 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetwork.swift
>      var existentialDeposit: Amount {
Чтобы на уровне приложения не было дополнительных телодвижений. Получили Amount, отформатировали как надо с currencyCode и все

2023-08-10 13:06 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetwork.swift
>      var existentialDeposit: Amount {
надо подумать как работать с Amount нам, а то при изменении кривой приходится лезть туда, где по факту не меняется ничего(
тип decimalValue и currencySymbol те же, а изменения есть

2023-08-10 13:50 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
> чтобы копипасты не было

Это же тесты, она ничем не мешает, тестируем адрес сервис на разной кривой, по мне так все ок)

2023-08-10 13:51 UTC, megakoko commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
Можем поменять один тест и забыть обновить второй. Зачем копипаста если код на 100% одинаковый и можно без нее обойтись?

2023-08-10 13:58 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
Можем поменять один тест и случайно заффектить другой )

ну вообще по хорошему это должны быть разные тесты, паблик ключ ed25519 и ed25519_slip0010 должны быть разные, и адреса тоже должны быть разные
кривая же разная

2023-08-10 14:00 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
Подумаю в целом как с тестами поступить

2023-08-10 14:01 UTC, megakoko commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
Можно иметь единый метод, куда передавать входные-выходные данные и вызывать его из двух разных тестов

2023-08-10 15:19 UTC, Balashov152 commented on BlockchainSdkTests/Solana/SolanaTests.swift
> +// TODO: Will be refactor https://tangem.atlassian.net/browse/IOS-4260
Завел отдельную задачу, тут что то странное тестируется, в плане что только одна проверка на ошибку и все, больше ничего
Надо заново норм тесты написать

2023-08-10 15:19 UTC, Balashov152 commented on BlockchainSdkTests/TON/TONTests.swift
> +    func testCorrectCoinTransactionEd25519() throws {
не понимаю что с гитом, по факту сделал так же как и везде, у входного метода curve и два метода сверху с разными кривыми

2023-08-10 15:20 UTC, Balashov152 commented on BlockchainSdkTests/Common/AddressTests.swift
> +    }
✅

2023-08-10 15:21 UTC, Balashov152 commented on BlockchainSdkTests/TON/TONTests.swift
> +    private var blockchain = Blockchain.ton(curve: .ed25519_slip0010, testnet: true)
Дописал тесты везде где менялась кривая ✅

2023-08-10 15:35 UTC, megakoko commented on BlockchainSdkTests/Solana/SolanaTests.swift
> +// TODO: Will be refactor https://tangem.atlassian.net/browse/IOS-4260
Мы только размер транзакции тестируем. Солана у нас работает через внешний СДК. Планируем переезд на трастволлет

2023-08-11 08:00 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
А загружаться-то нормально будет? Сейчас у .stellar не сохраняется параметр curve. А с этими изменениями мы будем его требовать. Все нормально мигрирует?

2023-08-11 08:01 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case "stellar": self = .stellar(curve: curve, testnet: isTestnet)
Посмотрел по коду, все норм должно быть

2023-08-11 08:07 UTC, megakoko approved these changes

2023-08-11 09:25 UTC, tureck1y approved these changes

2023-08-11 09:26 UTC, merged