IOS-4912: NEAR - add dummy entities and basic implementation
tangem/blockchain-sdk-swift pull request #440
Opened 2023-10-23 11:41 UTC by m3g0byt3

[IOS-4912](https://tangem.atlassian.net/browse/IOS-4912)

2023-10-24 08:42 UTC, Balashov152 commented on BlockchainSdk/ExternalLinkProvider/NEARExternalLinkProvider.swift
> +        }
Дубль 
```suggestion
            if isTestnet {
                return URL(string: "https://testnet.nearblocks.io/txns/\(hash)")!
            }
```

2023-10-24 08:42 UTC, Balashov152 commented on BlockchainSdk/ExternalLinkProvider/NEARExternalLinkProvider.swift
> +    ) {
Как будто лишнее тоже)
```suggestion
    init(isTestnet: Bool) {
```

2023-10-25 07:26 UTC, skibinalexander commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cardano,
Тут съехала отступ?

2023-10-26 15:15 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cardano,
Отступ ты заметил, а то что кривая неправильная - нет 🥲

2023-10-26 15:16 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cardano,
Тут логика должны быть как у всех остальных ed-based. Кардано стоит особняком.

2023-10-26 15:21 UTC, tureck1y requested changes
Кривую ed надо сделать по аналогии, например со стеллар

2023-10-27 11:53 UTC, m3g0byt3 commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/397'/0'"
У меня еще есть вопрос насчет деривации - ее я взял из registry.json у TW.
Но в тоже время офиц кошелек (и видимо ledger) юзают полный путь:
https://github.com/near/near-wallet/blob/master/packages/frontend/src/redux/slices/ledger/index.js#L18C14-L18C35
```
export const LEDGER_HD_PATH_PREFIX = '44\'/397\'/0\'/0\'/';
```


К которому еще добавляется index где надо, например:
```
./packages/frontend/src/components/accounts/batch_ledger_export/AccountExportModal.js:            
const ledgerHdPath = `${LEDGER_HD_PATH_PREFIX}${path}'`;
```

```
./packages/frontend/src/components/accounts/ledger/SetupLedger.js:    
const ledgerHdPath = `${LEDGER_HD_PATH_PREFIX}${confirmedPath}'`;
```

TW объясняют такой формат деривации тем, что по спеке bip44 нет смысла указывать change и index
https://github.com/trustwallet/wallet-core/issues/3387#issuecomment-1691097389

Может ли это быть проблемой?

2023-10-27 11:57 UTC, m3g0byt3 commented on BlockchainSdk/ExternalLinkProvider/NEARExternalLinkProvider.swift
> +        }
~~As intended~~ поправил
![123](https://github.com/tangem/blockchain-sdk-swift/assets/21194149/d4375d78-94d0-46e7-b345-bd7ba83cec4b)

2023-10-27 11:57 UTC, m3g0byt3 commented on BlockchainSdk/ExternalLinkProvider/NEARExternalLinkProvider.swift
> +    ) {
Поправил тут и еще в месте, где передавался единственный параметр в конструктор

2023-10-27 11:58 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cardano,
Такие отступы делает xcode ¯\_(ツ)_/¯

Поправил кривую, сделал конфигурабельной

2023-10-27 12:02 UTC, m3g0byt3 commented
> Кривую ed надо сделать по аналогии, например со стеллар

Поправил, сделал конфигурабельной.

На самом деле по кривым есть вопрос, потому что в `Blockchain+AllCases.swift` есть проперть `allMainnetCases`, в которой для всех edwards задан хардкодом `ed25519_slip0010`

Получается на v1 воллетах это не будет работать?
В аппе эта проперть юзается только в одном месте, в `CommonSwapAvailabilityManager` - не ломает ли это какую-то логику на v1?

Ну и корректно ли в целом отдавать такой хардкод для сторонних потребителей либы?

@tureck1y @Balashov152

2023-10-27 12:03 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> -        case .litecoin, .ducatus, .cardano, .xrp, .rsk, .tezos, .dogecoin, .kusama, .terraV1, .terraV2, .cronos, .octa:
Поправил форматирование тут и ниже, потому что длина некоторых строк начинает превышать не только значения из любых  кодстайлов (100-120 символов) но и любое разумное значение

2023-10-27 12:05 UTC, m3g0byt3 commented on BlockchainSdk/ExternalLinkProvider/NEARExternalLinkProvider.swift
> +        return URL(string: "https://nearblocks.io/address/\(address)")!
Эксплорер на https://explorer.near.org/ станет тыквой в начале 2024

2023-10-27 12:07 UTC, Balashov152 commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/397'/0'"
Вообще все адреса у нас с TW сравнивались, так что при одинаковой seed phrase должны совпадать с TW на Wallet 2.0(где есть импорт)

2023-10-27 12:10 UTC, ba1ashov commented
> > Кривую ed надо сделать по аналогии, например со стеллар
> 
> Поправил, сделал конфигурабельной.
> 
> На самом деле по кривым есть вопрос, потому что в `Blockchain+AllCases.swift` есть проперть `allMainnetCases`, в которой для всех edwards задан хардкодом `ed25519_slip0010`
> 
> Получается на v1 воллетах это не будет работать? В аппе эта проперть юзается только в одном месте, в `CommonSwapAvailabilityManager` - не ломает ли это какую-то логику на v1? 

`Blockchain+AllCases` это костыль просто для того что бы был весь, параметры testnet и curve не используются из него, просто не принималось как сделать весь список )

> Ну и корректно ли в целом отдавать такой хардкод для сторонних потребителей либы?
> 
> @tureck1y @Balashov152

Получается здесь потребители мы) Но а вообще у нас карта влияет на какой кривой она умеет работать, по этому и приходится это передавать с аппки

2023-10-27 13:34 UTC, m3g0byt3 commented
> `Blockchain+AllCases` это костыль просто для того что бы был весь, параметры testnet и curve не используются из него, просто не принималось как сделать весь список )

Теперь понятно)
Безопаснее наверное было бы отдавать в `allMainnetCases` просто raw network ids строками, чтобы нельзя было заюзать некорректные на v1 кривые
Но не принципиально)

2023-10-27 15:14 UTC, tureck1y approved these changes, later dismissed

2023-10-27 15:24 UTC, tureck1y commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/397'/0'"
При расхождениях, мы выбирали за эталон Трастволлет. А вообще с двумя нулями для ed какой-то странный путь получается. Либо уж по Bip44 - полный путь, либо только с одним нулем как тут.

2023-10-27 16:01 UTC, ba1ashov commented
> Безопаснее наверное было бы отдавать в allMainnetCases просто raw network ids строками, чтобы нельзя было заюзать некорректные для v1 кривые

вообще согласен, там еще в тестах используется, может поправим потом

2023-10-27 16:01 UTC, Balashov152 approved these changes, later dismissed

2023-10-30 12:51 UTC, m3g0byt3 commented
Слетели оки, потому что я подумал, что надо пилить ветку от релиза для 5.0 и начал черрипикать в новую ветку
Вернул все как было

2023-10-30 14:37 UTC, tureck1y approved these changes

2023-10-30 15:10 UTC, Balashov152 approved these changes

2023-11-02 11:10 UTC, merged