Ios 5167 add decimal blockchain
tangem/blockchain-sdk-swift pull request #465
Opened 2023-11-17 15:19 UTC by skibinalexander

Добавление блокчейна Decimal (EVM)

2023-11-17 15:27 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func sign(_ transaction: Transaction, signer: TransactionSigner) -> AnyPublisher<String, Error> {
@Balashov152 посмотри пожалуйста, так корректно ли делать, или есть более технологичный вариант?

2023-11-22 07:51 UTC, skibinalexander commented
Проверил отправку работает все нормально

2023-11-22 11:02 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +        )
`Transaction` конформит `ThenProcessable`, поэтому ее можно мутировать inplace
И правки в `BlockchainSdk/Common/Transaction.swift` становятся не нужны

2023-11-22 11:02 UTC, m3g0byt3 commented on BlockchainSdkTests/Common/AddressTests.swift
> +
Еще нужны тесты конвертации адресов в обоих направлениях (и с валидным/невалидным инпутом)

2023-11-22 13:42 UTC, tureck1y requested changes

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/ExternalLinkProvider/DecimalExternalLinkProvider.swift
> +        let copyAddress = (try? DecimalUtils().convertErcAddressToDscAddress(addressHex: address)) ?? address
Еще может не copyAddress, а dscAddress?

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +        let checksumAddress = toChecksumAddress(address)!
может лучше вообще без него?)

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +        let checksumAddress = toChecksumAddress(address)!
Я бы предложил для генерации эфировского адреса использовать соотв сервис, зачем копипаста

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +        }
а если будет 0X, а не 0x?

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +struct DecimalUtils {
Могу предложить DecimalBlockchainAddressConverter. Вообще хочется неймингом порешать конфликт с Decimal-типом

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +}
Только добавлю, что я рефакторингом убрал везде эти 0x, надо использовать String extensions для работы с префиксами

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    private func convertAddress(destinationAddress: String) -> String {
Как-будто тут тоже надо IfNeeded

2023-11-22 13:42 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func sign(_ transaction: Transaction, signer: TransactionSigner) -> AnyPublisher<String, Error> {
Это же не тут надо делать, а в билдере. И для buildForSign и для buildForSend. Тут совсем неверно, как минимум: есть еще метод send. Ты транзакцию с такой подменой тестировал?

2023-11-22 14:30 UTC, Balashov152 reviewed
Мельком глянул )

2023-11-22 14:30 UTC, Balashov152 commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .ethereumFair, .saltPay, .octa, .decimal:
@tureck1y  а мы для V1 ETH сети тоже все на 60 держим? Или там продолжаем делать разные для разных

2023-11-22 14:40 UTC, tureck1y commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .ethereumFair, .saltPay, .octa, .decimal:
точно, проглядел, для в1 разные

2023-11-23 07:41 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +        let checksumAddress = toChecksumAddress(address)!
> Я бы предложил для генерации эфировского адреса использовать соотв сервис, зачем копипаста

Посчитал, что тут специфично генерируются адреса, и чтобы не произошло коллизии с тем что, мы поменяем логику эфировскую и сломаем этот блокчейн

2023-11-23 07:42 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +        let checksumAddress = toChecksumAddress(address)!
> Я бы предложил для генерации эфировского адреса использовать соотв сервис, зачем копипаста

Посмотрю как можно избежать копи пасты

2023-11-23 07:43 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func sign(_ transaction: Transaction, signer: TransactionSigner) -> AnyPublisher<String, Error> {
> Это же не тут надо делать, а в билдере. И для buildForSign и для buildForSend. Тут совсем неверно, как минимум: есть еще метод send. Ты транзакцию с такой подменой тестировал?

Да тестировал по этой реализации, посмотрю через билдер

2023-11-23 07:50 UTC, skibinalexander commented on BlockchainSdk/ExternalLinkProvider/DecimalExternalLinkProvider.swift
> +        let copyAddress = (try? DecimalUtils().convertErcAddressToDscAddress(addressHex: address)) ?? address
> 1. ~Тут не надо валидировать, что на вход в этот метод пришел именно ERC адрес (и его надо конвертить). А если пришел DSC адрес - то конвертация не нужна? Или это под капотом делает конвертер?~ Увидел эту логику в коде DecimalUtils, но нейминг методов ничего об этом не говорит (отписал насчет этого ниже)
> 2. Фоллбек на исходный адрес ` ?? address` вообще сработает, откроется по нему инфа? Или это чтобы компилятор успокоить?
> 3. Контрактов в DECIMAL нет, их не надо тут поддерживать?

Контракты посмотрю , а вот эксплорер должен по идее кушать адрес evm, сейчас ошибку кидает , но сам эксплорер показывает оба адреса

2023-11-23 07:52 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +}
> Только добавлю, что я рефакторингом убрал везде эти 0x, надо использовать String extensions для работы с префиксами

Ага, хорошо чтобы не хардкодить

2023-11-23 07:54 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +            }
> А байт из хеша нельзя сразу тут as is заюзать? Без вот этого `Int(String(hashChars[i]), radix: 16)`
> 
> И кажется эту логику в целом можно сделать через zip

Код с эфировского адрес сервиса

2023-11-23 07:55 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +            }
> А байт из хеша нельзя сразу тут as is заюзать? Без вот этого `Int(String(hashChars[i]), radix: 16)`
> 
> И кажется эту логику в целом можно сделать через zip

На мой взгляд не должно быть расхождений

2023-11-23 08:21 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalAddressService.swift
> +        let checksumAddress = toChecksumAddress(address)!
> > Я бы предложил для генерации эфировского адреса использовать соотв сервис, зачем копипаста
> 
> Посмотрю как можно избежать копи пасты, в целом evm же, изменится эфир изменится и этот

2023-11-23 08:22 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +}
> Кажется можно вынести эти константы в API `DecimalUtils`, типа такого:
> 
> ```
> static func getAddressPrefix: String { "d0" }
> static func getLegacyAddressPrefix: String { "dx" }
> static func getERC55AddressPrefix: String { "0x" }
> ```
> 
> и таким образом избежать копипасты в `DecimalAddressService.swift`

Да , копипаста ошибся

2023-11-27 09:16 UTC, skibinalexander commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .ethereumFair, .saltPay, .octa, .decimal:
> точно, проглядел, для в1 разные

Не нашел coinId в coin листе :(

2023-11-27 18:03 UTC, tureck1y reviewed
Нельзя рефакторинг, особенно такого масштаба делать в рамках задачи. Надо выносить отдельно

2023-11-27 18:03 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalTransactionBuilder.swift
> +        return addressConverter.convertDscAddressToErcAddress(addressHex: destinationAddress) ?? destinationAddress
Мне кажется некорректно делать такой fallback. Если адрес не содержит hex prefix и не сконвертировался, то это какая-то ерунда и не надо туда транзакцию отправлять. лучше кинуть ошибку тут и там где фи

2023-11-27 18:03 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func getFee(to: String, from: String, value: String?, data: Data?) -> AnyPublisher<[Fee], Error> {
Нужно ли переопределять еще и getGasLimit? Это используется в WC.

2023-11-27 18:03 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func getInfo(address: String, tokens: [Token], _ completion: @escaping (Result<Void, Error>) -> Void) {
по идее, сюда же попадает только default адрес всегда. Не надо конвертировать?

2023-11-28 07:26 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalWalletManager.swift
> +    override func getFee(to: String, from: String, value: String?, data: Data?) -> AnyPublisher<[Fee], Error> {
> Нужно ли переопределять еще и getGasLimit? Это используется в WC.

Да проверю, я посмотрел видимо только в общем что все методы проходят уже с обновленным адресом, проверю на WC

2023-11-28 10:38 UTC, skibinalexander commented
@tureck1y комменты пока не поправил, ревью случайно запросил заново

2023-11-28 11:13 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalTransactionBuilder.swift
> +        return addressConverter.convertDscAddressToErcAddress(addressHex: destinationAddress) ?? destinationAddress
> Мне кажется некорректно делать такой fallback. Если адрес не содержит hex prefix и не сконвертировался, то это какая-то ерунда и не надо туда транзакцию отправлять. лучше кинуть ошибку тут и там где фи

Да как ты говоришь будет лучше сделаю через исключение

2023-11-28 18:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +        }
надо просто lowercased() дописать и все

2023-11-29 17:35 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +
> Еще нужны тесты конвертации адресов в обоих направлениях (и с валидным/невалидным инпутом)

Добавил

2023-11-29 17:42 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Decimal/DecimalUtils.swift
> +        }
> надо заюзать наши экстеншены для проверки на 0x

<img width="795" alt="Снимок экрана 2023-11-29 в 20 41 56" src="https://github.com/tangem/blockchain-sdk-swift/assets/5384724/42dca989-17fa-47eb-a836-4e7846632c96">

Вроде нормуль

2023-11-30 10:20 UTC, tureck1y submitted a review, later dismissed

2023-11-30 11:58 UTC, m3g0byt3 submitted a review, later dismissed

2023-11-30 12:12 UTC, m3g0byt3 approved these changes

2023-11-30 12:28 UTC, tureck1y approved these changes

2023-11-30 12:30 UTC, merged