Ios 5588 make algorand network layer
tangem/blockchain-sdk-swift pull request #516
Opened 2024-01-17 09:15 UTC by skibinalexander

Сетевой слой + взаимодействие с сетевым слоем для Algorand

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/BlockchainService/Algorand/Provider/AlgorandProviderTarget.swift
> +        }
А это получается рекомендованный самими nownodes способ передать ключ для всех сеток, не только для алго?
Не видел такого просто в остальных сетях

Для других сеток я вижу ключ просто в самом урле (xlm, near) (что менее безопасно офк)

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Common/WalletAssembly/AlgorandWalletAssembly.swift
> +//            AlgorandNetworkProvider(
что-то закоменченное пролезло)

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +import Combine
тоже что-то не то

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        let blanaceValues = calculateCoinValueWithReserveDeposit(from: accountModel)
nit: typo

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        guard accountModel.amount >= accountModel.minBalance else {
Кажется с точки зрения логики странно, что мы тут сравниваем не те значения баланса, которые мы добавили в воллет на строчках выше (т.е. значения которые будут в UI видны и учитываться логикой), а значения баланса в самой сетевой модели

правильнее сравнивать `wallet.amounts[.coin] >= accountModel.minBalance` или что-то такое, так как во всей логике в аппе будет использоваться именно то что мы положили в воллет (`wallet.amounts[.coin]`)

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        let changeBalanceValue = accountModel.amount > accountModel.minBalance ? accountModel.amount - accountModel.minBalance : 0
`max(accountModel.amount - accountModel.minBalance, 0)` достаточно

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +                let targetFee = sourceFee > minFee ? sourceFee : minFee
тоже кажется можно обойтись max

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +                    lastRound: transactionInfoParams.lastRound + 1000,
А это значение откуда, из официального воллета?

И еще напрашивается или коммент сразу тут или вынос в константы и коммент там, сложно спустя пару месяцев искать логику почему выбран тот или иной мэджикнамбер

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +                    nonce: (transaction.params as? AlgorandTransactionParams)?.nonce
nit: если без nonce транза не уйдет, то удобнее анврапить nonce где-то и кидать ошибку если что не так
чтобы дебажить проще было

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +            .tryMap { walletManager, buildParams -> (hash: Data, params: AlgorandBuildParams) in
на этой строчке явный возвращаемый тип можно грохнуть будет как только GH раннер перейдет на xcode 14.3 (ща 14.2 и на нем как раз эту строчку тайпчек не хавает)

2024-01-18 12:28 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +    private func makeNoAccountError(using accountModel: AlgorandResponse.Account) -> WalletError {
Мб вынести это как factory метод для WalletError?
Раз как минимум в двух местах уже юзается, NEAR и тут

2024-01-18 13:23 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +                    nonce: (transaction.params as? AlgorandTransactionParams)?.nonce
> nit: если без nonce транза не уйдет, то удобнее анврапить nonce где-то и кидать ошибку если что не так чтобы дебажить проще было

Без nonce транзакции нормально уходит

2024-01-18 13:25 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +    private func makeNoAccountError(using accountModel: AlgorandResponse.Account) -> WalletError {
> Мб вынести это как factory метод для WalletError? Раз как минимум в двух местах уже юзается, NEAR и тут

Не хотел бы рефакторинг тащить, у нас много где методы переиспользуются, лучше может как-то отдельно такое смотреть

2024-01-18 18:28 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Algorand/AlgorandNetworkService.swift
> +    func getAccount(address: String) -> AnyPublisher<AlgorandResponse.Account, Error> {
> Вообще с архитектурной точки зрения DTO (AlgorandResponse*) не должен возвращаться сетевым сервисом и должен быть ограничен сетевым провайдером. 
> 
> Сетевой сервис принимает и возвращает уже доменные модели
> 
> 
> 
> Потому что DTO содержит разные детали имплементации сетевой части, например:
> 
> - структуру полей как задано в апишке, а не как удобно/принято в домене
> 
> - типы как задано в апишке, а не как удобно/принято в домене
> 
> - конформанс codable
> 
> - и т.д. 
> 
> 
> 
> которые все лишние и не нужны в домене
> 
> 
> 
> ---
> 
> 
> 
> Ну и на странность в архитектурном плане указывает пустота самого сетевого сервиса, сейчас он просто по сути прокся чтобы дернуть сетевой провайдер и ничего особо не делает
> 
> 

Обсудили , сделал так , как решили

2024-01-19 08:35 UTC, m3g0byt3 approved these changes

2024-01-19 08:35 UTC, m3g0byt3 commented on BlockchainSdk/BlockchainService/Algorand/AlgorandNetworkService.swift
> +                        throw WalletError.failedToBuildTx
nit: по смыслу тут все-таки другая ошибка должна кидаться, failedToParse
тк тут именно парсинг и валидация ответа из сети

2024-01-19 08:35 UTC, m3g0byt3 commented on BlockchainSdk/BlockchainService/Algorand/AlgorandNetworkService.swift
> +
тут лишние пробелы/переносы)
можно наверное просто сделать
```
return AlgorandEstimatedFeeParams(
    minFee: Amount(with: service.blockchain, value: minFee),
    fee: Amount(with: service.blockchain, value: sourceFee)
)
```

2024-01-22 13:53 UTC, tureck1y requested changes

2024-01-22 13:53 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        }
Тут еще должна быть проверка и удаление пендинг транзакций

2024-01-22 13:53 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Algorand/DTO/AlgorandResponse.swift
> +enum AlgorandResponse {}
потом дополнится?

2024-01-22 13:53 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Algorand/Provider/AlgorandProviderUrl.swift
> +struct AlgorandProviderNode: HostProvider {
У нас такое есть уже у нескольких сеток есть, надо подумать можно ли как-то унифицировать подход. МОжно в ноушен вынести пока

2024-01-22 16:04 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Algorand/DTO/AlgorandResponse.swift
> +enum AlgorandResponse {}
Тут namespace , сами модельки лежат под namespace

2024-01-22 16:05 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Algorand/Provider/AlgorandProviderUrl.swift
> +struct AlgorandProviderNode: HostProvider {
Планировал в рамках другого МР , дополню в этом , нет проблем

2024-01-22 19:30 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        }
Планировал в рамках другого МР , дополню в этом , нет проблем

2024-01-22 19:31 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Algorand/Provider/AlgorandProviderUrl.swift
> +struct AlgorandProviderNode: HostProvider {
Закину в виде таски , помечу что нужно обсудить

2024-01-23 15:32 UTC, skibinalexander commented
Все-таки еще потестирую сброс pending, есть кое-какие сомнения ...

2024-01-23 15:32 UTC, skibinalexander commented
> Все-таки еще потестирую сброс pending, есть кое-какие сомнения ...

Отпишу как готово будет

2024-01-24 11:28 UTC, skibinalexander commented
@tureck1y можно смотреть

2024-01-25 06:57 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Algorand/Provider/AlgorandProviderUrl.swift
> +struct AlgorandProviderNode: HostProvider {
https://tangem.atlassian.net/browse/IOS-5779

2024-01-25 14:04 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Algorand/AlgorandWalletManager.swift
> +        }
Ну надо было тогда Туду оставить, мне же непонятно)

2024-01-25 14:22 UTC, tureck1y approved these changes

2024-01-25 19:33 UTC, merged