Aptos/ios 5745 make aptos network layer
tangem/blockchain-sdk-swift pull request #543
Opened 2024-02-06 08:34 UTC by skibinalexander

Реализация сетевого слоя + работы walletManager для Aptos

Смотреть после #542

2024-02-07 11:59 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +    let blockchain: Blockchain
Давай лучше без любого)
Все равно передача другого blockchain не поможет)
```suggestion
    let blockchain: Blockchain = .autos
```

2024-02-07 12:10 UTC, Balashov152 reviewed
Чуть глянул, потом понял что рано ))

2024-02-07 12:10 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/DTO/AptosResponse+Coin.swift
> +extension AptosResponse {
Я бы все в один файл заснул

2024-02-07 12:10 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +import SwiftyJSON
А без `SwiftyJSON` не получается? Что бы потом выпиливать проще было, если будем

2024-02-07 12:10 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +                    return WalletError.noAccount(message: "no_account_bnb".localized)
Текст точно тот?

2024-02-07 12:10 UTC, Balashov152 commented on BlockchainSdk/Common/WalletAssembly/AptosWalletAssembly.swift
> +            contentsOf: [
```suggestion
        var providers: [AptosNetworkProvider] = [
```

2024-02-07 12:10 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Aptos/AptosTransactionBuilder.swift
> +        guard signingOutput.error.rawValue == 0, signingOutput.hasAuthenticator else {
```suggestion
        guard signingOutput.error == .ok, signingOutput.hasAuthenticator else {
```

2024-02-07 12:44 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +import SwiftyJSON
> А без `SwiftyJSON` не получается? Что бы потом выпиливать проще было, если будем

Есть это в планах? Окей, посмотрю, но там конечно вероятно все в опционалы вырастит, попробую обойтись

2024-02-07 15:40 UTC, tureck1y requested changes

2024-02-07 15:40 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +    let blockchain: Blockchain
у нас что-то это постоянно всплывает, с какого файла копипаста? Может надо там исправить

2024-02-07 15:40 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                }
везде это убери плиз, если есть в алгоранде, тоже надо убрать

2024-02-07 15:40 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Aptos/DTO/AptosResponse+FeeParams.swift
> +            case deprioritizedGasEstimate = "deprioritized_gas_estimate"
это же можно порешать политикой декада ключей

2024-02-07 15:40 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +    func calculateUsedGasPriceUnit(transactionBody: AptosRequest.TransactionBody) -> AnyPublisher<JSON, Error> {
не-не, надо норм структурами

2024-02-07 17:18 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +    let blockchain: Blockchain
Да тащу ошибку , буду обращать внимание 👌

2024-02-07 17:21 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +    func calculateUsedGasPriceUnit(transactionBody: AptosRequest.TransactionBody) -> AnyPublisher<JSON, Error> {
Да уж понял , просто не помню что запрещали , в поиске вбил были импорты , а как серега написал , проверил , там только и импорты , переделаю нет проблем , только там было что то вроде почему JSON swifty , но уберу да 👌

2024-02-07 17:22 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/DTO/AptosResponse+FeeParams.swift
> +            case deprioritizedGasEstimate = "deprioritized_gas_estimate"
Ага , ок передалаю

2024-02-07 17:29 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +    func calculateUsedGasPriceUnit(transactionBody: AptosRequest.TransactionBody) -> AnyPublisher<JSON, Error> {
Не запрещали, но без него действительно чище, я бы кикнул из проекта

2024-02-08 20:56 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +                    return WalletError.noAccount(message: "no_account_bnb".localized)
> Текст точно тот?

<img width="1181" alt="Снимок экрана 2024-02-08 в 23 56 04" src="https://github.com/tangem/blockchain-sdk-swift/assets/5384724/5169793b-f8a7-4008-ab50-cd50d6113112">

2024-02-08 20:56 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                }
> везде это убери плиз, если есть в алгоранде, тоже надо убрать

Поставил TODO: - страшно резать в остальных сетях

2024-02-08 20:58 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                }
> > везде это убери плиз, если есть в алгоранде, тоже надо убрать
> 
> Поставил TODO: - страшно резать в остальных сетях

И в VeChain Near вроде обсудили что надо убрать, я лучше тачку заведу

2024-02-08 20:58 UTC, skibinalexander commented
Пока попрошу @Balashov152 по своим комментам пробежаться

2024-02-09 09:19 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                }
> везде это убери плиз, если есть в алгоранде, тоже надо убрать

https://tangem.atlassian.net/browse/IOS-5899

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +import SwiftyJSON
`import SwiftyJSON` тоже можно удалить

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                    }
NP: Выглядит что можно все в один `guard` закинуть )

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                }
`withWeakCaptureOf` лишнее

```suggestion
                .map { response in
                    return response.gasEstimate
                }
```

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                .tryMap { service, response in
`withWeakCaptureOf` лишнее как будто
```suggestion
                .tryMap { response in
```

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                .tryMap { service, response in
```suggestion
                .tryMap { response in
```

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                .tryMap { service, response in
```suggestion
                .tryMap { response in
```

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +        }
Тут осталось `SwiftyJSON.JSONKey`

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +                    return WalletError.noAccount(message: "no_account_bnb".localized)
`bnb` конечно не очень, раз у нас уже в двух местах

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/Common/Blockchain.swift
> +//                assertionFailure("getJsonRpcEndpoint s -> Not found GetBlock jsonRpc key for blockchain \(displayName)")
?

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/Extensions/String+.swift
> +    func camelCaseToSnakeCase() -> String {
Лишнее

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +                receiveCompletion: { [unowned self] completionSubscription in
`weak` что бы не падало )
```suggestion
                receiveCompletion: { [weak self] completionSubscription in
```

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +        }
А если есть входящая, можно это понять? И добавить
`wallet.addPendingTransaction()`

2024-02-09 09:51 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +    private func createExpirationTimestampSecs() -> UInt64 {
Может это лучше в TransactionBuilder перенести, что бы не было лишнего параметра в методах `buildForSend` и тд

2024-02-09 09:57 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +    private func createExpirationTimestampSecs() -> UInt64 {
> Может это лучше в TransactionBuilder перенести, что бы не было лишнего параметра в методах `buildForSend` и тд

Там написан коммент, что нужно прикапывать значение

2024-02-09 09:57 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +                receiveCompletion: { [unowned self] completionSubscription in
> `weak` что бы не падало )

Ага , уберу ....

2024-02-09 09:59 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                    }
> NP: Выглядит что можно все в один `guard` закинуть )

Не хотел второй guard делать, добавлю

2024-02-09 10:05 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +        }
> А если есть входящая, можно это понять? И добавить `wallet.addPendingTransaction()`

sequenceNumber насколько я понимаю, переваривает транзакции, в случае если он обновился, значит все твои транзакции переварились блокчейном. 

как я это понимаю ...

2024-02-09 10:07 UTC, skibinalexander commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +    private func createExpirationTimestampSecs() -> UInt64 {
> > Может это лучше в TransactionBuilder перенести, что бы не было лишнего параметра в методах `buildForSend` и тд
> 
> Там написан коммент, что нужно прикапывать значение на уровне менеджера чтобы засинхронить значения между buildForSign и buildForSend в рамках одной цепочки

2024-02-09 10:08 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                .tryMap { service, response in
> `withWeakCaptureOf` лишнее как будто

Нужно для service.blockchainDecimalValue

2024-02-09 10:09 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/AptosNetworkService.swift
> +                .tryMap { service, response in
В остальных местах поубирал, спс

2024-02-09 10:10 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +                    return WalletError.noAccount(message: "no_account_bnb".localized)
> `bnb` конечно не очень, раз у нас уже в двух местах

Не хочу тащить рефакторинг, ща тасочку заведу короткую

2024-02-09 10:11 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Aptos/Provider/AptosNetworkProvider.swift
> +                    return WalletError.noAccount(message: "no_account_bnb".localized)
https://tangem.atlassian.net/browse/IOS-5900

2024-02-09 10:22 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/Aptos/AptosWalletManager.swift
> +    private func createExpirationTimestampSecs() -> UInt64 {
Ok)

2024-02-09 10:22 UTC, Balashov152 approved these changes

2024-02-09 18:18 UTC, tureck1y approved these changes

2024-02-09 18:48 UTC, merged