IOS-5781 Fix chia obtain fee estimated value
tangem/blockchain-sdk-swift pull request #548
Opened 2024-02-07 13:31 UTC by skibinalexander

Внес 2 правки которые нужны были по итогу обсуждения.

- Не верно транслировалась ошибка, поменял на стандартные
- По итогу обсуждения с @dbaturin решили добавить множитель, предлагаю 2, но еще жду апрув от Дениса

До утверждения множителя пока WIP

2024-02-07 15:35 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                .mapError { error in
Не совсем понял что тут происходит.  Мы тогда не поймем в чем дело. Нам нужно добиться того, чтобы неуспешная отправка выдавала ошибку. Скорее всего проблема где-то здесь
guard response.status == ChiaSendTransactionResponse.Constants.successStatus

приходит success, а по факту фейл. Может можно проверять как-то точнее, проанализируйте логи из обращений по этой проблеме, надо понять какой респонс приходит в таких случаях

2024-02-07 15:35 UTC, tureck1y commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                .mapError { error in
не понимаю здесь тоже, зачем стирать тип ошибки?

2024-02-07 17:25 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                .mapError { error in
👌посмотрю но вероятно придется обсудить

2024-02-08 21:02 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                    let lowEstimatedFee = Double(cost) * response.feeRateLastBlock * MultiplicatorConstants.lowMultiplicatorFeeRate
> Почему double, а не decimal?

Да спасибо, вероятно лучше с response загнать в Decimal

2024-02-09 14:10 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                    guard
@tureck1y добавил проверку второго поля success, в целом сверился с Андроидом, делается вот такая проверка response.status == ChiaSendTransactionResponse.Constants.successStatus

2024-02-09 14:31 UTC, skibinalexander commented
![IMG_0947](https://github.com/tangem/blockchain-sdk-swift/assets/5384724/a4046245-8f52-4d2f-92d1-e6f5c11adb8a)
![IMG_0948](https://github.com/tangem/blockchain-sdk-swift/assets/5384724/98398b5c-f4cd-47b7-8cca-fc973693abb3)

2024-02-09 15:04 UTC, dbaturin requested changes

2024-02-09 15:27 UTC, skibinalexander commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +                    let highEstimatedFee = Decimal(cost) * Decimal(response.feeRateLastBlock) * MultiplicatorConstants.highMultiplicatorFeeRate
Ага , спс так яснее

2024-02-09 18:20 UTC, tureck1y submitted a review, later dismissed

2024-02-12 18:07 UTC, dbaturin approved these changes

2024-02-12 18:15 UTC, tureck1y approved these changes

2024-02-13 09:18 UTC, m3g0byt3 approved these changes

2024-02-13 09:18 UTC, m3g0byt3 commented on BlockchainSdk/BlockchainService/Chia/ChiaNetworkService.swift
> +    enum MultiplicatorConstants {
nit: тут кажется идеально подошел бы CaseIterable, но не крит

2024-02-13 09:50 UTC, merged