Ios 5795 bch nownodes api
tangem/blockchain-sdk-swift pull request #552
Opened 2024-02-09 14:19 UTC by fedorov-d

Сделал адаптер для BlockBookUtxoProvider. Также подрефакторил сам BlockBookUtxoProvider, вынес часть логики по созданию запросов в общий метод. Сейчас BlockBookUtxoProvider отправляет как BlockBook так и Node запросы, для вторых сделал отдельную модель.

2024-02-11 14:59 UTC, tureck1y requested changes
Все же напрашивается рефакторинг наунодс, гетблока и блокбука. Сейчас уже сложно разобраться что происходит. 

Странно, что таргет блокбука умеет делать какие-то еще запросы. Нужен отдельный таргет и разрулить это в провайдере. 

Не в рамках этой задачи, сделаем отдельно.

2024-02-11 14:59 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        }.eraseToAnyPublisher()
а зачем отделять result тут и ниже? Одной цепочкой лучше читается

2024-02-11 14:59 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +    func convertFee(_ fee: Decimal) throws -> Decimal {
сделай пожалуйста приватным все, что не должно торчать наружу

2024-02-11 14:59 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +    func convertFee(_ fee: Decimal) throws -> Decimal {
fee rate было более правильно, потому что это еще не fee, а только значение за байт

2024-02-11 14:59 UTC, tureck1y commented on BlockchainSdk/Common/NetworkProviderAssembly.swift
> +    func makeBitCoinCashNowNodesNetworkProvider(
BitcoinCash

2024-02-11 14:59 UTC, tureck1y commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashNowNodesNetworkProvider.swift
> +        let address = address.hasPrefix(prefix) ? address : prefix + address
тут что-то не то, адрес может быть с префиксом, а может и без, если это легаси адрес.

2024-02-13 11:02 UTC, fedorov-d commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashNowNodesNetworkProvider.swift
> +        let address = address.hasPrefix(prefix) ? address : prefix + address
тут грабли, BitcoinCashNetworkService отрезает префикс (видимо для нормальной работы Blockchair провайдера), а nownodes требует его наличие для не-легаси адресов, иначе 400 шлет.

2024-02-13 11:05 UTC, fedorov-d commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +    func convertFee(_ fee: Decimal) throws -> Decimal {
переименовал в convertFeeRate, приватным его сделать не получится, т.к. используется в BitcoinCashNowNodesNetworkProvider, возможно имеет смысл его куда-то отдельно вынести.

2024-02-13 12:00 UTC, fedorov-d commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +    func convertFee(_ fee: Decimal) throws -> Decimal {
добавил проверку на легаси адрес перед добавлением префикса

2024-02-14 17:54 UTC, tureck1y commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        }.eraseToAnyPublisher()
так явно тип вывести и все будет ок

2024-02-14 17:57 UTC, tureck1y commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashAddressService.swift
> +        !cashAddrService.validate(address) && legacyService.validate(address)
а точно нужна эта проверка !cashAddrService.validate(addr) ?

2024-02-14 17:57 UTC, tureck1y commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashNowNodesNetworkProvider.swift
> +    private let addressService: AddressService
Это же BitcoinCashNowNodesNetworkProvider, пусть тут лежит BitcoinCashAddressService

2024-02-15 07:53 UTC, fedorov-d commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashAddressService.swift
> +        !cashAddrService.validate(address) && legacyService.validate(address)
нет, убрал

2024-02-15 07:53 UTC, fedorov-d commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashNowNodesNetworkProvider.swift
> +    private let addressService: AddressService
поправил

2024-02-15 07:53 UTC, fedorov-d commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        }.eraseToAnyPublisher()
поправил

2024-02-17 15:03 UTC, tureck1y approved these changes, later dismissed

2024-02-20 10:58 UTC, Balashov152 commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        .tryMap { [weak self] response in
а вот так соберется? Хочется только один `executeRequest` иметь

```suggestion
        executeRequest(
            .fees(NodeRequest.estimateFeeRequest(confirmationBlocks: confirmationBlocks))
        )
        .tryMap { [weak self] (response: BlockBookFeeResponse) in
```

2024-02-20 10:58 UTC, Balashov152 commented on BlockchainSdk/Common/WalletAssembly/BitcoinCashWalletAssembly.swift
> +                blockchain: .bitcoinCash
Лучше из input
```suggestion
                blockchain: input.blockchain
```

2024-02-20 10:58 UTC, Balashov152 commented on BlockchainSdk/Common/WalletAssembly/BitcoinCashWalletAssembly.swift
> +                blockchain: .bitcoinCash
И я бы без переноса сделал )

2024-02-20 10:58 UTC, Balashov152 commented on BlockchainSdk/WalletManagers/BitcoinCash/BitcoinCashAddressService.swift
> +@available(iOS 13.0, *)
Можно без этого

2024-02-20 11:13 UTC, fedorov-d commented on BlockchainSdk/BlockchainService/BlockBook/BlockBookUtxoProvider.swift
> +        .tryMap { [weak self] response in
компилятор не резолвит без явного типа, выше где-то скрин кидал

2024-02-20 11:20 UTC, fedorov-d commented on BlockchainSdk/Common/WalletAssembly/BitcoinCashWalletAssembly.swift
> +                blockchain: .bitcoinCash
input поправил, переносы все же оставлю, напрягают длинные строки

2024-02-21 16:17 UTC, tureck1y approved these changes

2024-02-21 16:26 UTC, ba1ashov approved these changes

2024-02-22 05:20 UTC, merged