iOS-4557: Hedera blockchain transaction builder
tangem/blockchain-sdk-swift pull request #553
Opened 2024-02-09 22:37 UTC by m3g0byt3

[IOS-4557](https://tangem.atlassian.net/browse/IOS-4557)

2024-02-12 19:34 UTC, tureck1y requested changes

2024-02-12 19:34 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +        self.wallet = wallet
Эта копия воллета же потеряет актуальность со временем, не надо его сюда передавать

2024-02-12 19:34 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +                .map { try $0.normalize() }
TangemSdk отдает уже нормализованные подписи по-умолчанию

2024-02-12 19:34 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +                return hashes.map { $0.sha3(.keccak256) }
А как это работает? От хеша еще один хэш считается?

2024-02-15 10:22 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +        self.wallet = wallet
Переделал, теперь передается `isTestnet`, `curve`, `blockchainKey`

2024-02-15 10:23 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +                .map { try $0.normalize() }
Выпилил, проверил - транзы если юзать хидеру с secpk1 ходят норм

2024-02-15 10:24 UTC, m3g0byt3 commented on BlockchainSdk/WalletManagers/Hedera/HederaTransactionBuilder.swift
> +                return hashes.map { $0.sha3(.keccak256) }
У нас тут не хеш, а сами транзакции
Для ED мы подписываем их, для EC надо сделать хеш

Нейминг некорректный и сбивает, да
Поправил его

2024-02-15 10:41 UTC, Andoran90 approved these changes

2024-02-16 16:33 UTC, tureck1y approved these changes

2024-02-19 08:44 UTC, merged