IOS-5962 Add new evms
tangem/blockchain-sdk-swift pull request #577
Opened 2024-02-22 12:27 UTC by fedorov-d

2024-02-27 07:22 UTC, Andoran90 commented on BlockchainSdk/Common/Blockchain.swift
> +            return "PLAYA3ULL GAMES"
думаю тут тоже надо добавить тестнетовский суффикс

2024-02-27 07:22 UTC, Andoran90 commented on BlockchainSdk/Common/Blockchain.swift
> +        case .playa3ullGames: return 3011
а какой `chainId` в тестнете?
Вообще судя по коду МРа у этой сети будто нет тестнета, а значит не должно быть ассоциированной булки. Есть тестнет у сети или нет?
Если да, надо везде добавить инфу по тестнету, если нет, то обновить кейс

2024-02-27 07:22 UTC, Andoran90 commented on BlockchainSdk/Common/Blockchain.swift
> +                    URL(string: "https://testnet.aurora.dev/")!,
наверное не особо критично что для тестнета одна апишка, но хотелось бы хотя бы парочку. Нет больше?

2024-02-27 07:22 UTC, Andoran90 commented on BlockchainSdk/ExternalLinkProvider/AuroraExternalLinkProvider.swift
> +    var testnetFaucetURL: URL? = nil
а ни у одного нет краника для получения тестовых монет?((

2024-02-27 07:22 UTC, Andoran90 commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .disChain, .octa,
@tureck1y  напомни, пожалуйста, мы теперь для старых воллетов (АС01, АС02) тоже всегда теперь берем такую же деривацию как и для эфира?

2024-02-27 10:06 UTC, fedorov-d commented on BlockchainSdk/Common/Blockchain.swift
> +        case .playa3ullGames: return 3011
убрал тестнет, в андроиде его нету

2024-02-27 10:15 UTC, fedorov-d commented on BlockchainSdk/Common/Blockchain.swift
> +            return "PLAYA3ULL GAMES"
убрал тестнет

2024-02-27 12:59 UTC, tureck1y requested changes
Еще есть момент по фи, обсудим

2024-02-27 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +            return "Pulsechain" + testnetSuffix + (isTestnet ? " v4" : "")
мне кажется надо на 2 строчки поделить, в первой сформировать  кастовый теснит суффикс, во второй - уже название

2024-02-27 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +                URL(string: "https://api.mainnet.playa3ull.games/")!,
Берем из доки и отсюда https://chainlist.org/?search=pulsechain

2024-02-27 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +                    URL(string: "https://testnet.aurora.dev/")!,
на тестнете одна - ок

2024-02-27 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .disChain, .octa,
нет, только для тех сетей, где не смогли найти информацию здесь https://github.com/satoshilabs/slips/blob/master/slip-0044.md

2024-02-27 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .disChain, .octa,
@fedorov-d проверь плиз, что их там нет

2024-02-27 13:27 UTC, fedorov-d commented on BlockchainSdk/Common/Blockchain.swift
> +                URL(string: "https://api.mainnet.playa3ull.games/")!,
ни в доке ни в чейнлисте больше нет

2024-02-27 13:33 UTC, fedorov-d commented on BlockchainSdk/ExternalLinkProvider/AuroraExternalLinkProvider.swift
> +    var testnetFaucetURL: URL? = nil
нашел, добавил

2024-02-27 13:34 UTC, fedorov-d commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +        case .ethereum, .ethereumPoW, .disChain, .octa,
в списке нет, андроид тоже дефолтную поставил

2024-02-28 10:36 UTC, Andoran90 approved these changes, later dismissed

2024-02-28 10:54 UTC, tureck1y submitted a review, later dismissed

2024-02-28 11:06 UTC, tureck1y approved these changes

2024-02-28 11:06 UTC, merged