IOS-6354 Added ability to ignore totalExceedsBalance when checking fee
tangem/blockchain-sdk-swift pull request #610
Opened 2024-03-21 09:30 UTC by megakoko

В приложении изменения будут такими. Общую сумму в итоге все равно проверим

<img width="1167" alt="Screenshot 2024-03-21 at 17 28 55" src="https://github.com/tangem/blockchain-sdk-swift/assets/12209839/e36198a9-e91e-4bab-bc43-de8142c7fc16">

2024-03-22 12:10 UTC, Andoran90 requested changes

2024-03-22 12:10 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +public struct TransactrionValidatorOptions {
```suggestion
public struct TransactionValidatorOptions {
```

2024-03-22 12:10 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +    func validateAmounts(amount: Amount, fee: Amount, options: TransactrionValidatorOptions = .init()) throws {
не к этому МРу, на будущее:
наверное стоит сделать массив валидаторов, каждый из которых валидирует какую-то часть. Удалить все `guard` и просто прогонять `amount` и `fee` через массив этих валидаторов, которые передаются извне

2024-03-22 12:27 UTC, megakoko commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +public struct TransactrionValidatorOptions {
Давай оставим "опции", "опция" не читается совсем

2024-03-22 12:37 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +public struct TransactrionValidatorOptions {
там опечатка: Transact`r`ion

2024-03-22 13:01 UTC, Balashov152 commented
Так а погодите, может игнорирование сделать просто на уровне приложения. Зачем `if` в BSDK. по факту логика только для одного экрана в приложении

do { } 
catch ValidationError. totalExceedsBalance {
// Ignore it. Do nothing
} catch { 
// Work with others errors
}

2024-03-22 13:41 UTC, megakoko commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +public struct TransactrionValidatorOptions {
Спасибо, исправил

2024-03-22 13:41 UTC, megakoko commented
@tureck1y @Andoran90 @Balashov152 обновил

2024-03-22 13:43 UTC, megakoko commented
> Так а погодите, может игнорирование сделать просто на уровне приложения. Зачем `if` в BSDK. по факту логика только для одного экрана в приложении.
> 
> ```
> do { } 
> catch ValidationError. totalExceedsBalance {
> // Ignore it. Do nothing
> } catch { 
> // Work with others errors
> }
> ```
> 
> P.S. Да, я точно против, игнорирование ошибки должно обрабатываться потребителем(так в Express есть уже), а не валидатором

После totalExceedsBalance в методе валидации могут быть еще исключения, которые бы СДК могло кинуть, но не кинет. Сейчас оно последнее, но я на это полагаться не хочу

2024-03-25 07:45 UTC, tureck1y commented
Мне тоже не нравятся опции, неправильное использование которых, позволит собрать транзакцию. Либо можно сделать как Серега предложил, либо вынести validateTotal например в отдельную функцию и вызывать кастомный набор методов из сенда по необходимости, но по умолчанию, validateTotal будет

2024-03-25 07:50 UTC, megakoko commented
> Мне тоже не нравятся опции, неправильное использование которых, позволит собрать транзакцию. Либо можно сделать как Серега предложил, либо вынести validateTotal например в отдельную функцию и вызывать кастомный набор методов из сенда по необходимости, но по умолчанию, validateTotal будет

При сборке транзакции мы все равно будем всю валидацию прогонять. Это метод СДК, туда никакие опции извне не передаются

2024-03-25 07:51 UTC, megakoko commented
По Серегиному предложению я писал выше. Если бы у нас возвращался массив ошибок что-то можно было игнорировать. Раньше так и было, потом поменяли

2024-03-25 08:42 UTC, tureck1y commented
> > Мне тоже не нравятся опции, неправильное использование которых, позволит собрать транзакцию. Либо можно сделать как Серега предложил, либо вынести validateTotal например в отдельную функцию и вызывать кастомный набор методов из сенда по необходимости, но по умолчанию, validateTotal будет
> 
> При сборке транзакции мы все равно будем всю валидацию прогонять. Это метод СДК, туда никакие опции извне не передаются

Вот же публичный метод с передачей опций

`func validateAmounts(amount: Amount, fee: Amount, options: TransactionValidatorOptions = .init())`

2024-03-25 08:44 UTC, megakoko commented
Для валидации — да, публичный. Сборка транзакции будет без опций валидироваться

<img width="791" alt="Screenshot 2024-03-25 at 16 43 39" src="https://github.com/tangem/blockchain-sdk-swift/assets/12209839/44e2578d-996a-4f9f-becd-4eb5cd178901">

2024-03-25 10:34 UTC, tureck1y commented
Закинул код по обсуждению

2024-03-25 11:02 UTC, megakoko commented
@tureck1y @Balashov152 поправил пробелы и порядок, все работает

2024-03-25 11:03 UTC, tureck1y approved these changes

2024-03-25 11:09 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +    func validate(fee: Amount) throws {
может стоит это и `validateTotal` добавить в протокол? а то получается что если кто-то захочет реализовать эти функции - будет браться дефолтная реализация из расширения.

2024-03-25 11:10 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +    func validate(fee: Amount) throws {
да по идее другая реализация невозможна, поэтому чтобы меньше было изменений, воткнули в экстеншн

2024-03-25 11:12 UTC, Balashov152 approved these changes

2024-03-25 11:12 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        // All checks completed
Вот это думаю лишнее

2024-03-25 11:13 UTC, Andoran90 approved these changes

2024-03-25 11:13 UTC, megakoko commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        // All checks completed
Коммент? Он старый

2024-03-25 11:13 UTC, merged