Feature/ios 6001 make transaction builder radiant
tangem/blockchain-sdk-swift pull request #623
Opened 2024-03-29 13:42 UTC by skibinalexander

Здесь ручная сборка транзакции для Радианта. Заюзать текущие либы в особенности WalletCore не получилось из-за specify обвязки радианта. Комменты по возможности оставил для более простого ревью

Был МР , стал Close потому что, переименовал ветки по нашим гайдам #619

2024-03-29 13:43 UTC, skibinalexander commented
Блокировано #621

2024-04-01 13:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +//  Created by Alexander Osokin on 14.02.2020.
🤣

2024-04-01 15:04 UTC, skibinalexander commented on BlockchainSdk/Common/NetworkProviderAssembly.swift
> +                blockchain: .bitcoinCash,
> артефакты разработки?

Да сори что - то лишнее :( пробегусь ревертну

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Bitcoin/BitcoinModels.swift
> +    init(transactionHash: String, outputIndex: Int, amount: UInt64, outputScript: String) {
nit: А зачем явный инит?

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/Domain/RadiantAmountUnspentTransaction.swift
> +        (amount.value * decimalValue).roundedDecimalNumber.decimalValue
Это округление up, не будет проблем в кейсе вывода под ноль?
Когда из-за округления сумма в сатошах и затем конвертации decimal в сатоши сумма превысит баланс

Как в https://github.com/tangem/blockchain-sdk-swift/pull/525

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/Domain/RadiantAmountUnspentTransaction.swift
> +        let fullAmountSatoshi = Decimal(unspents.reduce(0, {$0 + $1.amount}))
Переполнение возможно из-за сложения UInt64 тут?
Так как тут в коде не Decimal редюсится, а именно UInt64

Или значения мелкие и даже тысяча анспентов не превысит емкость UInt64?

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantAddressService.swift
> +        addressAdapter.validateSpecify(address, onlyUse: .p2pkh)
nit: Это какой-то новый метод? Я не понимаю что именно он specify из нейминга

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantScriptUtils.swift
> +        let scriptHash = sendScript.sha256().sha256()
Интересные ребята)
>Then the entire datastructure above is hashed with sha256 one more time.

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +    func buildForSend(transaction: Transaction, signatures: [Data], isDer: Bool) throws -> Data {
isDer никуда не передается - это ок? Если да - лучше удалить

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        scriptUtils.writeSequenceHash(tx.unspents, into: &txToSign)
А здесь вроде не ffffffff, а валидные байты пишутся, коммент мб некорректный?

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +    var utxo: [ElectrumUTXO] = []
А нельзя как-то избавиться от этого стейта в билдере и сделать его stateless?

`utxo` обновляются из воллетменеджера, но может быть такой кейс:
1. Успешно отправили транзакцию в сеть
2. update воллетменеджера зафейлился (например пропала сеть)
3. Делаем новую транзакцию - она собирается со старыми utxo (с которыми собрана прошлая транзакция в пункте 1)

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantWalletManager.swift
> +                    let walletCorePublicKey = PublicKey(data: self.wallet.publicKey.blockchainKey, type: .secp256k1),
тут сильно захватывается self

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantWalletManager.swift
> +                    isDer: true
В билдере этот арг не юзается и передается false, а тут true - выглядит подозрительно)

2024-04-02 08:46 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Radiant/RadiantWalletManager.swift
> +                        .isEmpty
Не очень понял этой проверки - тут мы проверяем что у нас НЕТ сигнатур, для которых `verifyAsDER` вернет true? Это ок?

Если ок - то мб переделать на `!contains`? Т.к. у contains есть ранний выход, а filter + isEmpty O(N)

2024-04-02 09:39 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +    var utxo: [ElectrumUTXO] = []
> А нельзя как-то избавиться от этого стейта в билдере и сделать его stateless?
> 
> `utxo` обновляются из воллетменеджера, но может быть такой кейс:
> 
> 1. Успешно отправили транзакцию в сеть
> 2. update воллетменеджера зафейлился (например пропала сеть)
> 3. Делаем новую транзакцию - она собирается со старыми utxo (с которыми собрана прошлая транзакция в пункте 1)

Про stateless подумаю. Но про кейс с фейлом не действительный, так как pending транзакция висеть будет

2024-04-02 12:03 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/Domain/RadiantAmountUnspentTransaction.swift
> +        (amount.value * decimalValue).roundedDecimalNumber.decimalValue
> Это округление up, не будет проблем в кейсе вывода под ноль? Когда из-за округления decimal и затем конвертации decimal в сатоши сумма превысит баланс
> 
> Как в #525

Пожалуй тут ты прав, оставлю как в 525

2024-04-02 12:10 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/Domain/RadiantAmountUnspentTransaction.swift
> +        let fullAmountSatoshi = Decimal(unspents.reduce(0, {$0 + $1.amount}))
> Переполнение возможно из-за сложения UInt64 тут? Так как тут в коде не Decimal редюсится, а именно UInt64
> 
> Или значения мелкие и даже тысяча анспентов не превысит емкость UInt64?

Тут по идее ок, не стал бы менять наверное сначала в Decimal кидать а потом его редюсить

2024-04-02 12:23 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +    func buildForSend(transaction: Transaction, signatures: [Data], isDer: Bool) throws -> Data {
> isDer

Убрал, действительно не нужен спасибо

2024-04-02 12:25 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantWalletManager.swift
> +                    isDer: true
> В билдере этот арг не юзается и передается false, а тут true - выглядит подозрительно)

Отписал в комменте выше

2024-04-02 12:36 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantScriptUtils.swift
> +            outputs.append(0.bytes4LE)
> А это `sequence` `0` ? Не должен быть 1, если это сдача, и первый аутпут уже есть с 0
> 
> По факту это порядковый номер аутпута в транзакции

Делал по их кошельку вроде как кладут 0

2024-04-02 12:38 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        txToSign.append(contentsOf: [UInt8(0x01),UInt8(0x00),UInt8(0x00),UInt8(0x00)])
> UInt64(0x01)

Поменять не Сложно, но для общего понимая лучше явно указывать 4 байта, Денису проще было смотреть так к примеру

2024-04-02 12:40 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        txToSign.append(contentsOf: [UInt8(0x01),UInt8(0x00),UInt8(0x00),UInt8(0x00)])
> Должно быть тоже самое 4 байта будет

ну и txToSign жто же [UInt8] орать будет компилятор

2024-04-02 12:40 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        txToSign.append(contentsOf: [UInt8(0xff),UInt8(0xff),UInt8(0xff),UInt8(0xff)])
> Даже просто `append()` можно

отписал чуть выше

2024-04-02 12:40 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        txToSign.append(contentsOf: [UInt8(0x00),UInt8(0x00),UInt8(0x00),UInt8(0x00)])
> Тут так же можно `UInt64(0)`

тоже чуть выше отписал

2024-04-02 16:46 UTC, dbaturin commented on BlockchainSdk/Blockchains/Radiant/Domain/RadiantAmountUnspentTransaction.swift
> +        let fullAmountSatoshi = Decimal(unspents.reduce(0, {$0 + $1.amount}))
Вроде и правда должно хватать UInt64 на всесь total supply коина.

2024-04-02 18:00 UTC, dbaturin requested changes
Тут есть такие же проблемы, что я описал для Андроида, что не удивительно, ведь логику копировали отсюда. 

Этот блокчейн - клон Bitcoin Cash с небольшими изменениями (по крайней мере для нашего применения пока). Было бы неплохо наследоваться от классов Bitcoin или даже Bitcoin Cash, по ситуации. Тогда не пришлось бы переписывать кучу кода, который по факту уже реализован. По сути, как-будто бы, только buildToSign пришлось бы переписать. С Достоном обсудили, что этот момент сейчас уже не очень важен, просто было бы проще изначально.

Electrum - это нода для биткоина изначально, и многие биткоиноподобные блокчейны тоже ноды на основе электрума делали. Надо бы нетворк сервис под интерфейс BitcoinNetworkProvider подогнать. Может понадобиться, когда другие биткоинообразные блокчейны будем добавлять. Ну и опять же, тогда наследоваться можно было бы.

2024-04-02 18:06 UTC, dbaturin commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        scriptUtils.writeSequenceHash(tx.unspents, into: &txToSign)
Sequence у нас "ffffffff only", а это её хэш. Почти правильно)

2024-04-02 20:44 UTC, skibinalexander commented
> Тут есть такие же проблемы, что я описал для Андроида, что не удивительно, ведь логику копировали отсюда. 
> 
> 
> 
> Этот блокчейн - клон Bitcoin Cash с небольшими изменениями (по крайней мере для нашего применения пока). Было бы неплохо наследоваться от классов Bitcoin или даже Bitcoin Cash, по ситуации. Тогда не пришлось бы переписывать кучу кода, который по факту уже реализован. По сути, как-будто бы, только buildToSign пришлось бы переписать. С Достоном обсудили, что этот момент сейчас уже не очень важен, просто было бы проще изначально.
> 
> 
> 
> Electrum - это нода для биткоина изначально, и многие биткоиноподобные блокчейны тоже ноды на основе электрума делали. Надо бы нетворк сервис под интерфейс BitcoinNetworkProvider подогнать. Может понадобиться, когда другие биткоинообразные блокчейны будем добавлять. Ну и опять же, тогда наследоваться можно было бы.

Выдержать замечание достаточно сложно , у нас есть общий менеджер которые работает с BitcoinCore , при этом от него мы будем отказываться , и делать туда МР только specify радиант бессмысленно, надо договорится тогда о концепции , но рефакторинг мы планировали на будущее в этой части вопроса.

Что касается электрума, тут опять запрос понятен, но есть различия которые описал Никита в треде, которые сложно выдержать и предусмотреть , при этом не использовать для других блокчейнов, в рамках этого МР будет оверинжиниргом на мой взгляд

2024-04-03 05:19 UTC, skibinalexander commented
@tureck1y твое внимание требуется

2024-04-03 08:22 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +        txToSign.append(contentsOf: [UInt8(0x01),UInt8(0x00),UInt8(0x00),UInt8(0x00)])
Так точно можно, делал в `Nexa`,  и в `BitcoinCore`. Ну если так удобней, то ок)

2024-04-03 08:31 UTC, Balashov152 commented
Вставлю свои пять копеек 

> Было бы неплохо наследоваться от классов Bitcoin или даже Bitcoin Cash, по ситуации. 

Наследование не круто, мы пытаемся отказаться от него по большей части все делать через протоколы и разные объекты, так как это намного проще поддерживать, и не аффектит ничего лишнего когда меняется один объект

У нас сейчас просто нет такой базы Bitcoin подобных, что бы ее можно было удобно подстраивать под себя. Надеюсь в будущем у нас такая будет)

2024-04-03 14:17 UTC, tureck1y commented on BlockchainSdk/Blockchains/Radiant/RadiantTransactionBuilder.swift
> +    var utxo: [ElectrumUTXO] = []
ну utxo все равно где-то держать придется

2024-04-03 14:21 UTC, tureck1y commented
Тут получается следующая ситуация. Сейчас по биткоинподобным мы сидим на BitcoinCore. Либа нам не нравится и мы хотим уйти на WalletCore в ближайшее время, однако у радианта были изменения в сборке и допиливать BitcoinCore было нецелесообразно. Смотрели на WalletCore и на старую, но работающую, реализацию BitcoinCash. Сейчас допилить WalletCore было сложновато, поэтому взяли старую.

2024-04-03 14:22 UTC, tureck1y commented
Если получится WalletManager отнаследовать от BitcoinWalletManager, то ок

2024-04-03 14:23 UTC, tureck1y approved these changes
Авансом ок, мне дополнить нечего

2024-04-03 15:10 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantAddressUtils.swift
> +        return Data(scriptHashData.sha256().reversed()).hexString
* переименовать и проверить одинаковость операций

2024-04-04 02:51 UTC, skibinalexander commented
> Если получится WalletManager отнаследовать от BitcoinWalletManager, то ок
По комментам , выше + Серегины, пока лучше не делать, попачкаем реализацию, менеджера, лучше в рамках рефакторинга учесть сборку PreImage hashes ждя BCH и BSV

2024-04-04 02:51 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantScriptUtils.swift
> +    func writePrevoutHash(_ unspents: [RadiantUnspentOutput], into txToSign: inout Data) {
> Этот и последующие функции с хэшами не связаны со скриптами и им тут не место.

Обсудили переименовал в RadiantTransactionUtils

2024-04-04 02:59 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantAddressUtils.swift
> +        return Data(scriptHashData.sha256().reversed()).hexString
Думаю лучше оставить через адрес, так как в спецификации электрума идет трансформация адреса

2024-04-04 10:55 UTC, Balashov152 approved these changes

2024-04-04 11:34 UTC, dbaturin approved these changes

2024-04-04 12:18 UTC, merged

2024-04-04 12:28 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Radiant/RadiantWalletManager.swift
> +                    !walletCorePublicKey.verifyAsDER(signature: sig, message: Data(hashesForSign[index].reversed()))
Проверял на тестах , работало как надо , перепроверю