IOS-6429 Added UTXOTransactionFeeCalculator
tangem/blockchain-sdk-swift pull request #625
Opened 2024-04-01 04:51 UTC by megakoko

На уровне приложения будем вызывать этот метод, передавать туда satoshi per byte и показывать кастомную комиссию которую насчитаем

<img width="695" alt="Screenshot 2024-04-01 at 12 50 49" src="https://github.com/tangem/blockchain-sdk-swift/assets/12209839/97a8554b-f4f0-421e-97d3-127c0aecbb97">

2024-04-01 08:25 UTC, Balashov152 submitted a review, later dismissed

2024-04-01 12:33 UTC, Andoran90 approved these changes, later dismissed

2024-04-01 13:24 UTC, tureck1y commented
надо бы утвердить сначала

2024-04-02 14:38 UTC, tureck1y approved these changes, later dismissed

2024-04-03 12:38 UTC, dbaturin requested changes
UTXO механизм напрямую не связан, с тем, как фи рассчитывается.
Это должен быть либо BitcoinTransactionFeeCalculator, либо FeePerByteTransactionFeeCalculator. Если второе, то термин satoshi кажется слишком спецефичным.

2024-04-03 12:44 UTC, megakoko commented
> UTXO механизм напрямую не связан, с тем, как фи рассчитывается. Это должен быть либо BitcoinTransactionFeeCalculator, либо FeePerByteTransactionFeeCalculator. Если второе, то термин satoshi кажется слишком спецефичным.

Здесь UTXO — это отсылка к UTXO-based блокчейнам. Сейчас кастомная комиссия рассчитывается только для биткоина, в последующем может для других появится

2024-04-03 14:25 UTC, tureck1y commented
Ну давайте сделаем BitcoinTransactionFeeCalculator

2024-04-04 03:36 UTC, megakoko commented
@dbaturin @tureck1y @Andoran90 @Balashov152 обновил

2024-04-04 05:24 UTC, Andoran90 approved these changes

2024-04-04 07:28 UTC, merged