IOS-6400 Add fixed estimation addresses for several blockchains
tangem/blockchain-sdk-swift pull request #631
Opened 2024-04-02 15:50 UTC by fedorov-d

адреса взяты отсюда https://tangem.atlassian.net/browse/IOS-6400

2024-04-02 18:15 UTC, dbaturin approved these changes, later dismissed

2024-04-03 14:33 UTC, tureck1y requested changes
Генерацию надо совсем убрать

2024-04-04 11:20 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
Ну финального решения так и нет, но с легаси адресом транзакция будет уходить )

2024-04-04 12:06 UTC, Balashov152 requested changes

2024-04-04 12:06 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "addr1vxkgxehrx5c049azfalr9mxhr5u3njvuqu6da95qtyuwj2s0fazfp"
Надо длинный сделать, который на Wallet 2.0. Так как от провайдеров приходит длинный и транзакция будет больше.

тот старый вроде как у Регины был на `seed-phrase`

2024-04-04 12:16 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
хм, а тут вроде который и нужен, на `ltc1` начинается.

2024-04-04 12:59 UTC, tureck1y commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
Точно?)

2024-04-04 14:08 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
Так, еще раз проверил
Нужен `P2SH` - это который начинается с цифры, like `342ftSRCvFHfCeFFBuz4xwbeqnDw6BGUey`. У нас это вроде бы как раз legacy.

Дока - https://unchained.com/blog/bitcoin-address-types-compared/

2024-04-05 11:59 UTC, dbaturin approved these changes, later dismissed

2024-04-05 11:59 UTC, dbaturin commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
Не понял, зачем P2SH адрес?

2024-04-08 09:48 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
>Не понял, зачем P2SH адрес?

некоторые провайдеры в Express присылают его, как `destination`. И при попытке вывести все, у нас получается ошибка, так как `estimatedFee` < `realFee`. Решили сделать здесь такой адрес, что бы по нему комса считалась "с запасом"

2024-04-10 18:21 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
я протестировал с P2SH, в случае с change now, реальная комиссия действительно начинает совпадать с эстиметом, в случае с changelly - реальная все равно немного больше

2024-04-12 09:30 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qn7zu6luzkzdej6lnurwzmejd3hq44gz68e42ue"
upd: changelly действительно присылает P2SH адреса, для который комиссия больше, пока не понятно как поправить, наш кошелек их не генерит. пока предлагаю смержить то что есть, а по ltc в рамках отдельного бага разбираться.

2024-04-12 09:32 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "addr1vxkgxehrx5c049azfalr9mxhr5u3njvuqu6da95qtyuwj2s0fazfp"
обновил, но к сожалению для changelly не помогает, т.к. он присылает Byron адреса для которых комиссия больше

2024-04-12 14:26 UTC, dbaturin submitted a review, later dismissed

2024-04-12 14:31 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return ""
В итоге не смогли сделать что ли?)

2024-04-12 17:37 UTC, tureck1y commented on BlockchainSdk/Blockchains/Tezos/TezosWalletManager.swift
> +        // We assume that account is not created therefore we're adding allocation fee
Это у обоих провайдеров да?

2024-04-12 17:37 UTC, tureck1y commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return ""
Обязательно сразу задачу заведи в следующий спринт, чтобы не забыть

2024-04-12 17:37 UTC, tureck1y commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
>          switch blockchain {
В файле можно импорт TangemSdk подчистить еще

2024-04-16 09:07 UTC, m3g0byt3 reviewed
⁣⁣

2024-04-16 15:13 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return ""
обсудил с Сашей, радиант не зависит от destination, перенес в соответствующее место

2024-04-16 15:14 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
>          switch blockchain {
убрал

2024-04-16 15:18 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +             .radiant:
согласовано с @skibinalexander

2024-04-17 09:15 UTC, Balashov152 approved these changes

2024-04-17 10:06 UTC, tureck1y approved these changes

2024-04-18 13:40 UTC, dbaturin approved these changes

2024-04-19 10:16 UTC, m3g0byt3 approved these changes

2024-04-19 12:01 UTC, merged