IOS-5277 Fix decimal link
tangem/blockchain-sdk-swift pull request #638
Opened 2024-04-05 13:03 UTC by skibinalexander

Фикс ссылки на decimal

2024-04-05 13:03 UTC, skibinalexander commented
> Фикс ссылки на decimal explorer

2024-04-05 13:43 UTC, tureck1y approved these changes

2024-04-08 03:24 UTC, megakoko approved these changes

2024-04-08 07:26 UTC, Andoran90 approved these changes

2024-04-10 15:02 UTC, dbaturin requested changes
У меня показало только свежую транзакцию, только uppercase и без 0x. Ту, что в примере не показало никак

2024-04-15 05:31 UTC, skibinalexander commented
> У меня показало только свежую транзакцию, только uppercase и без 0x. Ту, что в примере не показало никак
<img width="1038" alt="Снимок экрана 2024-04-15 в 08 30 41" src="https://github.com/tangem/blockchain-sdk-swift/assets/5384724/fc497cf3-0198-4e84-8ee0-53b8a3d8e390">

2024-04-15 05:32 UTC, skibinalexander commented
> У меня показало только свежую транзакцию, только uppercase и без 0x. Ту, что в примере не показало никак

Даже не знаю как быть :(( он видимо то показывает то нет

2024-04-15 13:45 UTC, skibinalexander commented
@dbaturin давай тут решим что нибудь , не ясно

2024-04-15 15:20 UTC, dbaturin commented
> @dbaturin давай тут решим что нибудь , не ясно

Я сейчас глянул, у них всё то же. Если зайти в раздел транзакции, то вообще пусто.

Но со скрином я понял теперь. То, как у тебя этот хэш передаётся - это как в EVM, с 0x и lowercase. А другой хэш вообще другой. Мне по блокам лазая так и не удалось найти ни одной EVM транзакции. Может у них именно EVM часть отваливается?

А выключить вообще ссылку на транзакцию мы не можем? Или может можно её не по EVM хэшу стабильно находить? Вроде по другому хэшу со скрина находится и сейчас - https://explorer.decimalchain.com/transactions/D4E22A557F947ECDE037DC7DE43941641BA99811B1504D3EA50FAA461F7014B4

Я в общем за 1 из этих 2 вариантов, оставлять полурабочую ссылку не хотелось бы. Хотя наверное лучше, чем стабильно нерабочая всё же

2024-04-17 05:40 UTC, skibinalexander commented
> > @dbaturin давай тут решим что нибудь , не ясно
> 
> Я сейчас глянул, у них всё то же. Если зайти в раздел транзакции, то вообще пусто.
> 
> Но со скрином я понял теперь. То, как у тебя этот хэш передаётся - это как в EVM, с 0x и lowercase. А другой хэш вообще другой. Мне по блокам лазая так и не удалось найти ни одной EVM транзакции. Может у них именно EVM часть отваливается?
> 
> А выключить вообще ссылку на транзакцию мы не можем? Или может можно её не по EVM хэшу стабильно находить? Вроде по другому хэшу со скрина находится и сейчас - https://explorer.decimalchain.com/transactions/D4E22A557F947ECDE037DC7DE43941641BA99811B1504D3EA50FAA461F7014B4
> 
> Я в общем за 1 из этих 2 вариантов, оставлять полурабочую ссылку не хотелось бы. Хотя наверное лучше, чем стабильно нерабочая всё же

@dbaturin  Короче предлагаю закрыть тогда и задачу и МР, потому Decimal ну совсем маленькие, они у нас интегрированы как EVM. Они 100500 раз фиксили этот explorer чтобы он показывал evm. Что скажешь, вообще сомневаюсь, что у нас есть хоть 5 человек кто будет пользоваться переходом

2024-04-17 13:54 UTC, dbaturin commented
Ну тогда у нас будет неработающий переход. Давай так:
1. Если можно легко переделать EVM хэш в их хэш, делаем так.
2. Если можно без допиливаний запретить этот переход для этого блокчейна, то делаем так.
3. Если ничего выше легко сделать не получается, принимаем PR как есть, с надеждой, что допилят. Лучше переход, который может в итоге заработать, чем принципиально нерабочий.

Раз она такая не популярная, то много времени не трать на ресёрч. Нет, так нет

2024-04-17 14:15 UTC, skibinalexander commented
> @skibinalexander Ну тогда у нас будет неработающий переход. Давай так:
> 
> 1. Если можно легко переделать EVM хэш в их хэш, делаем так.
> 2. Если можно без допиливаний запретить этот переход для этого блокчейна, то делаем так.
> 3. Если ничего выше легко сделать не получается, принимаем PR как есть, с надеждой, что допилят. Лучше переход, который может в итоге заработать, чем принципиально нерабочий.
> 
> Раз она такая не популярная, то много времени не трать на ресёрч. Нет, так нет

Я имел в виду как раз не вливать этот МР, у нас просто плашка pending транзакции без перехода в эксплорер. Поэтому захочет посмотреть транзакции просто перейдет в эксплорер

2024-04-17 14:16 UTC, skibinalexander commented
> @skibinalexander Ну тогда у нас будет неработающий переход. Давай так:
> 
> 1. Если можно легко переделать EVM хэш в их хэш, делаем так.
> 2. Если можно без допиливаний запретить этот переход для этого блокчейна, то делаем так.
> 3. Если ничего выше легко сделать не получается, принимаем PR как есть, с надеждой, что допилят. Лучше переход, который может в итоге заработать, чем принципиально нерабочий.
> 
> Раз она такая не популярная, то много времени не трать на ресёрч. Нет, так нет

то есть как раз пункт 2 получается

2024-04-17 14:16 UTC, closed without merging