IOS-3498 Move ETH on WalletCore (EIP1559 transaction type)
tangem/blockchain-sdk-swift pull request #652
Opened 2024-04-15 14:58 UTC by Balashov152

Основные изменения:
- `EthereumTransactionBuilder` новая сборка транзакций
- `EthereumTests` доабвил тесты для нового типа транзакций, обновил под новый билдер
- Наследники `DecimalWalletManager/DecimalTransactionBuilder` и `XDCWalletManager/XDCTransactionBuilder` для адаптации к новому `EthereumTransactionBuilder`

2024-04-15 15:03 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +    let networkService: EthereumNetworkService
Убрал `force_unwrap`. Сделал через `init`. Более очевидная реализация)

2024-04-15 15:03 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> -    func send(_ transaction: SignedEthereumTransaction) -> AnyPublisher<String, Error> {
Не использовался

2024-04-15 15:06 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> -        pendingTxCount = response.pendingTxCount
не было смысла в хранении именно в WalletManager

2024-04-15 15:12 UTC, Balashov152 commented on BlockchainSdk/Common/Utils/EthereumUtils.swift
> +            return BigUInt(decimal.rounded().uint64Value)
Если `decimal` с значением после запятой, то `uint64Value` было `0`

2024-04-16 13:27 UTC, dbaturin requested changes

2024-04-16 13:27 UTC, dbaturin commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    public func buildForL1(destination: String, value: String?, data: Data?, fee: Fee) throws -> Data {
Может обозначить, что это не настоящая транзакция собирается, а dummy? И точно ли нельзя код из стандартых функций для сборки переиспользовать?

2024-04-16 13:27 UTC, dbaturin commented on BlockchainSdkTests/Common/BlockchainSdkTests.swift
> +        XCTAssertTrue(ethAddressService.validate("0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9adb"))
Неа, не валидный это адрес. Правильный чексам адрес можно на странице эксплорера увидеть и он выглядит так - 0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9aDb

Предпоследний символ в верхнем регистре должнен быть. Так в принципе чексам на эфире сделали уже как надстройку над глупым адресом без чексама, для обратной совместимости. Чексам зашит в то, какие буквы в каком регистре.

Логика должна быть такая, валидными (с точки зрения чексама) адресами могут считаться:
1. Без чексама - полностью lowercase или uppercase
2. С правильным чексамом - если mixed case, чесам проверяем.

2024-04-17 14:03 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    public func buildForL1(destination: String, value: String?, data: Data?, fee: Fee) throws -> Data {
Переименовал в `buildDummyTransactionForL1`. Через обычный метод не получается, так как придется логику по `buildERC20TransferData` в двух менеджерах писать )

2024-04-17 14:04 UTC, Balashov152 commented on BlockchainSdkTests/Common/BlockchainSdkTests.swift
> +        XCTAssertTrue(ethAddressService.validate("0xD1220A0cf47c7B9Be7A2E6BA89F429762e7b9adb"))
Вернул `EthereumAddressService` со всей старой логикой

2024-04-18 10:47 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let signature = unmarshal.r + unmarshal.s + Data([UInt8.zero])
Попробовал еще раз передать V. Опять ошибка у них, причем я никак не могу найти по коду ее.

Я тут подумал, что у нас раньше в `EthereumTransaction` при `encode` использовалась формула 
`v - 27 + chainID * 2 + 35` 

и `v` во всех моих тестах, около 10 был `27`. 
Получается что использовали как раз `0 + chainID * 2 + 35` 

И я думаю передавать им как ранее было у нас `v - 27`. Что думаешь ?

2024-04-18 11:30 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Ethereum/Interfaces/EthereumNetworkProvider.swift
> +    func getBaseFee() -> AnyPublisher<BigUInt, Error>
больше фи богу фи...

Вообще выглядит так будто нам надо убрать из сдк логику подкручивания фи и перенести её в приложение, т.к. в контексте блокчеина нет приоритетного или не приоритетного фи, хочешь чтобы быстрее твою транзу взяли - ставь высокую комиссию. Может я по ходу чтения пока что не правильно понял смысла именно тут, но кажется что в целом лучше выдавать на `getFee`, только одно значение, а там уже дальше пусть приложение делает с ним что хочет.

Ну или хотя бы не на уровне `NetworkProvider`/`NetworkService` это делать

2024-04-18 11:30 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumNetworkService.swift
> +        let lowBaseFee = baseFee * BigUInt(85) / BigUInt(100) // - 15%
может сделать какую-нибудь дженериковую фабрику с параметром % накрутки (чтобы адаптировать для каждого блокчеина во время инициализации фабрики), которая будет заниматься этими вещами и `WalletManager` будет просить давать список фи. В `NetworkService` это выглядит совершенно неуместным

2024-04-18 11:30 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/WalletManager.swift
>  @available(iOS 13.0, *)
надо б везде почистить, наверное уже, не к этому МРу предложение.

2024-04-18 11:30 UTC, Andoran90 commented on BlockchainSdkTests/Ethereum/EthereumTests.swift
> +    func test_eth_address() {
почему названия тестов змейкой пошли?

2024-04-18 11:30 UTC, Andoran90 commented on BlockchainSdkTests/Ethereum/EthereumTests.swift
> +    func test() throws {
хотя бы `testV`...

2024-04-18 12:10 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    init(chainId: Int?) throws {
А если тут не нужен опциона прям в начале, может переложить на вызывающего?

2024-04-18 12:11 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    public func update(nonce: Int) {
нужен public?

2024-04-18 12:23 UTC, skibinalexander commented on BlockchainSdk/Common/SignatureInfo.swift
> +    let hash: Data
Тут может коммент, а то получается вроде как много блокчейнов юзают эту модельку либо я конечно не понял

2024-04-18 12:24 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumResponse.swift
> +    let baseFees: (low: BigUInt, market: BigUInt, fast: BigUInt)
А точно хотим хардкодить 3 элемента?

2024-04-18 12:25 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumResponse.swift
> +    let baseFees: (low: BigUInt, market: BigUInt, fast: BigUInt)
Просто тогда лучше структурку наверное

2024-04-18 12:25 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumNetworkService.swift
> +                return networkService.mapToEthereumFeeResponse(
Тут также может все такие массив лучше будет, из менеджера массив улетает

2024-04-18 13:00 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    init(chainId: Int?) throws {
Я думал но в `Assemblies` везде `force_unwrap`. по этому перевел сюда.
Вообще конечно можно и там проверять

2024-04-18 13:01 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletAssembly.swift
>      func make(with input: WalletManagerAssemblyInput) throws -> WalletManager {
Первый @Andoran90 пойдет, я потом подтяну

2024-04-18 14:41 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let signature = unmarshal.r + unmarshal.s + Data([UInt8.zero])
Вообще так сработало, проверил еще пару транзакций, и иногда v - `0x1` идет

2024-04-18 14:43 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Interfaces/EthereumNetworkProvider.swift
> +    func getBaseFee() -> AnyPublisher<BigUInt, Error>
Вообще согласен, на просто иногда нужно получить отдельно `baseFee/priorityFee` как это было с `gasPrice` для того же WC. По этому добавил методы, что без изменений в BSDK можно было получать разное

2024-04-18 14:44 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumNetworkService.swift
> +        let lowBaseFee = baseFee * BigUInt(85) / BigUInt(100) // - 15%
Вообще звучит как задача для техдолга, в этом MR думаю смысла нет так делать)

2024-04-18 14:44 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/WalletManager.swift
>  @available(iOS 13.0, *)
Да, тоже об этом говорил уже, надо тоже в backlog завести

2024-04-18 14:47 UTC, Balashov152 commented on BlockchainSdkTests/Ethereum/EthereumTests.swift
> +    func test_eth_address() {
Вернул верблюдов) ✅  Да чет не знаю зачем поменял

2024-04-18 14:48 UTC, Balashov152 commented on BlockchainSdkTests/Ethereum/EthereumTests.swift
> +    func test() throws {
Удалил вообще

2024-04-18 14:48 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    public func update(nonce: Int) {
Сделал все `internal` ✅

2024-04-18 14:48 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    public func buildForSend(transaction: Transaction, signatureInfo: SignatureInfo) throws -> Data {
Сделал все `internal` ✅

2024-04-18 14:50 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +    /// - Parameters:
Мне кажется нет, сразу понятно что это именно raw transaction hex для отправки в сеть. Просто сам метод этого не отображает

2024-04-18 14:51 UTC, Balashov152 commented on BlockchainSdk/Common/SignatureInfo.swift
> +    let hash: Data
Добавил ✅

2024-04-18 14:53 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumResponse.swift
> +    let baseFees: (low: BigUInt, market: BigUInt, fast: BigUInt)
Добавил typealias. Структура мне кажется лишняя тут ✅

2024-04-18 14:55 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumNetworkService.swift
> +                return networkService.mapToEthereumFeeResponse(
Так а как массив, у нас же три параметра мапятся в `EthereumFeeResponse`

2024-04-18 14:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let signature = unmarshal.r + unmarshal.s + Data([UInt8.zero])
Ну, если работает стабильно, то хорошо. Если были результаты с разным V, похоже, что так и есть. Видимо, всё же заново рассчитывается, в WalletCore мне сложно ориентироваться.

2024-04-18 15:09 UTC, dbaturin commented on BlockchainSdk/Blockchains/Ethereum/Interfaces/EthereumNetworkProvider.swift
> +    func getBaseFee() -> AnyPublisher<BigUInt, Error>
Это вообще тут не связано с рынком фи и тем, как ты быстро хочешь транзакцию провести. Это разные параметры, которые оба в транзакцию задаются после EIP-1559. Ну точнее в транзакцию задаётся max fee = base + priority и priority отдельго, но не суть.

Кстати, я вижу, что мы base fee считаем сами по base fee последних блоков, как много где предлагают. Интересно, а на сколько это значения отличается от того, что приходит с легаси ручки gasPrice? Мне казалось, что оно может быть крайне близко должно получиться, если priority fee вычесть. Только нода это рассчитывает, а не мы, может, конечно, алгоритм слегка отличаться.

2024-04-18 15:14 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Interfaces/EthereumNetworkProvider.swift
> +    func getBaseFee() -> AnyPublisher<BigUInt, Error>
Вообще baseFee +- похож на gasPrice. Вот этот EIP-1559 больше для "наглядности/управления" комиссиями

2024-04-18 15:16 UTC, dbaturin submitted a review, later dismissed

2024-04-18 16:03 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumNetworkService.swift
> +                return networkService.mapToEthereumFeeResponse(
> Так а как массив, у нас же три параметра мапятся в `EthereumFeeResponse`

Ну я подумал может более гибко будет не конкретными величинами, ну окей понял

2024-04-18 16:03 UTC, skibinalexander submitted a review, later dismissed

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/XDC/XDCAddressService.swift
> +        let ethAddress = try ethereumAddressService.makeAddress(for: publicKey, with: .default).value
я так понимаю можно убрать тут .value и тогда legacy не придется заворачивать еще раз в PlainAddress

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Common/Utils/EthereumUtils.swift
> +            return BigUInt(decimal.rounded().uint64Value)
У меня даже задача есть в бэклоге проверить все такие места, есть еще использования, надо ее вытащить из бэклога

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdkTests/Common/BlockchainSdkTests.swift
> +        let chesksummed = EthereumAddressService().toChecksumAddress("0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359")
а почему тут и ниже юзается EthereumAddressService() вместо ethAddressService?

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +    func getGasLimit(to: String, from: String, value: String?, data: String?) -> AnyPublisher<BigUInt, Error> {
Хочется эфировский NetworkService открыть в паблик, чтобы не писать такие штуки. Для WC тоже надо. Но непонятно как его собирать теперь. @Andoran90 может через фабрику какую-то? И реюзать ее в EthereumWalletAssembly

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    init(chainId: Int?) throws {
Ну да, лучше в ассемлях фейлится

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let signature = Data(hex: "28ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa63627667cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83")
Так, а @dbaturin говорил, что для оракула l1 фи подпись не нужна, а теперь добавляется

2024-04-25 18:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let unmarshal = try secp256k1Signature.unmarshal(with: decompressed, hash: signatureInfo.hash)
А ниже в коде юзается же

2024-05-08 15:11 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let unmarshal = try secp256k1Signature.unmarshal(with: decompressed, hash: signatureInfo.hash)
Да, обсудили ниже, что с `V-27` все ок

2024-05-13 11:13 UTC, Balashov152 commented on BlockchainSdk/Blockchains/XDC/XDCAddressService.swift
> +        let ethAddress = try ethereumAddressService.makeAddress(for: publicKey, with: .default).value
не, не получается, как раз ошибка получалась, так как надо сделать default адрес в ETH
и использовать его как `legacy`. А XDC - `default` будет уже другой

2024-05-13 11:31 UTC, Balashov152 commented on BlockchainSdk/Blockchains/EthereumOptimisticRollup/EthereumOptimisticRollupWalletManager.swift
> +            .switchToLatest()
✅

2024-05-13 11:32 UTC, Balashov152 commented on BlockchainSdkTests/Common/BlockchainSdkTests.swift
> +        let chesksummed = EthereumAddressService().toChecksumAddress("0xfb6916095ca1df60bb79ce92ce3ea74c37c5d359")
AddressServiceFactory возращет протокол AddressService в котором нет `toChecksumAddress`
сделал вот так
```
        let addressService = AddressServiceFactory(blockchain: blockchain).makeAddressService()
        let ethAddressService = try XCTUnwrap(addressService as? EthereumAddressService)
```

2024-05-13 11:32 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let signature = Data(hex: "28ef61340bd939bc2195fe537567866003e1a15d3c71ff63e1590620aa63627667cbe9d8997f761aecb703304b3800ccf555c9f3dc64214b297fb1966a3b6d83")
точно, спасибо, а чет забыл совсем про это, переделал норм ✅

2024-05-13 11:34 UTC, Balashov152 commented
Были `force-push` из за `rebase on develop`

2024-05-13 11:39 UTC, tureck1y approved these changes, later dismissed

2024-05-13 11:39 UTC, tureck1y commented on BlockchainSdk/Blockchains/Cardano/Rosetta/RosettaNetworkProvider.swift
> +                  let amount = Decimal(string: amountValue) else {
Надо будет написать, чтобы протестили кардану на розетте

2024-05-13 11:51 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/Rosetta/RosettaNetworkProvider.swift
> +                  let amount = Decimal(string: amountValue) else {
блин, а это случайно попало походу, уберу лучше
В Кардано токенах вообще будет все на UInt64

2024-05-13 16:22 UTC, tureck1y submitted a review, later dismissed

2024-05-13 17:06 UTC, dbaturin submitted a review, later dismissed

2024-05-13 17:06 UTC, dbaturin commented on BlockchainSdk/Common/SignatureInfo.swift
> +    let hash: Data
Название hash - не самое лучшее. Для ed25519 частенько не хэши на подпись уходят, а большой пэйлоад какой-нибудь. Ну это так, совсем мелочь.

2024-05-14 06:33 UTC, skibinalexander submitted a review, later dismissed

2024-05-14 06:33 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/EthereumAddressService.swift
>      public func makeAddress(for publicKey: Wallet.PublicKey, with addressType: AddressType) throws -> Address {
А если WalletCore должны адрес сами собирать или лучше тоже переехать ?

2024-05-14 06:33 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    private let coinType: CoinType = .ethereum
Может тоже настроить из вне , примеров нет где coin type может отличаться , но мало ли

2024-05-14 07:53 UTC, Andoran90 submitted a review, later dismissed

2024-05-21 18:36 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    private let coinType: CoinType = .ethereum
наоборот лучше внутри, что бы случайно `bitcoin` не передали

2024-05-21 18:39 UTC, dbaturin approved these changes, later dismissed

2024-05-21 19:30 UTC, Balashov152 commented
Пофиксил билд, не правильно смержил (

2024-05-21 19:45 UTC, skibinalexander commented
> Пофиксил билд, не правильно смержил (

Что то тесты лежат

2024-05-21 20:05 UTC, tureck1y approved these changes, later dismissed

2024-05-22 06:57 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +    func getGasLimit(to: String, from: String, value: String?, data: String?) -> AnyPublisher<BigUInt, Error> {
кстати, это нам понадобится не только для эфира, когда начнем добавлять новые сети в WC + вряд ли получится закрыть получение фи, методы разных `NetworkService` единым протоколом. Наверное стоит сделать фабрику сервисов для внешних пользователей, в которые передавать списки апишек, блокчеин. Но это стоит отдельно обсудить, собрать требования и рефачить и в блокченСДК и в приложении. Хочется подчистить `WalletModel` и убрать оттуда геттеры разных протоколов

2024-05-22 06:57 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +            if let feeParameters = fee.parameters as? EthereumFeeParameters {
а где-то вообще будет использоваться теперь `EthereumFeeParameters`? может действительно его удалить сразу или для чего его оставляем?

2024-05-23 11:35 UTC, skibinalexander submitted a review, later dismissed

2024-05-23 11:51 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +            if let feeParameters = fee.parameters as? EthereumFeeParameters {
Он сейчас в WalletConent используется, ну могу выкинуть, и там переделать получается

2024-05-23 12:01 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumAddressService.swift
>      public func makeAddress(for publicKey: Wallet.PublicKey, with addressType: AddressType) throws -> Address {
там нет валидации по checksum, по этому решил что свой останется

2024-05-23 12:02 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumResponse.swift
> +    typealias Fees = (low: BigUInt, market: BigUInt, fast: BigUInt)
Массив не очень хочу, именно типизированной хочется, добавил `EthFee `

2024-05-23 12:04 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +            if let feeParameters = fee.parameters as? EthereumFeeParameters {
Убрал Legacy ✅

2024-05-23 12:05 UTC, Balashov152 commented
@tureck1y @dbaturin @Andoran90 @skibinalexander давайте лить, поправил еще по паре комментов

2024-05-23 12:27 UTC, Andoran90 approved these changes, later dismissed

2024-05-23 13:04 UTC, tureck1y approved these changes, later dismissed
для WC не оторвет ничего?

2024-05-23 13:37 UTC, Balashov152 commented
> для WC не оторвет ничего?

ну будет по другому Fee идти, все остальное так же, по тестам все ок

2024-05-23 16:29 UTC, dbaturin approved these changes, later dismissed

2024-05-23 21:51 UTC, Balashov152 commented
В этот раз все решили/обсудили все таки maxFeePerGas правильное название, плюс более правильно сделал расчет fee

2024-05-24 06:38 UTC, Andoran90 approved these changes

2024-05-24 08:46 UTC, tureck1y approved these changes

2024-05-24 10:19 UTC, skibinalexander approved these changes

2024-05-24 11:34 UTC, dbaturin approved these changes

2024-05-24 11:35 UTC, merged