IOS-6286 Cardano tokens
tangem/blockchain-sdk-swift pull request #666
Opened 2024-04-24 23:48 UTC by Balashov152

2024-04-24 23:48 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/Adalite/AdaliteNetworkProvider.swift
> +                // Because in response the hash is equal `"239392bc6c6bd354d5a95b77f799b61ac056c65566a10bb50033a7c9deabfe42"`
Не работала ссылка на explorer из за лишних кавычек

2024-05-13 18:33 UTC, dbaturin requested changes

2024-05-14 18:58 UTC, tureck1y requested changes

2024-05-14 18:58 UTC, tureck1y commented on BlockchainSdk/Common/Amount.swift
> +    }
Я бы эту штуку сюда не добавлял. Сейчас это лежит в блокчейне, что тоже не очень. По хорошему нужна утилита-конвертер.

1) Нам надо в целом переходить на целые числа, тогда это не понадобится
2) Смысл этого значения был просто в значении делителя для конвертами, а тут кажется что это значение amount в Decimal

2024-05-15 11:42 UTC, Balashov152 commented on BlockchainSdk/Common/Amount.swift
> +    }
Вообще да, согласен
надо переходить на BigInt в Amount. А в decimal через отдельный конвертер преобразовывать только для UI
Убрал ✅

2024-05-15 11:49 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let minChange = try minChange(exclude: amount.type)
Убрал исключение в этом случае ✅

2024-05-15 11:49 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let minChange = try minChange(exclude: amount.type)
Да, согласен для коина вообще это не нужно ✅

2024-05-15 11:49 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let hasAnotherTokenWithBalance = wallet.amounts
Сделал по другому не много, этот флаг нужен если только весь токен отправляем ✅

2024-05-15 11:51 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +    private func validateCardanoCoinWithdrawal(amount: Amount, fee: Amount, hasAnotherTokenWithBalance: Bool) throws {
Сделал более просто 
`CardanoTransferRestrictable` / `validateCardanoTransfer`

2024-05-15 15:21 UTC, tureck1y submitted a review, later dismissed

2024-05-15 17:56 UTC, dbaturin requested changes
Если честно, разбираться было очень трудно из-за плохой структуры. Ошибки оттуда же растут. Может переделать это, опираясь на реализацию в Андроиде? Там гораздо понятнее всё получилось - https://github.com/tangem/blockchain-sdk-kotlin/pull/611/files#diff-c1d7450a88da5a3dad513ad69528b2ca5f908e5a7740697559609f805e10e79d

2024-05-15 17:56 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let minChange = try minChange()
Почему здесь не исключаем текущий токен, если его баланса не осталось? Ведь мы дойдём сюда, если есть другие токены.

2024-05-15 17:56 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            throw ValidationError.cardanoHasTokens(minimumAmount: minChange)
А здесь мы кинем экспепшн наоборот, только если есть другие токены.

2024-05-15 17:56 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let change = adaBalance - minAdaDecimal
Было сложно понять, что тут происходит из-за названия minAdaDecimal. Может minAdaToSendDecimal лучше?

2024-05-15 17:56 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            throw ValidationError.cardanoInsufficientBalanceToSendToken
Тут не понятно, почему другая ошибка, а не та, что выше.

2024-05-15 18:05 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +    private func validateCardanoCoinWithdrawal(amount: Amount, fee: Amount, hasAnotherTokenWithBalance: Bool) throws {
Публичную функцию переименовал, а приватные остались с "Withdrawal". Немного странно, хоть и не пренципиально

2024-05-16 15:53 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            throw ValidationError.cardanoInsufficientBalanceToSendToken
Согласен, упростил, теперь везде `ValidationError.cardanoInsufficientBalanceToSendToken`

2024-05-16 15:54 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        let change = adaBalance - minAdaDecimal
✅

2024-05-16 15:54 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            throw ValidationError.cardanoHasTokens(minimumAmount: minChange)
Согласен, упростил, теперь везде `ValidationError.cardanoInsufficientBalanceToSendToken` ✅

2024-05-16 15:56 UTC, Balashov152 commented
> Если честно, разбираться было очень трудно из-за плохой структуры. Ошибки оттуда же растут. Может переделать это, опираясь на реализацию в Андроиде? Там гораздо понятнее всё получилось - https://github.com/tangem/blockchain-sdk-kotlin/pull/611/files#diff-c1d7450a88da5a3dad513ad69528b2ca5f908e5a7740697559609f805e10e79d

Согласен, чет намудрил больше чем нужно. Теперь метод `validateCardanoTokenWithdrawal` более понятный стал, и добавил комментов заодно

2024-05-16 15:58 UTC, tureck1y submitted a review, later dismissed

2024-05-16 18:55 UTC, dbaturin submitted a review, later dismissed
Вроде всё ок, стало заметно проще разбираться

2024-05-16 18:55 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            change -= fee.value
Не понятно, зачем проверка, ведь мы уже с коинами работаем

2024-05-16 18:55 UTC, dbaturin commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        throw ValidationError.cardanoInsufficientBalanceToSendToken
Странновато выглядит, что throw является дефолтным поведением. С коинами обратная реализация и выглядит гораздо лучше.

2024-05-16 19:07 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +            change -= fee.value
на всякий случай )

2024-05-17 07:21 UTC, fedorov-d approved these changes, later dismissed

2024-05-17 08:32 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        throw ValidationError.cardanoInsufficientBalanceToSendToken
Согласен с Денисом, что странно получается. Давай лучше вот так
```suggestion
        if 0 < change, change < minChange.value {
            throw ValidationError.cardanoInsufficientBalanceToSendToken
        }
```

кстати, может проверка должна быть 
``` swift
    if change < 0 || change < minChange.value {
        throw ValidationError.cardanoInsufficientBalanceToSendToken
    }
```

2024-05-17 12:30 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cardano/CardanoWalletManager.swift
> +        throw ValidationError.cardanoInsufficientBalanceToSendToken
Обновил на `if`. Не тут правильная проверка, что сдача "есть" и что она "больше чем минимум"

2024-05-17 12:31 UTC, Andoran90 submitted a review, later dismissed

2024-05-17 13:31 UTC, tureck1y submitted a review, later dismissed

2024-05-17 15:51 UTC, dbaturin submitted a review, later dismissed

2024-05-20 11:27 UTC, fedorov-d submitted a review, later dismissed

2024-05-21 16:19 UTC, Balashov152 commented
@tureck1y @Andoran90 @dbaturin @fedorov-d можете плиз поставить, одно переименование все таки решил сделать, что бы все одинаково было

2024-05-21 16:45 UTC, dbaturin approved these changes

2024-05-21 17:30 UTC, tureck1y approved these changes

2024-05-22 09:13 UTC, fedorov-d approved these changes

2024-05-22 09:13 UTC, Andoran90 approved these changes

2024-05-22 09:14 UTC, merged