IOS-6527 joystream integration
tangem/blockchain-sdk-swift pull request #672
Opened 2024-05-03 10:30 UTC by fedorov-d

Добавлен joystream блокчейн, работа с polkadot подобными адресами (создание, валидация) перенесена в SS58. Вообще для SS58 существует отдельная библиотека, но решил ее не импортить чтобы избежать дублирования, лишних зависимостей и проблем совместимости модулей.

2024-05-03 16:08 UTC, dbaturin approved these changes

2024-05-03 16:17 UTC, dbaturin requested changes

2024-05-03 16:17 UTC, dbaturin commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +        case .polkadot, .joystream:
Почему деривация как у Польки? Мы же собирались добавить в SLIP-0044 для них coin type и его использовать.

2024-05-06 08:26 UTC, fedorov-d commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +        case .polkadot, .joystream:
поправил, в slip-0044 уже смержено https://github.com/satoshilabs/slips/pull/1723

2024-05-06 10:21 UTC, dbaturin approved these changes, later dismissed

2024-05-08 09:12 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Polkadot/PolkadotNetwork.swift
> +    var addressPrefix: UInt {
Может лучше `UInt8` возвращать, что бы сразу было понятно что это один байт

2024-05-08 09:12 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +             .joystream:
тут надо убрать тогда

2024-05-08 09:12 UTC, Balashov152 commented on BlockchainSdk/Common/SS58.swift
> +        let second = UInt(decodedData[1])
и в этих местах думаю можно UInt8 сделать 

```suggestion
        let first = UInt8(decodedData[0])
        
        guard first >= Constants.rangeLimit else {
            return first
        }
        
        let second = UInt8(decodedData[1])
```

2024-05-08 09:12 UTC, Balashov152 commented on BlockchainSdkTests/Common/SS58Tests.swift
> +final class SS58Tests: XCTestCase {
👍

2024-05-08 09:48 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Polkadot/PolkadotNetwork.swift
> +    var addressPrefix: UInt {
могут быть большие числа, см. https://github.com/paritytech/ss58-registry/blob/main/ss58-registry.json поле 'prefix', можно, наверное, UInt16, но особо не вижу смысла.

2024-05-08 09:51 UTC, fedorov-d commented on BlockchainSdk/Common/SS58.swift
> +        let second = UInt(decodedData[1])
возвращаемое значение может быть больше разрядности UInt8, ниже есть битовые операции, которые могут генерить как раз большие числа, в них придется все равно добавлять конвертацию, так что не вижу смысла.

2024-05-08 09:54 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +             .joystream:
@tureck1y  просил оставить и создать задачу, задача вот https://tangem.atlassian.net/browse/IOS-6793

2024-05-08 17:14 UTC, tureck1y commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +             .joystream:
Лучше задачу в тудушке писать сразу

2024-05-08 17:22 UTC, tureck1y commented on BlockchainSdkTests/Common/SS58Tests.swift
> +    func testGenerateAddresses() {
Нужны бы еще тесты на попытку создать адрес из других ключей, например secp256k1

2024-05-08 17:22 UTC, tureck1y commented on BlockchainSdk/Common/SS58.swift
> +public extension Data {
Либо это должно лежать в Data+, но не паблик, а internal, либо тут как fileprivate. Public без необходимости лучше не делать, чтобы не плодить возможные конфликты

2024-05-08 17:22 UTC, tureck1y commented on BlockchainSdk/Common/SS58.swift
> +enum SS58 {
лучше бы сделать просто структуру с конструктором и избавиться от статики, чтобы был консистентный подход со многими другими утилитками

2024-05-13 09:29 UTC, skibinalexander commented on BlockchainSdk/Common/SS58.swift
> +struct SS58 {
А у WalletCore нет ничего подобного?

2024-05-13 09:31 UTC, skibinalexander commented on BlockchainSdkTests/Common/SS58Tests.swift
> +    func testNetworkTypesFromAddresses() {
Для try делаем 
func testNetworkTypesFromAddresses() throws

2024-05-13 09:47 UTC, skibinalexander commented
@fedorov-d от меня все

2024-05-13 09:56 UTC, fedorov-d commented on BlockchainSdk/Common/SS58.swift
> +struct SS58 {
в walletcore реализация ограничена polkadot и kusama

2024-05-13 11:49 UTC, fedorov-d commented on BlockchainSdkTests/Common/SS58Tests.swift
> +    func testGenerateAddresses() {
добавил в AddressTests

2024-05-13 15:36 UTC, Balashov152 commented on BlockchainSdk/Common/SS58.swift
> +        let second = UInt(decodedData[1])
окей)

2024-05-13 15:36 UTC, Balashov152 approved these changes

2024-05-13 16:25 UTC, tureck1y approved these changes

2024-05-13 17:56 UTC, dbaturin approved these changes

2024-05-14 03:05 UTC, megakoko approved these changes

2024-05-14 03:05 UTC, megakoko commented on BlockchainSdkTests/Common/SS58Tests.swift
> +    }
NP: может захардкоженные значения заменить на PolkadotNetwork.addressPrefix? И что за cess?

2024-05-14 07:13 UTC, fedorov-d commented on BlockchainSdkTests/Common/SS58Tests.swift
> +    }
заменить можно, но мне кажется в тестах лучше не закладываться на лишнюю логику, cess это какой-то блокчейн, который мы не поддерживаем, добавлен чтобы покрыть кейс с большим значением type

2024-05-14 07:46 UTC, merged