Feature/ios 4772 ton address service
tangem/blockchain-sdk-swift pull request #690
Opened 2024-05-19 14:38 UTC by fedorov-d

добавлен TonAddressService, надо обновить ревизию после мерджа https://github.com/tangem/wallet-core-binaries-ios/pull/10

2024-05-19 20:05 UTC, skibinalexander commented
Тесты упали, надо глянуть, упали прям в тоне

2024-05-20 09:39 UTC, tureck1y requested changes
Не хватает тестов на генерацию и валидацию старых и новых форматов адресов. Старые наверное покрыты, надо проверить, что точно идут через новый сервис, а новые надо добавить

2024-05-20 13:54 UTC, fedorov-d commented
> Не хватает тестов на генерацию и валидацию старых и новых форматов адресов. Старые наверное покрыты, надо проверить, что точно идут через новый сервис, а новые надо добавить

добавил тесты для нового формата, поправил где падало

2024-05-20 14:57 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
- мы старые адреса в интерфейсе не будем показывать?
- старый и новый форматы совместимы? Балансы со старого будет видно в новом?

2024-05-21 06:38 UTC, fedorov-d commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
насколько я понял суть задачи как раз сводится к тому чтобы показывать новые адреса вместо старых на UI. не совсем понял вопрос насчет совместимости, но если перейти в эксплорер по старому адресу у которого на балансе будет какая-то сумма - эксплорер покажет уже новый адрес.

2024-05-21 06:54 UTC, skibinalexander commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
> насколько я понял суть задачи как раз сводится к тому чтобы показывать новые адреса вместо старых на UI. не совсем понял вопрос насчет совместимости, но если перейти в эксплорер по старому адресу у которого на балансе будет какая-то сумма - эксплорер покажет уже новый адрес.

По идее адреса должны быть совместимы, и баланс должен быть одинаковый

2024-05-21 10:30 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
Я просто думал что мы оба адреса будет в UI поддерживать для совместимости. В этом вообще есть смысл? Просто если старых адресов не будет, то и тесты на старые адреса не нужны больше.

2024-05-21 10:36 UTC, tureck1y commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
Денис сказал старые не нужны, тогда давай тесты дропнем

2024-05-21 11:03 UTC, fedorov-d commented on BlockchainSdkTests/Common/AddressTests.swift
> +        let oldAddressService = WalletCoreAddressService(coin: .ton)
готово

2024-05-21 11:19 UTC, m3g0byt3 approved these changes, later dismissed

2024-05-21 11:19 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/TON/TONAddressService.swift
> +            throw WalletCoreAddressService.TWError.makeAddressFailed
nit: немного странно кидать эту ошибку, это же не WalletCoreAddressService.
Можно подумать над неймингом/локацией TWError, чтобы юзать ее и в WalletCoreAddressService и TonAddressService и в других будущих местах

2024-05-21 12:14 UTC, tureck1y approved these changes, later dismissed

2024-05-21 13:10 UTC, tureck1y approved these changes

2024-05-21 14:59 UTC, dbaturin approved these changes

2024-05-21 14:59 UTC, dbaturin commented on BlockchainSdkTests/VectorTests/AddressesValidationTests.swift
>              let addressValidator = AddressServiceFactory(blockchain: blockchain).makeAddressService()
Это точно правильно? Получится 2 одинаковых валидатора для Тона. Хотя Wallet Core в основе нового и лежит... В общем, просто странновато как-то

2024-05-21 15:03 UTC, fedorov-d commented on BlockchainSdkTests/VectorTests/AddressesValidationTests.swift
>              let addressValidator = AddressServiceFactory(blockchain: blockchain).makeAddressService()
это тесты, я честно говоря не придумал ничего лучше, если есть идеи - велкам

2024-05-21 15:05 UTC, tureck1y commented on BlockchainSdkTests/VectorTests/AddressesValidationTests.swift
>              let addressValidator = AddressServiceFactory(blockchain: blockchain).makeAddressService()
Мы будем эти тесты рефачить. Плюс я все же надеюсь мы или сами добавим новые адреса в репу траста, либо они добавят и это все уйдет

2024-05-23 09:44 UTC, m3g0byt3 approved these changes

2024-05-23 11:09 UTC, skibinalexander approved these changes

2024-05-23 11:34 UTC, merged