IOS-6909: [KOINOS] TransactionBuilder
tangem/blockchain-sdk-swift pull request #692
Opened 2024-05-22 09:42 UTC by amuraveinik

[IOS-6909](https://tangem.atlassian.net/browse/IOS-6909)

[Android PR](https://github.com/tangem/blockchain-sdk-kotlin/pull/573/files#diff-bd461c2fb1579ebdb5b329a3d42571420915f72e96658c698536ec6992500fa0)

[IOS-6909]: https://tangem.atlassian.net/browse/IOS-6909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-23 16:19 UTC, tureck1y requested changes

2024-05-23 16:19 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +            case diskStorageUsed = "disk_storage_used"
Может заюзать декодер с keyDecodingStrategy = .convertFromSnakeCase?

2024-05-23 16:19 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let amountSatoshi = (amount * satoshi).uint64Value
c uint64Value у Decimal есть нюанс - вернется 0, если число дробное, сначала надо округлять, например params.manaLimit.roundedDecimalNumber.uint64Value

2024-05-23 16:19 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +            $0.chainID = chainId.base64UrlDecodedData()!
лучше без force unwrap, можно кидать WalletError.failedToBuildTx

2024-05-24 06:56 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +    private let transactionIdPrefix = "0x1220"
что-то какой-то разнобой, сложи, пожалуйста, все `private let` вместе, а следом `private var`, чтобы поля были вместе, рассчитываемые свойства вместе были

2024-05-24 06:56 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +    func base64UrlEncodedString() -> String {
обсуждали, не помню где-то была у нас пометка, но аббревиатуры заглавными пишем `base64URLEncodedString()`, `base64URLToBase64()` и `base64URLDecodedData()`

2024-05-24 06:56 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +    func buildForSend(transaction: KoinosProtocol.Transaction, normalizedSignature: Data) throws -> KoinosProtocol.Transaction  {
думаю можно убрать, т.к. нигде ничего не выбрасывает ошибку
```suggestion
    func buildForSend(transaction: KoinosProtocol.Transaction, normalizedSignature: Data) -> KoinosProtocol.Transaction  {
```

2024-05-27 15:37 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +            case diskStorageUsed = "disk_storage_used"
Именно здесь - да, подходит, я тоже об этом думал.
Но для других структур, например для EventData, нейминг в json не совпадает с названием поля в структуре, поэтому для консистентности оставил ключи декодирования везде

2024-05-27 17:00 UTC, tureck1y approved these changes

2024-05-28 12:39 UTC, dbaturin approved these changes

2024-05-29 03:11 UTC, megakoko commented
@skibinalexander посмотри вместо меня пожалуйста, ты уже соседний МР проревьювил

2024-05-29 17:06 UTC, skibinalexander approved these changes

2024-05-30 07:54 UTC, Andoran90 approved these changes

2024-05-30 07:55 UTC, merged