IOS-6949: [KOINOS] WalletManager
tangem/blockchain-sdk-swift pull request #703
Opened 2024-06-04 13:00 UTC by amuraveinik

[IOS-6949](https://tangem.atlassian.net/browse/IOS-6949)

2024-06-05 13:12 UTC, tureck1y requested changes

2024-06-05 13:12 UTC, tureck1y commented on BlockchainSdk/Common/Amount.swift
> +    public var maxValue: Decimal?
Давай это тоже положим внутрь feeResource, к amount это все же не имеет отношения, а может это тут вообще не нужно? Amount есть amount, это просто обертка над value, тут не может быть логики

2024-06-05 13:12 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +        let currentMana = wallet.amounts[.feeResource(name: "Mana")]?.value ?? .zero
Давай "Mana" в константу закинем

2024-06-05 13:12 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +        let currentMana = wallet.amounts[.feeResource(name: "Mana")]?.value ?? .zero
И валидацию сделаем по аналогии с DustRestrictable и прочими в файле TransactionValidator

2024-06-06 09:19 UTC, amuraveinik commented on BlockchainSdk/Common/Amount.swift
> +    public var maxValue: Decimal?
Ага, `amounts[.feeResource].maxValue` всегда равено `amounts[.coin].value`, так что maxValue действительно можно выпилить

2024-06-06 14:10 UTC, tureck1y requested changes

2024-06-07 06:37 UTC, Andoran90 commented on BlockchainSdk/Common/FeePaidCurrency.swift
> +    case feeResource(currency: String)
думаю тут должно быть так:
``` swift
    case feeResource(type: FeeResourceType)
```

2024-06-07 06:37 UTC, Andoran90 commented on BlockchainSdk/Common/Amount.swift
> +    }
а нам точно стоит класть это сюда? кажется более правильное место `Fee`, кажется хранить там это будет более валидно

2024-06-07 06:37 UTC, Andoran90 commented on BlockchainSdk/Common/Blockchain.swift
> +            return .feeResource(currency: "Mana")
надо убрать этот хардкод и брать из `FeeResourceType`

2024-06-07 06:37 UTC, Andoran90 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        let currentFeeResource = wallet.amounts[.feeResource(feeResourceType)]?.value ?? .zero
нужен небольшой ликбез...
откуда в кошельке появится мана? сейчас в `KoinosWalletManager` нет загрузки и добавления количества маны, получается тут все время будет браться 0.
Как будто стоит сделать внутри `Wallet` отдельное хранилище для таких ресурсов и не смешивать их с `Amount`
@tureck1y тебе не кажется, что это не очень хорошая идея мешать `Amount` с `FeeResourse`?

2024-06-07 06:37 UTC, Andoran90 commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +    func testTransactionValidationTest_amount_exceeds_mana_balance() {
картина маслом:
Змеи гонятся за верблюдом

давай все в одном стиле и можно поменять префикс на `testTxValidation...` нет смысла дублировать `Test`.

2024-06-07 09:14 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        let currentFeeResource = wallet.amounts[.feeResource(feeResourceType)]?.value ?? .zero
Обсуждали с Андроидом и Батуриным, решение норм, с заделом под другие сети с похожими нюансами. По сути мана это обычный токен для фи, но без контракта.

2024-06-07 09:14 UTC, tureck1y commented on BlockchainSdk/Common/Amount.swift
> +    }
Да отдельным файлом положить и все

2024-06-07 09:16 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        let currentFeeResource = wallet.amounts[.feeResource(feeResourceType)]?.value ?? .zero
где-то загрузка должна же быть, она есть? @amuraveinik

2024-06-10 06:15 UTC, skibinalexander commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +final class KoinosWalletManagerTests: XCTestCase {
Тут не очень понял, тесты на сборку транзакции и адреса еще будут ?

2024-06-10 07:41 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +private extension Amount {
В ином случае будет куча бойлерплейта

2024-06-10 07:43 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +final class KoinosWalletManagerTests: XCTestCase {
Нет, тут пока только тесты на валидацию.
Тесты на сборку транзакций и на адреса лежать соседними файликами в той же директории

2024-06-10 07:56 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        let currentFeeResource = wallet.amounts[.feeResource(feeResourceType)]?.value ?? .zero
Верно подмечено, потерял кусо логики по дороге. 
Добавил override func update в WalletManager, там сеттятся значения.
Спасибо!

2024-06-10 07:58 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +private extension Amount {
В целом можно, но пока не понимаю зачем, это же все равно fileprivate extension

2024-06-11 07:46 UTC, tureck1y approved these changes, later dismissed

2024-06-11 18:21 UTC, dbaturin submitted a review, later dismissed

2024-06-11 18:21 UTC, dbaturin commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +            try validate(amount: transaction.amount, fee: transaction.fee)
Мы вроде нигде не делаем валидацию при сенде, она раньше вызывается. Это точно тут нужно?

2024-06-11 18:21 UTC, dbaturin commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        }
Первый кейс как-будто лишний, попадёт в третий, а ошибка как-будто неправильная получается.

2024-06-12 08:28 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        }
В целом, звучит логично. 
currentFeeResource всегда будет меньше баланса.

Делал по аналогии с андроидом
https://github.com/tangem/blockchain-sdk-kotlin/blob/8661f92744a74f3696f9d3789cfe4963cb932198/blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosWalletManager.kt#L86

@dbaturin @MasterBin давайте договоримя как сделаем в итоге, чтобы было одинаково на обеих платформах

2024-06-12 08:30 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +            try validate(amount: transaction.amount, fee: transaction.fee)
Тут тоже делал по аналогии с андроидом
https://github.com/tangem/blockchain-sdk-kotlin/blob/8661f92744a74f3696f9d3789cfe4963cb932198/blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosWalletManager.kt#L104

Но если у нас валидация где-то в более раннем шаге происходит, то уберу.
@tureck1y Подскажи пожалуйста

2024-06-14 09:35 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +            try validate(amount: transaction.amount, fee: transaction.fee)
Да, тут не нужна валидация

2024-06-14 09:39 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        }
Тут отрефакторить нужно, созвонимся отдельно

2024-06-14 10:27 UTC, MasterBin commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        }
Проверки все правильные. Не уверен правда, что сами ошибки ок, в андроиде я кастомные сделал. Вот тут расписал все эти три кейса AND-6448

2024-06-14 10:30 UTC, MasterBin commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +        }
Первый кейс - отдельная ошибка, потому что в этом случае клиент вообще не сможет отправить средства и ему надо блокировать перевод, в отличие от второго, когда мы его просто просим подождать

2024-06-14 12:35 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +    func validate(amount: Amount, fee: Fee, destination: DestinationType) throws
этот метод не нужен

2024-06-14 12:35 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +    func validate(amount: Amount, fee: Fee, destination: DestinationType) throws {
да я бы оставил async throws тут для единообразия с остальными экстеншенами

2024-06-14 12:35 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
забыл добавить MARK)

2024-06-14 15:18 UTC, tureck1y submitted a review, later dismissed

2024-06-17 07:07 UTC, skibinalexander submitted a review, later dismissed

2024-06-17 09:40 UTC, Andoran90 approved these changes, later dismissed

2024-06-17 10:45 UTC, Balashov152 requested changes

2024-06-17 10:45 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Cosmos/CosmosWalletManager.swift
> +                            throw WalletError.failedToGetFee
Лучше)
```suggestion
                            throw BlockchainSdkError.notImplemented
```

2024-06-17 10:45 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +            }
Как будто это можно сделать первым условием, на 17 строке

2024-06-17 10:45 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        let maxFeeResource = wallet.amounts[amount.type]?.value ?? .zero
По коду это получается просто баланс того что отправляем ?
Лучше бы тогда так)
```suggestion
        guard let balance = wallet.amounts[amount.type]?.value else {
            throw ValidationError.balanceNotFound
        }
```

P.S: если это так принято называть в сети, то можно и так оставить, пофиг

2024-06-17 10:45 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/TransactionValidator.swift
> +}
Тут надо скопировать с `DustRestrictable`. Так как не везде еще используется async валиация.

там два метода, оба обязательны

```suggestion
extension TransactionValidator where Self: FeeResourceRestrictable {
    func validate(amount: Amount, fee: Fee, destination: DestinationType) async throws {
        Log.debug("TransactionValidator \(self) doesn't checking destination. If you want it, make our own implementation")
        try validate(amount: amount, fee: fee)
    }
    
    func validate(amount: Amount, fee: Fee) throws {
        try validateAmounts(amount: amount, fee: fee.amount)
        try validateFeeResource(amount: amount, fee: fee.amount)
    }
}
```

2024-06-17 10:45 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +    func validateFeeResource(amount: Amount, fee: Amount) async throws
`async` не нужен здесь 
 ```suggestion
    func validateFeeResource(amount: Amount, fee: Amount) throws
```

2024-06-17 14:38 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +    func validateFeeResource(amount: Amount, fee: Amount) async throws
https://github.com/tangem/blockchain-sdk-swift/pull/703#discussion_r1639754878

Я в замешательстве. Как в итоге?

2024-06-17 14:43 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        let maxFeeResource = wallet.amounts[amount.type]?.value ?? .zero
Мы отправляем KOIN, в качестве комиссии используем MANA

currentFeeResource - MANA
maxFeeResource - MANA, но это число равно количеству KOIN в кошельке

Это можно было бы назвать `balance`, но семантически это используется именно в качестве максимального количества `feeResource`, так что я бы оставил нейминг

2024-06-17 14:48 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +    func validateFeeResource(amount: Amount, fee: Amount) async throws
А, это другое

2024-06-17 17:55 UTC, tureck1y approved these changes

2024-06-17 18:05 UTC, Balashov152 approved these changes

2024-06-17 18:06 UTC, Balashov152 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +    func validateFeeResource(amount: Amount, fee: Amount) async throws
`async` нужен только для `async` кода, запросы, делеи ))
а тут же все синхронно выполняется

2024-06-18 07:09 UTC, skibinalexander approved these changes

2024-06-18 07:59 UTC, Andoran90 approved these changes

2024-06-18 08:56 UTC, merged