IOS-6965 ton transaction build
tangem/blockchain-sdk-swift pull request #704
Opened 2024-06-05 07:02 UTC by fedorov-d

Сборка транзакций для токенов тона. Для сборки нужен адрес для жетон волета, дергается отдельным запросом.

2024-06-05 07:04 UTC, fedorov-d commented on BlockchainSdk.xcodeproj/project.pbxproj
> +				version = "4.0.21-tangem6";
пришлось допилить воллеткор для подписи жетон трансферов

2024-06-05 07:06 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONNetworkService.swift
> +                return address.toString(bounceable: false)
перепутал в прошлом пр, везде должны быть не bounceable адреса

2024-06-05 07:08 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONProvider/TONProvider.swift
здесь убрал private для getWalletAddress чтобы можно было дергать отдельно, остальное перестановка местами и добавление доки.

2024-06-05 07:10 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        amountValue: Decimal,
Amount целиком не использовался, только его value

2024-06-05 07:12 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +    private func getWalletAddressIfNeeded(
хелпер чтобы дергать запрос только для токенов

2024-06-05 10:57 UTC, tureck1y approved these changes, later dismissed

2024-06-05 12:36 UTC, skibinalexander approved these changes, later dismissed

2024-06-05 12:36 UTC, skibinalexander commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.forwardAmount = 1 // set according to WalletCore docs
точно нужно ?

2024-06-05 12:46 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.forwardAmount = 1 // set according to WalletCore docs
да, согласовали с @dbaturin

2024-06-05 13:00 UTC, tureck1y approved these changes, later dismissed

2024-06-05 14:22 UTC, dbaturin requested changes

2024-06-05 14:22 UTC, dbaturin commented on BlockchainSdk/Blockchains/TON/TONNetworkService.swift
>                  provider.getWalledData(walletAddress: walletAddress)
Здесь тоже предлагаю уточнить, что get**Jetton**Walle**t**Data (внимание на опечатку). Что-то в PR с network не обратил внимание.

2024-06-05 14:22 UTC, dbaturin commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.forwardAmount = 1 // set according to WalletCore docs
Хотелось бы в комменте указать: needs some amount to send "jetton transfer notification", use minimum

2024-06-05 14:22 UTC, dbaturin commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        let tonTransferAmountValue: Decimal = 0.05 // discussed and agreed with dbaturin
Мне кажется, что странно ссылаться на меня в комментах, да и понимания это не даёт. Здесь хотелось бы видеть, что-то вроде "used to cover token transfer fees, commonly used value after TON fee reduction, actual costs now are ~10 times less, excess is returned"

Вообще это надо бы константой сделать, так и просто красивее будет, так её ещё и при получении фи нужно приплюсовывать, а то, получается, что мы это не учитываем. Пока дёшево и фи округляем в вверх, может и влезать даже, но вообще учесть надо.

2024-06-06 08:18 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +                walletManager.getWalletAddressIfNeeded(
добавил кеш

2024-06-06 08:19 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONNetworkService.swift
> +    func getWalletAddress(for ownerAddress: String, token: Token) -> AnyPublisher<String, Error> {
добавил слово Jetton

2024-06-06 08:19 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONNetworkService.swift
>                  provider.getWalledData(walletAddress: walletAddress)
также поправил

2024-06-06 08:19 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.forwardAmount = 1 // set according to WalletCore docs
обновил комент

2024-06-06 08:20 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        let tonTransferAmountValue: Decimal = 0.05 // discussed and agreed with dbaturin
обновил комент, перенес значение в константы, использовал это значение для вычисления fee

2024-06-06 09:01 UTC, skibinalexander submitted a review, later dismissed

2024-06-06 11:42 UTC, dbaturin submitted a review, later dismissed

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONNetworkService.swift
> +                )
nit:
```suggestion
                let reader = TupleReader(items: response.stack)
```

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +    ) throws -> TheOpenNetworkSigningInput {
А давай лучше переделаем что бы полную тарнзакцию передавать
```suggestion
    public func buildForSign(transaction: Transaction) throws -> TheOpenNetworkSigningInput {
```
И уже из нее все брать, плюс адрес ты можешь взять из `self.wallet.defaultAdress`
Можешь глянуть как `EthereumTransactionBuilder` или `CardanoTransactionBuilder` сделано

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.amount = ((amountValue * wallet.blockchain.decimalValue) as NSDecimalNumber).uint64Value
Можно так, есть extension под это 
```suggestion
            $0.amount = (amountValue * wallet.blockchain.decimalValue).uint64Value
```

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        }
что то не понятно, точно ок 
destination - не используется, 
walletAddress это же тоже самое что и wallet.address должно быть ?
на 145 строке передается адрес нашего кошелька как адреса `destination `
как будто все перепутано

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        }
аа, может тогда не walletAdress, а jetonAddress или как то так. А то не понятно

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +    private var jettonWalletAddressCache = [Token: String]()
nit, как будто по гайдлайнам так не пишем )
```suggestion
    private var jettonWalletAddressCache: [Token: String] = [:]
```

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +            }
Лучше без Just() тогда, раз можно сразу с подписки начинать 
```suggestion
         getJettonWalletAddressIfNeeded(
               for: transaction.sourceAddress,
               transactionType: transaction.amount.type
          )
```

2024-06-06 13:58 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +            }
```suggestion
        getJettonWalletAddressIfNeeded(
                    transactionType: amount.type
                )
```

2024-06-06 14:02 UTC, tureck1y commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.amount = ((amountValue * wallet.blockchain.decimalValue) as NSDecimalNumber).uint64Value
округление надо добавить тут? Иначе при дробном значении можем получить 0

2024-06-06 14:05 UTC, tureck1y reviewed
👀

2024-06-06 14:24 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +    ) throws -> TheOpenNetworkSigningInput {
тут нужен именно jettonWallet адрес, его надо снаружи пробрасывать, переименую для ясности

2024-06-06 14:54 UTC, Balashov152 commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.amount = ((amountValue * wallet.blockchain.decimalValue) as NSDecimalNumber).uint64Value
ну вообще не должно быть дробного, при умножении на `decimalValue` должно целочисленное получается )

2024-06-06 14:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +            }
поправил

2024-06-06 14:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +            }
поправил

2024-06-06 14:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONWalletManager.swift
> +    private var jettonWalletAddressCache = [Token: String]()
поправил

2024-06-06 14:55 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +            $0.amount = ((amountValue * wallet.blockchain.decimalValue) as NSDecimalNumber).uint64Value
поправил

2024-06-06 14:55 UTC, fedorov-d commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        }
переименовал и дописал комент

2024-06-06 14:56 UTC, Balashov152 approved these changes, later dismissed

2024-06-06 15:01 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/PolkadotNetwork.swift
> +            return Amount(with: .kusama(curve: curve), value: Decimal(stringValue: "0.000333333333")!)
а это почему сюда попало?

2024-06-06 15:32 UTC, skibinalexander approved these changes

2024-06-06 15:52 UTC, dbaturin approved these changes

2024-06-06 15:55 UTC, Balashov152 approved these changes

2024-06-06 15:55 UTC, tureck1y approved these changes

2024-06-06 15:55 UTC, merged