IOS-6758: [KOINOS] Implement KoinosWalletAssembly
tangem/blockchain-sdk-swift pull request #707
Opened 2024-06-06 18:33 UTC by amuraveinik

[IOS-6758](https://tangem.atlassian.net/browse/IOS-6758)

[Android KoinosWalletManagerAssembly](https://github.com/tangem/blockchain-sdk-kotlin/blob/8661f92744a74f3696f9d3789cfe4963cb932198/blockchain/src/main/java/com/tangem/blockchain/common/assembly/impl/KoinosWalletManagerAssembly.kt)

Таргет бранчем поставил свой предыдущий PR чтобы корректно отображался дифф

[IOS-6758]: https://tangem.atlassian.net/browse/IOS-6758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-07 09:46 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Каинос на secp256k1. Нужно ли принудительно сжимать ключи? На старых картах они приходят разжатые. Умеет ли коинос вообще работать с разжатыми? @dbaturin

2024-06-07 09:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Не знаю, умеет ли, но лучше сжимать, мне кажется. Как минимум, для однообразия

2024-06-11 07:50 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Посмотри плиз для примера на Радиант, там в ассемблируйте есть сжатие

`let publicKey = try Secp256k1Key(with: input.wallet.publicKey.blockchainKey).compress()`

Нужно проверить, что и в адрес сервисе такой код есть и сказать об этом андроид платформе, если у них не сделано

2024-06-11 09:11 UTC, MasterBin commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Кто-то мне на ревью сказал, что от карты и так приходит compressed, но согласен, лучше добавить для страховки

2024-06-11 12:15 UTC, m3g0byt3 approved these changes, later dismissed

2024-06-11 15:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
@MasterBin Для старых карт приходит разжатый. Для новых - воллеты и новее - сжатый

2024-06-11 15:28 UTC, tureck1y requested changes

2024-06-11 15:28 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosAddressService.swift
> +        return try bitcoinLegacyAddressService.makeAddress(for: compressedPublicKey, with: addressType)
Можно проще. Ниже пример на основе BitcoinCashAddressService

let compressedKey = try Secp256k1Key(with: publicKey.blockchainKey).compress()
return try bitcoinLegacyAddressService.makeAddress(from: compressedKey)

2024-06-11 15:28 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +        let compressedPublicKey: Wallet.PublicKey
Сжимаем в AddressService и TransactionBuilder. В сенде уже нельзя ничего делать категорически, потому что тут идет отправка того, что пользователь заправил и то, что прошло валидацию

2024-06-11 16:01 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                    walletPublicKey: compressedPublicKey
сюда не нужно сжимать, сайнер сам возьмет нужный seedKey

2024-06-13 09:20 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +import TangemSdk
Больше не нужно?

2024-06-13 13:23 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +import TangemSdk
Убрал

2024-06-13 14:51 UTC, tureck1y approved these changes, later dismissed

2024-06-13 14:55 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Все проверено? TransactionBuilder юзает правильный сжатый ключ?

2024-06-13 18:02 UTC, dbaturin submitted a review, later dismissed

2024-06-14 07:09 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletAssembly.swift
> +        let blockchain = input.blockchain
Мы в TransactionBuilder вообще не юзаем ключ, с Никитой синканулся.

На скриншоте ниже то что обсудили - добавить в метод send, [но в этом же PR уже был коммент чтобы не делать так ](https://github.com/tangem/blockchain-sdk-swift/pull/707#discussion_r1635138989)

<img width="607" alt="image" src="https://github.com/tangem/blockchain-sdk-swift/assets/163782033/d64c9719-c707-4227-aa09-8c8881bb162a">

2024-06-17 07:59 UTC, Andoran90 submitted a review, later dismissed

2024-06-18 09:05 UTC, amuraveinik commented
Слетели аппрувы после смены таргет бранча (был в ветку с другой задачей, которая влилась в `blockchains/koinos`)

2024-06-18 09:17 UTC, tureck1y approved these changes

2024-06-18 10:06 UTC, dbaturin approved these changes

2024-06-19 07:52 UTC, Andoran90 approved these changes

2024-06-19 11:11 UTC, m3g0byt3 approved these changes

2024-06-19 11:15 UTC, merged