BSS-179 Adding Solana
tangem/blockchain-sdk-swift pull request #72
Opened 2022-01-20 13:05 UTC by megakoko

2022-01-20 17:50 UTC, tureck1y requested changes

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +            return 9
```suggestion
        case .avalanche, .solana:
            return 9
```

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaDummyAccountStorage.swift
> +//  SolanaDummyAccountStorage.swift
Этот файл нужен? Вроде не используется

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +//  SolanaNetworkService.swift
Лучше всё же сделать как у стеллара (см. StellarSdk+.swift). Комбайновая обертка отдельно, логика отдельно. NetworkService станет чище.

-Лучше везде Future дополнительно в Deferred завернуть
-В StellarSdk+.swift я всю такую обертку переписал на weak, т.к. не не нашел нигде толкового объяснения. Если сможешь найти, будет круто. Ни одного краша не было в этом коде, но в этом случае решил перестраховаться, поэтому лучше сделать единообразно.

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +    private func mapInfo(mainAccountInfo: SolanaMainAccountInfoResponse, tokenAccountsInfo: [TokenAccount<AccountInfoData>]) -> SolanaAccountInfoResponse {
А зачем эту функцию выносить в extension?

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .map { transactionFee, accountCreationFee, accountExists in
[weak self] не хватает

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .flatMap { [unowned self] additionalAmount -> AnyPublisher<Void, Error> in
тут weak должен быть, за хранение в памяти мы не отвечаем в этом случае

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +            .map(self.mapInfo)
[weak self]

2022-01-20 17:50 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .transactionFee(numberOfSignatures: 1)
В каком случае будет не 1?

2022-01-21 05:23 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaDummyAccountStorage.swift
> +//  SolanaDummyAccountStorage.swift
Нужен, передается в Solana SDK, чтобы удовлетворить систему аккаунтов, которая используется внутри.

https://github.com/tangem/blockchain-sdk-swift/blob/853fcaa4b0600862422428a554c47aa585068cb7/BlockchainSdk/Common/WalletManagerFactory.swift#L256

2022-01-21 05:24 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +    private func mapInfo(mainAccountInfo: SolanaMainAccountInfoResponse, tokenAccountsInfo: [TokenAccount<AccountInfoData>]) -> SolanaAccountInfoResponse {
А не знаю, логически пытался разделить класс. Перенес обратно.

2022-01-21 05:30 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .transactionFee(numberOfSignatures: 1)
Не знаю, по крайней мере в наших кейсах всегда 1.

Во внутренностях Solana SDK в общем случае передается массив аккаунтов/сайнеров, плюс в RPC используется наименование lamportsPerSignature, поэтому решил подобно сделать.

2022-01-21 05:45 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .map { transactionFee, accountCreationFee, accountExists in
Исправил

2022-01-21 05:45 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            .flatMap { [unowned self] additionalAmount -> AnyPublisher<Void, Error> in
Исправил

2022-01-21 05:45 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +            .map(self.mapInfo)
Исправил

2022-01-21 06:58 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaNetworkService.swift
> +//  SolanaNetworkService.swift
Вынес комбайн: https://github.com/tangem/blockchain-sdk-swift/blob/BSS-179_adding_solana/BlockchainSdk/WalletManagers/Solana/SolanaSdk%2B.swift

2022-01-21 07:38 UTC, tureck1y approved these changes

2022-01-21 07:48 UTC, lazutkin-andrey approved these changes

2022-01-21 08:30 UTC, merged