IOS-7084: Update adresses for a new blockchains
tangem/blockchain-sdk-swift pull request #723
Opened 2024-06-11 07:51 UTC by amuraveinik

[IOS-7084](https://tangem.atlassian.net/browse/IOS-7084)

Адрес для коиноса добавлен [в соседнем PRе](https://github.com/tangem/blockchain-sdk-swift/pull/722)

2024-06-11 07:53 UTC, fedorov-d requested changes

2024-06-11 07:53 UTC, fedorov-d commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qelzg874tr0zap72ckcc9exa3lgyyt6rvfhhekc"
для легаси адресов комиссия больше, тут нужно будет поставить M-адрес, это я поменяю в рамках отдельной задачи

2024-06-11 15:30 UTC, tureck1y approved these changes

2024-06-11 15:48 UTC, fedorov-d approved these changes

2024-06-13 07:10 UTC, skibinalexander approved these changes

2024-06-13 12:47 UTC, dbaturin approved these changes
В названии "new blockchains", а в PR только Raidant

2024-06-13 12:49 UTC, dbaturin commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "ltc1qelzg874tr0zap72ckcc9exa3lgyyt6rvfhhekc"
По идее, самая низкая комиссия как раз для SegWit адресов, то есть тех, что ltc1.

2024-06-13 13:50 UTC, merged