IOS-7103 Make solana fix for token
tangem/blockchain-sdk-swift pull request #730
Opened 2024-06-13 09:47 UTC by skibinalexander

Было обнаружено 2 проблемы:

1. Запрос получения ренты для токене, должен идти все таки после того, как мы получим инфу об аккаунте
2. Мы не правильно использовали параметр space, мы его брали для main info, а нужно было из token info

При этом, space берется для аккаунта отправителя, поэтому мы его припакапываем на уровне wallet manager

2024-06-13 09:47 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaNetworkService.swift
> +            tokenAccountSpace: tokenAccountsInfo.first?.account.space
В андроиде почему то возвращается не массив , а один параметр, поэтому имел смелость сделать через first

2024-06-13 09:48 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaResponse.swift
>      let mainAccountSpace: UInt64?
Общая модель из networkService просто добавил параметр

2024-06-13 09:48 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> +    private var currentTokenAccountSpace: UInt64?
То самое припакапываемое значение

2024-06-13 09:49 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> +        return Publishers.Zip(accountExistsPublisher, rentExemptionBalancePublisher)
Сделал запрос получение существование акканута и ренты в одном паблишере, а расчет фи ренты дальше по цепочке для лучшего понимая флоу как это должно происходить

2024-06-13 11:24 UTC, tureck1y approved these changes, later dismissed

2024-06-13 17:22 UTC, dbaturin requested changes

2024-06-13 17:22 UTC, dbaturin commented on BlockchainSdk/Blockchains/Solana/SolanaNetworkService.swift
> +            tokenAccountSpace: tokenAccountsInfo.first?.account.space
Что-то не то получилось. В Андроиде мы запрашиваем этот tokenAccountSpace для конкретного токена когда фи запрашиваем и транзакцию строим.

2024-06-14 13:44 UTC, dbaturin approved these changes

2024-06-14 15:19 UTC, tureck1y approved these changes

2024-06-18 09:10 UTC, skibinalexander commented
+ Мистер Сон, потому что Дима в отпуске

2024-06-18 09:11 UTC, Balashov152 approved these changes

2024-06-18 09:11 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Solana/SolanaWalletManager.swift
> +                let rentExemption = values.1
nit просто на будущее )

```suggestion
                let (accountExistsInfo, rentExemption) = values
```

2024-06-18 09:22 UTC, tureck1y commented
Тут все готово?

2024-06-18 09:25 UTC, merged