Koinos integration fixes
tangem/blockchain-sdk-swift pull request #741
Opened 2024-06-20 09:43 UTC by amuraveinik

2024-06-24 19:22 UTC, dbaturin approved these changes, later dismissed

2024-06-25 17:21 UTC, tureck1y requested changes

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
А зачем нужен кастомный декодер?

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosMethod.swift
> +            init(from decoder: any Decoder) throws {
и тут?

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +        init(from decoder: any Decoder) throws {
И здесь? Может лучше маппинг и вариацию вынести куда-то?

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +            .map(JSONRPC.Response<T, NEARNetworkResult.APIError>.self, using: decoder)
Может сразу сделаем норм? Это вроде быстро

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    return WalletError.failedToParseNetworkResponse as Error
as тут точно нужен?

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Blockchains/TON/TONTransactionBuilder.swift
> +        case .coin, .reserve, .feeResource:
какой-то артефакт, ниже уже есть

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/ValidationError.swift
> +    case invalidMaxAmount(validMax: Decimal)
предлагаю сделать что-то типа insufficientFeeResource(availableAmount: Amount), чтобы не конфьюзило с вариацией тотала

2024-06-25 17:21 UTC, tureck1y commented on BlockchainSdk/Common/TransactionHistory/Ethereum/EthereumTransactionHistoryMapper.swift
> +                case .coin, .reserve, .feeResource:
Тут тоже

2024-06-26 09:02 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    return WalletError.failedToParseNetworkResponse as Error
Компилятор сам не смог нормально распознать возвращаемый тип.
Я поменял на `-> Error`

2024-06-26 09:30 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    return WalletError.failedToParseNetworkResponse as Error
ну в таких случаях можно подсказать компилятору, да через  .mapError { moyaError -> Error in, однако не  надо затирать и маппить ошибки вообще нигде, мы прикидываем низкоуровневые ошибки на самый верх

2024-06-26 10:35 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
С апишки прилетают значения в формате String, при том что фактически они числового типа, и мы с ними потом работаем именно как с числами. По моему это самое подходящее место чтобы делать маппинг

2024-06-26 10:35 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosMethod.swift
> +            init(from decoder: any Decoder) throws {
Ответил выше

2024-06-26 10:37 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +        init(from decoder: any Decoder) throws {
Я думаю что это как раз правильное место для маппинга, т.к. сущности в чистом виде как они приходят с апишки нам не пригодятся, и маппер мы переиспользовать тоже не сможем

2024-06-26 10:41 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +        init(from decoder: any Decoder) throws {
Но я открыт к конкретным предложениям

2024-06-26 10:42 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/ValidationError.swift
> +    case invalidMaxAmount(validMax: Decimal)
Поменял на `amountExeedsFeeResourceCapacity`

2024-06-26 10:43 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/ValidationError.swift
> +    case invalidMaxAmount(validMax: Decimal)
С твоим вариантом есть проблема с компилацией, из-за того что нейминг двух кейсов одинаковый.

А так, вроде по смыслу подходит

2024-06-26 11:01 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
Ну вот не уверен, все же сетевая модель должна отражать сетевой ответ. А тут получается в декодинге из json происходит какая-то конвертация. Чище было бы сделать разные модели + маппер на мой взгляд, ну пусть все посмотрят, скажут свое мнение тоже

2024-06-26 11:02 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosMethod.swift
> +            init(from decoder: any Decoder) throws {
Закрою этот конверсейшен, обсудим все в рамках одной ветки тогда

2024-06-26 11:06 UTC, tureck1y requested changes

2024-06-26 11:06 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +    func getKoinBalance(address: String) throws -> AnyPublisher<UInt64, Never> {
Я проглядел сначала, функция throws, но при этом возвращает Паблишер. Видимо нужно убирать throws и делать -> AnyPublisher<UInt64, Error>.

2024-06-26 11:06 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +    func getKoinBalance(address: String) throws -> AnyPublisher<UInt64, Never> {
Остальные функции надо тоже чекнуть

2024-06-26 11:06 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkService.swift
> +            let manaResult: AnyPublisher<UInt64, Never>
И этот момент не очень понимаю. Сетевой запрос же может зафейлится, почему тут Never?

2024-06-26 21:11 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
@skibinalexander @Balashov152 @m3g0byt3 @fedorov-d @Andoran90 Нужно мнение

2024-06-26 21:16 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +    func getKoinBalance(address: String) throws -> AnyPublisher<UInt64, Never> {
Ага, согласен, тут убрал. В остальных местах норм, они без throws

2024-06-26 21:18 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkService.swift
> +            let manaResult: AnyPublisher<UInt64, Never>
Это за счет того что я делаю на паблишере `replaceError` и подсовываю ноль в качестве дефолтного.
С Никитой обсуждали еще на том этапе где я ловил ошибку на запросе баланса когда на адресе не было ни одной транзакции, тогда Никита сказал что по дефолту считаем в таких случаях что возвращается ноль.

Я сейчас вернул сигнатуру с ошибкой, но фактически там ошибки никогда не будет

2024-06-27 11:27 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkService.swift
> +            let manaResult: AnyPublisher<UInt64, Never>
Синканулся с Никитой, при отсутствии баланса не ошибка возвращается, а пустой результат.
Этот кейс уже обрабатывается в нетворк провайдере

2024-06-27 12:01 UTC, tureck1y reviewed
По маппингу ошибок есть вопрос, в остальном от меня ок

2024-06-27 12:01 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
>              }
Я вот про маппинг такого характера говорил. Нет смысла приводить к какой-то конкретной ошибке, лучше пусть в UI отобразится что-то конкретное, проще будет разбираться с саппортом

2024-06-27 14:41 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
>              }
А, понял.
В этом месте откуда-то скопировал.
Уберу тогда

2024-06-28 10:17 UTC, tureck1y submitted a review, later dismissed

2024-06-28 12:22 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
Я за подход с маппером в кейсе, когда есть доменные модели

Два профита:
- В маппере можно еще делать валидацию, обработку опшионалов, склеивание разных моделек
- Когда DTO 1в1 повторяют то, что приходит из сети (и нейминг полей и их типы) - это дает легкость поиска в коде, можно легко сопоставить ответ из сети и код

---

Если доменных моделей нет - то конечно можно маппинг разный делать и в `init(from decoder: any Decoder) throws {`, но кажется отсутствие доменных моделей и жесткая фиксация на формат того, что приходит из сети - не ок


Еще один плюс того,

2024-06-30 22:58 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosChain.swift
> +        init(from decoder: any Decoder) throws {
Вынес маппинг отдельно

2024-06-30 22:58 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/DTO/KoinosProtocol.swift
> +        init(from decoder: any Decoder) throws {
Вынес маппинг отдельно

2024-07-01 11:05 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinContractAbi.swift
> +    init(isTestnet: Bool, decimalCount: Int) {
Больше похоже на структуру, чем класс, логики тут нет. Еще меня немного смущает ABI, Тут же просто набор параметров, предлагаю переименовать, чтобы не путало с evm ABI. Может что-то типа KoinosNetworkParams?

Это то же самое, что и blockchain.decimalValue, можно оттуда брать
satoshiMultiplier = pow(10, decimalCount)

2024-07-01 12:25 UTC, tureck1y submitted a review, later dismissed

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
>              throw WalletError.failedToBuildTx
nit: Может лучше пройтись и возвращать `KoinosTransactionBuilderError`, так будет легче к логах понимать что именно пошло не так, тем более enum уже даже есть

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
а как на счет что бы это перенести в TransasctionBuilder. Сам метод `buildForSend` будет проще, да и подготовку подписи дело как мне лучше в самом билдере делать )

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return try Koinos_Contracts_Token_balance_of_result(serializedData: decodedResult).value
А это не наша сущность ? А то snake_case не используем нигде ж

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return 0
```suggestion
        guard let stringRC = dto.rc, let rc = UInt64(stringRC) else {
            return 0
        }
        
        return rc
```

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +            throw WalletError.failedToParseNetworkResponse
тот же самый Тейк про ошибку, иногда это `KoinosDTOMapperError` а иногда `WalletError`.
Я больше за `KoinosDTOMapperError`

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +            return Fail(error: error).eraseToAnyPublisher()
Тоже вроде как можно сделать через вроде `Result {}.publisher` @tureck1y в EVM так делал, чище получается

2024-07-01 16:20 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +            manaResult.map { Decimal($0) / satoshiMultiplier }
чисто придирка, но если `satoshiMultiplier` в `koinosNetworkParams` нужен только для этого, то я бы эту конвертацию вообще бы в WalletManager сделал, а здесь и в `KoinosNetworkParams` это поле убрал бы

2024-07-02 08:57 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return try Koinos_Contracts_Token_balance_of_result(serializedData: decodedResult).value
Это сгенерированные сущности протобафа

2024-07-02 08:59 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return 0
![image](https://github.com/tangem/blockchain-sdk-swift/assets/163782033/dee5fd2d-f754-48f9-9c7e-7ece1259922e)

2024-07-02 09:00 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return 0
Ну это уже придирка, разницы абсолютно никакой

2024-07-02 09:07 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +            manaResult.map { Decimal($0) / satoshiMultiplier }
Не только здесь, ниже в методе `getRCLimit` тоже используется

2024-07-02 09:09 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return 0
Ну да, просто привычней через `guard`, причем метод выше через `guard` сделан )

2024-07-02 09:11 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +import TangemSdk
Понадобилось когда вынес колдовство с подписью сюда

2024-07-02 09:17 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +        return 0
Сделал тоже через guard для унификации

2024-07-02 09:31 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
Блин, а получится сделать сигнатуру как во всех новых билдерах делаем
```
    func buildForSend(transaction: Transaction, signature: SignatureInfo) throws -> Data
```
Что бы более примитивными данными оперировать, что бы в будущем можно было легко на протокол переделать

2024-07-02 10:04 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +            return Fail(error: error).eraseToAnyPublisher()
Да у нас в целом есть .anyFail

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +                toAccount: decodedEvent.to.base58EncodedString,
А тут норм что base58? 
Где потом юзаются эти поля (я просто не ревьювил остальные пулы)?

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    + Constants.maxComputeLimit * limits.computeBandwidthCost
Тут есть опасность вылезти за пределы uint64?

Сами значения из ручки приходят как инты да, но тут мы их складываем и умножаем

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +}
А это откуда, из доки? Если да - то неплохо бы добавить ссылку и объяснение в коммент, а то сейчас какие-то magic numbers

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
Не понимаю этого условия, amount и fee могут быть совсем разными валютами, разве так корректно сравнивать?
`maxFeeResource` берется по `amount.type`, но сравнивается с `fee.value`, которое имеет `fee.type`, не обязательно равное `amount.type`

Это может работать для конкретного кейса, но некорректно для например эфира, где amount какой-нибудь токен, а fee это ETH
А интерфейс заявлен как универсальный, а не koinos specific

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        if amount.value == maxFeeResource, availableBalanceForTransfer > 0 {
А почему не >= ?
Странно выглядит == для чисел с точкой, Decimal хоть и сохраняет точность, но чтобы получить Decimal - atomic units скорее всего были где-то ранее поделены на 10^decimals и могла набежать ошибка

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdkTests/Koinos/KoinosMethodResponseDecodingTests.swift
> +        .data(using: .utf8)!
nit: вместо форсанврапов в тестах можно юзать XCTUnwrap, будет немного чище

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdkTests/Koinos/KoinosTransactionBuilderTests.swift
> +    private lazy var transactionBuilderTestnet = KoinosTransactionBuilder(koinosNetworkParams: koinContractAbiTestnet)
Все сущности, где потенциально может быть какой-то стейт (tx билдер выглядит как такая сущность) - я бы предложил сетать в `XCTest.setUp()` и убивать в `XCTest.tearDown()`

Чтобы тесты были более атомарными и изолированными

2024-07-02 12:28 UTC, m3g0byt3 commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +    private lazy var walletManager = KoinosWalletManager(
Аналогично комменту выше

2024-07-02 12:33 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let preparedSignature = Data([newV]) + extendedSignature.r + extendedSignature.s
Вообще интересный тейк, как в `EthereumTransactionBuilder:207` идет в конце
но я не стал писать коммент, так как решил что это особенность сети возможно

Если все таки в конце, то можно это отдельным extension сделать для `Secp256k1Signature`

2024-07-02 12:36 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let preparedSignature = Data([newV]) + extendedSignature.r + extendedSignature.s
Если выносить в экстеншн - то заодно можно перейти на этот экстеншн в VeChainTransactionBuilder

Там в `unmarshalledSignature(from:publicKey:hash:)` примерно такая же логика, только нет `+31` (что можно сделать опциональным аргом)

2024-07-02 14:46 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Models/KoinosDTOMapper.swift
> +                toAccount: decodedEvent.to.base58EncodedString,
Да, это особенность коиноса что где-то base58, а где-то base64.
Эта структура вроде как должна было быть использоваться при истории транзакции, делал по аналогии с анлроидом, но в процессе решили не делать, там какая-то проблема

2024-07-02 15:02 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    + Constants.maxComputeLimit * limits.computeBandwidthCost
В идеале тут должен был бы быть BigDecimal, по аналогии с андроидом, но по сути это число потом используется по аналогии с числом баланса, которое должно умещаться в UInt64

2024-07-02 15:03 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +}
Из андроид репо, а Никита брал откуда-то из js либы

2024-07-02 15:07 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
А тут и нет другого способа узнать maxFeeResource. 
Именно в коиносе он равен балансу.
Пока что да, получается что коинос специфичная логика

2024-07-02 15:07 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
@tureck1y @Balashov152 Помогите

2024-07-02 15:10 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        if amount.value == maxFeeResource, availableBalanceForTransfer > 0 {
Это специальный кейс обработки ошибки когда отправляем макс эмаунт. 
Получится что `amount.value` при отправки макс будет равен `wallet.amounts[amount.type]`, который в свою очередь и равен `maxFeeResource`, и тут потерь точности быть не должно, потому что это фактически сравнение с самим собой

2024-07-02 15:13 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosTransactionBuilderTests.swift
> +    private lazy var transactionBuilderTestnet = KoinosTransactionBuilder(koinosNetworkParams: koinContractAbiTestnet)
У транзакшн билдера нет стейта, его функции чистые

2024-07-02 15:16 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosWalletManagerTests.swift
> +    private lazy var walletManager = KoinosWalletManager(
Тут согласен, сделал как предложил

2024-07-02 15:17 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    + Constants.maxComputeLimit * limits.computeBandwidthCost
@tureck1y Нужна помощь, что в таких случаях использовать

2024-07-02 15:18 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
@tureck1y Нужна помощь, не в курсе договоренностей. В последний раз когда обсуждали про пендинг транзакции как раз и решили же так делать

2024-07-02 15:20 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        guard let chainID = koinosNetworkParams.chainID.base64URLDecodedData() else {
Это самописный метод, я добавлял в BSDK в предыдущих пуллреквестах.
Отличие этого метода от дефолтных - тут идет замена символов на ожидаемые (`/` на `_` и другие). 
Это опять таки специфика коиноса, и хоть они действительно не передается в урле, но апишка ожидает в теле JSONRPC запроса именно такое

2024-07-02 15:21 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosNetworkParams.swift
> +    let satoshiMultiplier: Decimal
Убрал отсюда вообще, вроде как по логике оно вообще не относится к KoinosNetworkParams. Вынес в KoinosWalletManager

2024-07-02 15:24 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosTransactionBuilderTests.swift
> +        let publicKey = Wallet.PublicKey(seedKey: Data(), derivationType: nil) // TODO: [KOINOS] What to use here?
@tureck1y Нужна помощь, не знаю что тут надо передавать. 
Эта проблема возникла когда применил изменение по комментам с тем чтобы изменить сигнатуру `buildForSend` и спрятать колдовство над подписями внутрь этой же функции

2024-07-02 15:26 UTC, amuraveinik commented on BlockchainSdkTests/Koinos/KoinosTransactionBuilderTests.swift
>          )
@tureck1y Вот сюда лучше коммент оставлю, чтобы было видно куда публичный ключ передается

2024-07-02 15:35 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let preparedSignature = Data([newV]) + extendedSignature.r + extendedSignature.s
Нет, это особенность коиноса, тут должно быть в конце

2024-07-02 15:36 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
Да, как раз обсуждали что хрупко и лучше бы поискать способ как это делать надежнее, если это возможно.

2024-07-02 15:37 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                    + Constants.maxComputeLimit * limits.computeBandwidthCost
Можно юзать BigUInt

2024-07-02 15:44 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
Насколько я понимаю этот блокчейн и как этот интерфейс задумывал Денис, фи ресурс иначе работать не может. Давайте оставим как есть, если вдруг понадобится заюзать для другого блокчейна, будем думать

2024-07-02 15:54 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
>                  nonce: encodedNextNonce.base64URLEncodedString(),
Аналогично отведу выше, специфика коиноса

2024-07-02 16:05 UTC, tureck1y commented on BlockchainSdkTests/Koinos/KoinosTransactionBuilderTests.swift
> +        let publicKey = Wallet.PublicKey(seedKey: Data(), derivationType: nil) // TODO: [KOINOS] What to use here?
Если рандомно или нулями забить не получается, то можно взять настоящий из AddressTests

2024-07-03 09:44 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
Так и что в итоге тут?
Я вижу в апишке есть нужная ручка `GET /v1/transaction/{transaction_id}`, которую можно дергать в `update()` c хешами pending txs (их мы знаем локально) и далее обрабатывать соответственно

Как пример - можно посмотреть как сделано в `VeChainWalletManager.update(completion:)` и в других сетках

2024-07-03 09:48 UTC, m3g0byt3 commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
Ну как то максимум криво выходит, получается в BSDK шипится нерабочий для 99% сеток (ну кроме как для коиноса) код
Денис может быть не в курсе как работает BSDK, он относительно недавно на фуллтайме

Можно хотя бы ассерт/коммент оставить тут для прочих сеток

2024-07-03 09:48 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +}
Ну видимо можно уточнить у Никиты?

2024-07-03 09:51 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let preparedSignature = Data([newV]) + extendedSignature.r + extendedSignature.s
>это особенность коиноса, тут должно быть в конце

первая часть предложения противоречит второй😀
Я в итоге не понял, как должно быть - видимо все-таки в начале и все ок?

2024-07-03 09:56 UTC, tureck1y commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
Денис стоит у истоков нашего бсдк) Коммент да, давайте добавим, что подразумеваем одинаковый тип фи ресурса и amount на случай использования этого интерфейса другими сетями. Я пока не вижу тут проблем. Просто эта тема с Маной выглядит запутанно, я тоже долго разбирался.

2024-07-03 10:14 UTC, tureck1y submitted a review, later dismissed
Проверил транзакции после доработок?

2024-07-03 10:14 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosNetworkParams.swift
> +//  koinosNetworkParams.swift
NP: KoinosNetworkParams

2024-07-03 10:14 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosTransactionBuilder.swift
> +        let preparedSignature = Data([newV]) + extendedSignature.r + extendedSignature.s
Ахах, да, в начале имел в виду))

2024-07-03 10:14 UTC, tureck1y commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                let atimicUnitMultiplier = wallet.blockchain.decimalValue
NP: atimic?

2024-07-04 09:21 UTC, amuraveinik commented
3.07 пришлось делать ресерч по отслеживанию пендинг транзакций. Выше Андрей и Саша писали что существующий способ неподходит, и лучше использовать что-то лучше. Я посмотрел в доке коиноса нужную ручку, у одной апишки она возвращает 404, а для другой приходит ошибка JSONRPC, при том что в доке написано что придет просто результат. Погуглил соответствующие методы для выполнения этого запроса с помощью JSONRPC, ничего не нашел, пришлось идти копать js либу. В итоге нашел подходящий метод, потестил в постмане на существующих и несуществующих transactionIDs. Тут аналогично VeChain - для несуществующего айдишника возвращается пустой результат, сделал по аналогии. Пока не понятно будет ли это работать с пендинг транзакциями, когда транзакция с айдишником уже должна существовать, но статус не подтвержден. В ответе от сервера с транзакцией статус не указывает, так что если с этим будут проблемы, то придется использовать какой-то другой способ.

Интеграцию в приложение вчера не успел закончить

2024-07-04 09:50 UTC, Balashov152 submitted a review, later dismissed

2024-07-04 10:38 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                }
Сделал по-другому

2024-07-04 10:41 UTC, amuraveinik commented on BlockchainSdk/Common/Interfaces/TransactionValidator/FeeResourceRestrictable.swift
> +        }
Добавил коммент

2024-07-04 10:41 UTC, amuraveinik commented
> Проверил транзакции после доработок?

Да, конечно, все работает

2024-07-04 10:42 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                let atimicUnitMultiplier = wallet.blockchain.decimalValue
Поправил

2024-07-04 10:43 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosNetworkParams.swift
> +//  koinosNetworkParams.swift
Поправил

2024-07-04 10:45 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +}
Добавил коммент

2024-07-04 10:46 UTC, Balashov152 submitted a review, later dismissed

2024-07-05 21:04 UTC, tureck1y submitted a review, later dismissed

2024-07-08 08:29 UTC, Balashov152 approved these changes, later dismissed

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                wallet.clearPendingTransaction()
1. Тут как я понимаю логика что если pending уже не pending - то считаем ее прошедшей
Но нейминг говорит совсем о другом, как будто тут проверка что pending действительно pending

2. Тут идет завязка на то, что pending tx может быть только одна (выше `wallet.pendingTransactions.first`) - но это же не так в общем случае. И в таком случае будут затронуты другие pending. Ранее предлагалось вроде сделать запрос статуса на каждую pending, а затем его агрегировать - с этим какие-то проблемы именно в коиносе?
Вижу кста что судя по DTO, где массив tx ids - ручка умеет возвращать статус для множества транз.  Тогда еще легче все сделать можно и получится ограничиться одним запросом, если это так

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                        value: (rcLimit.decimal ?? .zero) / blockchain.decimalValue,
Кажется с точки зрения логики правильнее кидать ошибку, чем делать фоллбек на ноль (фи же не может быть ноль?)

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
>          )
Сетевой провайдер это архитектурно более низкий уровень, чем сетевой сервис - поэтому странно в нем видеть аггрегацию данных из двух ручек, этому место в сервисе

И судя по диффу раньше логика была была именно в сетевом сервисе - но почему-то переехала в сетевой провайдер
Это где-то обсуждалось?

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +        .tryMap(KoinosDTOMapper.convertNonce)
Маппинг dto->domain тоже немного странно видеть в провайдере, мне кажется это ответственность все-таки сервиса, а провайдер может возвращать ДТО. Но тут обсуждаемо

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +                Constants.maxDiskStorageLimit * limits.diskStorageCost
Точно этому не место в провайдере

2024-07-08 10:45 UTC, m3g0byt3 commented on BlockchainSdkTests/Koinos/KoinosMethodResponseDecodingTests.swift
> +                    NEARNetworkResult.APIError
nit: NEARNetworkResult.APIError🫠
Но вроде ни на что не влияет, можно забить

2024-07-08 16:42 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
>          )
Не обсуждалось, мне показалось более логичным именно в NetworkProvider всякие преобразования делать

2024-07-08 16:42 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
>          )
Вернул в сервис

2024-07-08 16:43 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/Network/KoinosNetworkProvider.swift
> +        .tryMap(KoinosDTOMapper.convertNonce)
Перенес в сервис

2024-07-08 16:52 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                wallet.clearPendingTransaction()
> Тут идет завязка на то, что pending tx может быть только одна

Да, на это и расчет. Мы же когда отправляем транзакцию - блочим сенд, пока все пендинг не перестанут быть пендинг, разве не так?

Я в большей части ориентируюсь [на андроид](https://github.com/tangem/blockchain-sdk-kotlin/blob/892924f6fe0569a1dd27ca4d560c182738e5f0be/blockchain/src/main/java/com/tangem/blockchain/blockchains/koinos/KoinosWalletManager.kt#L30), там проверка как раз идет по first. Там правда сетевой метод несколько другой чем у нас, но смысл такой же

2024-07-09 08:40 UTC, skibinalexander approved these changes, later dismissed

2024-07-09 09:06 UTC, tureck1y submitted a review, later dismissed

2024-07-09 09:30 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Koinos/KoinosWalletManager.swift
> +                wallet.clearPendingTransaction()
Сделал запрос на все имеющиеся транзакции и проверку тоже по всем айдишникам

2024-07-09 10:19 UTC, m3g0byt3 approved these changes

2024-07-09 10:49 UTC, tureck1y approved these changes

2024-07-09 10:50 UTC, skibinalexander approved these changes

2024-07-09 11:16 UTC, dbaturin approved these changes

2024-07-09 11:18 UTC, Balashov152 approved these changes

2024-07-09 11:21 UTC, merged