Cyber network support
tangem/blockchain-sdk-swift pull request #756
Opened 2024-07-07 00:09 UTC by darcang

adding support for Cyber L2 network https://docs.cyber.co/build-on-cyber/network-info.

To add some context, we got into a situation when our staked tokens could not be unstacked because Tangem is not supporting their new network, which they pushed everyone(me included). Happy to have any feedback!

2024-07-09 19:42 UTC, dbaturin requested changes

2024-07-09 19:42 UTC, dbaturin commented on BlockchainSdk/Blockchains/Ethereum/OtherChains/CyberExternalLinkProvider.swift
> +        baseExplorerUrl = isTestnet ? "https://cyber-testnet.alt.technology" : "https://cyber.alt.technology"
```suggestion
        baseExplorerUrl = isTestnet ? "https://testnet.cyberscan.co/" : "https://cyberscan.co/"
```

2024-07-09 22:16 UTC, darcang commented on BlockchainSdk/Blockchains/Ethereum/OtherChains/CyberExternalLinkProvider.swift
> +        baseExplorerUrl = isTestnet ? "https://cyber-testnet.alt.technology" : "https://cyber.alt.technology"
https://github.com/tangem/blockchain-sdk-swift/pull/756/commits/d7202f579e9230893dc10fb552a7ddf3683c92e3

2024-07-10 18:42 UTC, tureck1y reviewed
Thanks for your amazing work. We will accept this PR and take this network for internal testing after we prepare the icons and our backend.

2024-07-10 18:42 UTC, tureck1y commented on BlockchainSdk.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "a0738665bda10cbdb05da546422ce445e2fdf9ace530c7941d4cba18d71a3d25",
This file should be reverted

2024-07-10 18:42 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +    case cyber(testnet: Bool)
supportsEIP1559 is missing. Basically we check it by eth_feeHistory response. You can attach the response here and we will check

```
{
  "params": [
     5
    "latest",
    [25, 50, 75]
  ],
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_feeHistory"
}
```

2024-07-10 18:56 UTC, tureck1y commented
Cyber is an L2 network, so we must check how the L1 fee is calculated. 

Probably, the EthereumOptimisticRollupWalletAssembly should be used. 

https://docs.cyber.co/cyber-l2-and-optimism-superchain

2024-07-10 19:39 UTC, darcang commented on BlockchainSdk.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +  "originHash" : "a0738665bda10cbdb05da546422ce445e2fdf9ace530c7941d4cba18d71a3d25",
https://github.com/tangem/blockchain-sdk-swift/pull/756/commits/6d8875ac933c941c93721c9dbb3de0a119d815e4

2024-07-10 20:12 UTC, darcang commented on BlockchainSdk/Common/Blockchain.swift
> +    case cyber(testnet: Bool)
```json
{
   "jsonrpc":"2.0",
   "id":1,
   "result":{
      "oldestBlock":"0x3707f7",
      "reward":[
         [
            "0x0",
            "0xf4240",
            "0xf4240"
         ],
         [
            "0x0",
            "0x0",
            "0x0"
         ],
         [
            "0xf4240",
            "0xf4240",
            "0xf4240"
         ],
         [
            "0x0",
            "0x0",
            "0xf4240"
         ],
         [
            "0xf4240",
            "0xf452c",
            "0xf452c"
         ]
      ],
      "baseFeePerGas":[
         "0xfc",
         "0xfc",
         "0xfc",
         "0xfc",
         "0xfc",
         "0xfc"
      ],
      "gasUsedRatio":[
         0.0035375333333333334,
         0.0014605,
         0.0073422,
         0.0024133,
         0.012337633333333334
      ]
   }

2024-07-10 20:18 UTC, darcang commented
@tureck1y thanks for the feedback!
Yeah that was i [assumed](https://github.com/tangem/blockchain-sdk-swift/pull/756/files#diff-e0f9d65d5cc30a869c673655ea6fff26a5194a702430c16bdfdc5dd28814c5d0R1199) as well in analogy to base network

2024-07-27 12:26 UTC, darcang commented
@tureck1y Also if there is anything I could do to speed this up a bit, like opening PRs for adding icons and backend support, please let me know

2024-08-06 23:55 UTC, amuraveinik requested changes

2024-08-06 23:55 UTC, amuraveinik commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                .init(url: URL(string: "https://cyber-testnet.alt.technology")!)
There is `]` missing

2024-08-06 23:55 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +    case cyber(testnet: Bool)
According to the response, the network should support EIP-1559.

Please fetch the latest changes to your PR, set the corresponding property value to true, and after that, we'll be able to run tests.

2024-08-07 12:50 UTC, darcang commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                .init(url: URL(string: "https://cyber-testnet.alt.technology")!)
https://github.com/tangem/blockchain-sdk-swift/pull/756/commits/539d4038ba0fd33818a04125d84fd305ac27fa6d

2024-08-07 12:50 UTC, darcang commented on BlockchainSdk/Blockchains/Ethereum/OtherChains/CyberExternalLinkProvider.swift
> +        baseExplorerUrl = isTestnet ? "https://testnet.cyberscan.co/" : "https://cyberscan.co/"
https://github.com/tangem/blockchain-sdk-swift/pull/756/commits/fe06f1fb3e8f56d3b3f67cf38f2aec668bd45629

2024-08-07 12:53 UTC, darcang commented on BlockchainSdk/Common/Blockchain.swift
> +    case cyber(testnet: Bool)
[this](https://github.com/tangem/blockchain-sdk-swift/blob/fe06f1fb3e8f56d3b3f67cf38f2aec668bd45629/BlockchainSdk/Common/Blockchain.swift#L751) one already set to true 
Is there another place i should change?

2024-08-08 11:31 UTC, amuraveinik requested changes

2024-08-08 11:33 UTC, amuraveinik commented
Additionally, please add 'cyber' to the currencyId computed property, just as it is done for 'base'. This is to ensure the price is displayed correctly in the app

2024-08-08 11:35 UTC, amuraveinik commented
> Additionally, please add case `cyber` to the `currencyId` computed property, just as it is done for `base`. This is to ensure the price is displayed correctly in the app

```swift
 /// Should be used to get the actual currency rate.
    public var currencyId: String {
        switch self {
        case .arbitrum(let testnet),
             .optimism(let testnet),
             .aurora(let testnet),
             .manta(let testnet),
             .zkSync(let testnet),
             .polygonZkEVM(let testnet),
             .base(let testnet):
             // <- case .cyber
            return Blockchain.ethereum(testnet: testnet).coinId
        default:
            return coinId
        }
    }
```

2024-08-08 13:32 UTC, darcang commented on BlockchainSdk/Common/Blockchain.swift
> +            return "cyber"
https://github.com/tangem/blockchain-sdk-swift/pull/756/commits/986f14324284ae5c4fe07e123487ec639d60f1b0

2024-08-08 14:12 UTC, amuraveinik requested changes

2024-08-08 14:12 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cyber: return true
```suggestion
        case .cyber: return false
```

2024-08-08 14:12 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +        case .cyber: return true
I apologize for the error in one of my previous comments about eip1559 support. It seems that setting this property to true enables sending transactions, but not with the maximum amount. Using the maximum amount results in an error related to gas * price, indicating that eip1559 is not supported

2024-08-08 16:12 UTC, amuraveinik approved these changes

2024-08-08 16:17 UTC, dbaturin approved these changes

2024-08-09 07:02 UTC, fedorov-d approved these changes

2024-08-09 09:09 UTC, tureck1y approved these changes

2024-08-09 09:16 UTC, m3g0byt3 approved these changes

2024-08-09 12:30 UTC, merged