IOS-6549: Mantle: error when enter max amount
tangem/blockchain-sdk-swift pull request #760
Opened 2024-07-08 12:36 UTC by amuraveinik

[IOS-6549](https://tangem.atlassian.net/browse/IOS-6549)

[IOS-6549]: https://tangem.atlassian.net/browse/IOS-6549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Сообщение от Дениса с решением](https://tangem.slack.com/archives/GMXC6PP71/p1719591856597299?thread_ts=1714215815.690169&cid=GMXC6PP71)

2024-07-15 13:25 UTC, AlekseiMuraveinik1 commented
Работает стабильно, изменений в аппке не требует

2024-07-15 13:57 UTC, tureck1y requested changes

2024-07-15 13:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +        parameters = EthereumEIP1559FeeParameters(
Пока что надо бы поддерживать оба типа фи, потому что непонятно финально как будет WalletConnect работать

2024-07-15 13:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +    override func getFee(amount: Amount, destination: String) -> AnyPublisher<[Fee], any Error> {
а зачем переопределять этот метод, когда есть более низкоуровневый? Он уже специально вынесен из extension
` func getFee(destination: String, value: String?, data: Data?) -> AnyPublisher<[Fee], Error>`

2024-07-15 13:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +class EthereumWalletManager: BaseManager, WalletManager, TransactionFeeProvider, EthereumTransactionSigner {
Получается что фи, не нужно переносить, можно переопределить другой метод.
EthereumTransactionSigner - переопределить нужно, но я не понял как работает, он же оставлся в extension.
То же самое надо сделать для EthereumTransactionSender

2024-07-15 13:59 UTC, tureck1y commented
> Работает стабильно, изменений в аппке не требует

не очень понял как работает, потому что в сенде юзается другой метод и в нем нет манипуляций с транзакцией

2024-07-15 14:22 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +    override func getFee(amount: Amount, destination: String) -> AnyPublisher<[Fee], any Error> {
Так было проще произвести уменьшение эмаунта, типа не надо декодировать string в число и потом обратно. И тут интерфес понятнее, т.к. видно откуда вызовы идут, в отличие от более низкоуровневого

2024-07-15 14:25 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +class EthereumWalletManager: BaseManager, WalletManager, TransactionFeeProvider, EthereumTransactionSigner {
`func sign(_ transaction: Transaction, signer: TransactionSigner) -> AnyPublisher<String, Error>` я поднял тоже из экстеншена в сам класс, как раз чтобы можно было переопределить в `MantleWalletManager`

2024-07-15 14:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +class EthereumWalletManager: BaseManager, WalletManager, TransactionFeeProvider, EthereumTransactionSigner {
Странно, я в диффе вижу только перенос getFee

2024-07-15 14:30 UTC, amuraveinik commented
> > Работает стабильно, изменений в аппке не требует
> 
> не очень понял как работает, потому что в сенде юзается другой метод и в нем нет манипуляций с транзакцией

В WalletModel вызывается вот эта функция, которая вызывает send из EthereumWallerManager, который уже вызывает sign, который я переопределил в `MantleWalletManager`

```swift
func send(_ tx: Transaction, signer: TransactionSigner) -> AnyPublisher<TransactionSendResult, SendTxError> {
    if isDemo {
        let hash = Data.randomData(count: 32)
        return signer.sign(hash: hash, walletPublicKey: wallet.publicKey)
            .mapSendError(tx: hash.hexString)
            .map { _ in TransactionSendResult(hash: hash.hexString) }
            .receive(on: DispatchQueue.main)
            .eraseSendError()
            .eraseToAnyPublisher()
    }

    return walletManager
        .send(tx, signer: signer)
        .receive(on: DispatchQueue.main)
        .withWeakCaptureOf(self)
        .handleEvents(receiveOutput: { walletModel, _ in
            walletModel.updateAfterSendingTransaction()
        })
        .map(\.1)
        .eraseToAnyPublisher()
}
```

2024-07-15 14:58 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +        parameters = EthereumEIP1559FeeParameters(
Добавил

2024-07-15 15:00 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +class EthereumWalletManager: BaseManager, WalletManager, TransactionFeeProvider, EthereumTransactionSigner {
Это просто дифф так отображается, в нем убраны комменты и объявления экстеншенов таким образом что send теперь в самом классе. Там если развернуть неизмененный код, то нагляднее видно

2024-07-15 15:52 UTC, tureck1y reviewed
Судя по всему все равно придется заморочиться декодом value, потому что нужно переопределять е еще и getGasLimit, он используется в WalletConnect. Для этого можно использовать EthereumUtils

2024-07-16 11:56 UTC, tureck1y submitted a review, later dismissed

2024-07-16 13:30 UTC, tureck1y commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +        .flatMap { transaction in
.withWeakCaptureOf(self) вроде не хватает

2024-07-17 09:14 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +        .flatMap { transaction in
Тут утечки не будет все равно, т.к. паблишер резалта эмиттит только один элемент, причем синхронно, то есть в момент подписки ссылка на `super` разрушится практически сразу.

К тому же если захватить `self` сюда и на нем вызвать `sign`, то вызовется `sign` не суперкласса, а текущий, то есть будет бесконечная рекурсия

2024-07-17 11:40 UTC, tureck1y approved these changes, later dismissed

2024-07-17 12:17 UTC, m3g0byt3 requested changes

2024-07-17 12:17 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                    value: parsedValue - (1 / blockchain.decimalValue)
А зачем это?

Вычитание `1 / 10^18`, это какой-то костыль из-за округления?
То есть на балансе всегда будет оставаться от 0 до 1 wei?

Выглядит сомнительно

2024-07-17 12:17 UTC, m3g0byt3 commented on BlockchainSdkTests/Mantle/MantleTests.swift
> +            29.618123086712134,
Тут инит decimal из float литералов с потерей точности
Из-за них тесты как минимум могут флакать, как максимум - ничего не будут тестировать по сути
https://forums.swift.org/t/how-to-initialize-decimal/53630/7

Надо юзать стринг литералы + `init?(stringValue: String?)`

2024-07-17 14:13 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                    value: parsedValue - (1 / blockchain.decimalValue)
Так задумано Денисом чтобы не фейлился запрос фи

2024-07-17 14:16 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                gasLimit: BigUInt(ceil(Double(parameters.gasLimit) * gasLimitMultiplier)),
Надо умножить BigUInt на дробное число (1.6 либо 0.7) таким образом чтобы в итоге снова получился BigUInt. Кроме как кастить к дробным, умножать и округлять вверх - не понимаю какие еще есть опции

2024-07-18 11:51 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                    value: parsedValue - (1 / blockchain.decimalValue)
Добавил в описание PR ссылку на сообщение в слаке

2024-07-18 14:22 UTC, m3g0byt3 approved these changes

2024-07-18 14:22 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                gasLimit: BigUInt(ceil(Double(parameters.gasLimit) * gasLimitMultiplier)),
C комментом в слаке многое прояснилось

Можно еще сделать через уже юзаемые экстеншены:
- Перевести BigUInt в Decimal (`var decimal` из `BigUInt+.swift`), полученный Decimal домножить на что надо
- Округлить произведение вверх через `var roundedDecimalNumber` из `Decimal+.swift`
- Создать из полученного Decimal снова BigUInt c помощью `init?(decimal decimalValue: Decimal)` из `BigUInt+.swift`

Но это чисто ради консистентности с остальным кодом, сохранение точности нам тут получается не важно (раз есть округление все равно) - поэтому не обязательно

2024-07-18 14:22 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/Mantle/MantleWalletManager.swift
> +                    value: parsedValue - (1 / blockchain.decimalValue)
Интересный конечно костыль

Я бы добавил здесь `max(parsedValue - (1 / blockchain.decimalValue), 0)`, чисто на всякий случай, чтобы в ручку не улетело отрицательное значение (если это вообще возможно)

Я не знаю, можно ли каким-нибудь способом в BSDK или аппе инициировать трансфер ниже, чем одна атомарная единица, поэтому это на всякий случай и не обязательно

2024-07-19 09:15 UTC, fedorov-d approved these changes

2024-07-22 11:00 UTC, tureck1y approved these changes

2024-07-22 12:48 UTC, dbaturin approved these changes

2024-07-22 13:18 UTC, tureck1y commented
@dbaturin интересно, почему-то твои апрувы не принимаются

2024-07-22 13:18 UTC, merged