Ios 7049 icp network
tangem/blockchain-sdk-swift pull request #773
Opened 2024-07-16 10:54 UTC by fedorov-d

Сетевой слой для ICP. Для запросов нужны CBOR-encoded объекты генерируемые с помощью либы IcpKit.

2024-07-16 10:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +final class ICPTransactionBuilder {
на будущее

2024-07-16 10:55 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let fee = Decimal(stringValue: "0.0001")!
пока не все константы используются, также на будущее

2024-07-16 11:23 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +    case internetComputer(curve: EllipticCurve)
Предлагаю оставить icp ради компактности

2024-07-16 11:42 UTC, fedorov-d commented on BlockchainSdk/Common/Blockchain.swift
> +    case internetComputer(curve: EllipticCurve)
в WalletCore internetComputer, на беке "internetComputer", для единообразия решил так сделать

2024-07-18 09:25 UTC, skibinalexander commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +                    self?.wallet.add(coinValue: balance)
Пока не видно сброс pending транзакций, будет дальше?

2024-07-18 09:25 UTC, skibinalexander commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +                    result/blockchain.decimalValue
Слиплось

2024-07-18 09:26 UTC, skibinalexander commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/223'/0'/0/0"
А с другими кошелями совпало да ?

2024-07-18 13:40 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +                    self?.wallet.add(coinValue: balance)
я немного не в курсе как это должно работать, но я не добавляю транзакцию в pending после send-a т.к. она судя по всему отрабатывает достаточно быстро и у нас нет возможности проверить ее статус после отправки.

2024-07-18 13:41 UTC, fedorov-d commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/223'/0'/0/0"
да, с трастом совпадает

2024-07-18 14:12 UTC, dbaturin requested changes

2024-07-18 14:12 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +                    self?.wallet.add(coinValue: balance)
У нас много где, где не умеем транзакции смотреть, механизм такой: добавляем после сенда дамми неподтвеждённую транзакцию. Как только баланс изменится, чистим транзакции.

2024-07-18 14:12 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    private func makeBalanceRequestData() throws -> Data {
Почему создание запроса в WalletManager, а не в NetworkProvider? Мне кажется, этому тут не место.

2024-07-18 14:12 UTC, dbaturin commented
Ах, да, почемуто у NetworkProvider класса пропало слово Network, хотя везде вроде как есть

2024-07-18 14:32 UTC, amuraveinik submitted a review, later dismissed

2024-07-18 17:29 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +                    self?.wallet.add(coinValue: balance)
добавил логику

2024-07-18 17:30 UTC, fedorov-d commented
> Ах, да, почемуто у NetworkProvider класса пропало слово Network, хотя везде вроде как есть

смотрел на TON, в нем просто Provider, поправил

2024-07-18 17:59 UTC, dbaturin approved these changes

2024-07-18 17:59 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let readStateRetryDelayMilliseconds = 500
Ой, как-то в прошлом ревью не оставил здесь комментарий. Это же тоже сетевая штука какая-то? Но почему она тогда ещё не используется? Ну как будешь использовать, тогда можно и переложить.

2024-07-19 06:27 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let readStateRetryDelayMilliseconds = 500
да я отписал это выше, это уже готово в следующем пр, как этот смержу - сразу же сделаю второй, но если критично - могу убрать

2024-07-19 08:15 UTC, skibinalexander approved these changes

2024-07-19 08:47 UTC, amuraveinik approved these changes

2024-07-19 09:41 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +    case internetComputer(curve: EllipticCurve)
На бэк не стоит ориентироваться, там айдишники коингеко, они нашим не всегда соответствуют. Нужно выбрать что-то одно. Кейс енама internetComputer, но папка в Blockchains называется ICP и все сущности ICPWalletManager и так далее.

2024-07-22 09:30 UTC, tureck1y approved these changes

2024-07-22 10:46 UTC, merged