IOS-7051 Ability to send new transaction on ETH like networks with active transaction
tangem/blockchain-sdk-swift pull request #775
Opened 2024-07-21 20:22 UTC by amuraveinik

[IOS-7051](https://tangem.atlassian.net/browse/IOS-7051)

2024-07-21 20:25 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumTransactionParams.swift
> -    public let nonce: Int?
Тут убрано нонс, т.к. в транзакшн билдер его явно передаем в качестве аргумента. 

Решил подойти именно с этой стороны, а не со стороны того чтобы сделать его неопциональным, т.к. есть место в `CommonWalletConnectEthTransactionBuilder` где создается `EthereumTransactionParams` и в качестве нонса там потенциально опциональное значение. Я пробежался по стеку вызовов, и насколько понял там нет четкого контракта что точно прийдет что-то в качестве нонса, т.к. ответ парсится из JSON

2024-07-21 20:27 UTC, amuraveinik commented
Проверил на полигоне и троне, работает

2024-07-22 10:54 UTC, tureck1y requested changes

2024-07-22 10:54 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    func buildForSign(transaction: Transaction, nonce: Int) throws -> Data {
Давай лучше сделаем через TransactionParams, чтобы был один источник

2024-07-22 11:35 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +    var isParallelTransactionAllowed: Bool {
```suggestion
    var isParallelTransactionsAllowed: Bool {
```
можно еще поиграться с неймингом в сторону concurrent, multiple и т.д. - но кажется и так норм

2024-07-22 11:35 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +        return isEvm || isTron
Не слишком запарно ли для такой мелочи?)
Как в будущем расширить если кроме трона что-то еще подъедет?

```
switch {
  case _ where isEvm, .tron:
    return true
  default:
    return false
}
```

2024-07-22 12:20 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +    var isParallelTransactionAllowed: Bool {
Тут тогда надо вместо is делать are, т.к. их же несколько. 

Я когда делал решил оставить в единственном числе с помощью такой мысленной проверки: "Могу ли я параллельно с текущей транзакцией отправить еще одну". 

То есть типа
- Блокчейн, ты тут?
- Ага
- Еще **одну** параллельную транзакцию можно?
- Давай

2024-07-23 10:28 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumTransactionParams.swift
> -    public let nonce: Int?
Уже неактуально, т.к. решили засунунть нонс обратно в параметры

2024-07-23 11:27 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +    var isParallelTransactionAllowed: Bool {
>Тут тогда надо вместо is делать are, т.к. их же несколько.

все время забываю про to be(

по неймингу вроде понятно, что происходит - поэтому и не предлагаю что-то менять

2024-07-23 11:27 UTC, m3g0byt3 submitted a review, later dismissed

2024-07-23 11:43 UTC, tureck1y requested changes

2024-07-23 11:43 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        nonce: Int
В целом это же дамми-транзакция, можно было и не передават сюда нонс и запрос лишний не потребуется. Думаю что можно просто единичку поставить. Собранная транзакция пихается в смарт-контракт оракул, который прогнозирует для нее фи, а нонс на фи не влияет

2024-07-23 11:43 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +    var isParallelTransactionAllowed: Bool {
Только тут момент, зачем в extension выносить? Пусть лежит рядом с такими же пропертями

2024-07-23 11:43 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .publisher
в чем смысл менять tryMap на эту конструкцию?

2024-07-23 11:43 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .withWeakCaptureOf(walletManager)
а почему тут и ниже walletManager, а не self?

2024-07-23 13:03 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .publisher
Я бы сделал `tryFlatMap` если бы он был.

Вообще сделал таким образом, т.к. в предыдущей реализации два раза вызывался `convertToETHAddresses` - один раз через паблишер, один раз синхронно, по диффу видно, хотя по сути результат был одинаковый. И по ходу исполнения операторов использовались то аргументы функции, то элементы последовательности, что сложновато читается, и я на этом не раз споткнулся.

Сейчас же структурно все более единообразно, аргументы функции используются только один раз, а далее - только элементы последовательности

2024-07-23 13:03 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .withWeakCaptureOf(walletManager)
Потому что в этом скоупе мы не можем использовать `self` предварительно его не захватив.
Мы уже захватили `self` на 90 строке, и в скоупе у нас `self` уже существует под именем `walletManager`

2024-07-23 13:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .withWeakCaptureOf(walletManager)
Хм, это точно так? Нигде не было в цепочках такого. @m3g0byt3 глянь плиз

2024-07-23 16:05 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .publisher
было:

```
 .tryMap { walletManager, convertedTransaction in
                 try walletManager.txBuilder.buildForSign(transaction: convertedTransaction)
             }
```

cтало:

```
 .flatMap { walletManager, convertedTransaction in
             Result {
                 try walletManager.txBuilder.buildForSign(transaction: convertedTransaction)
             }
             .publisher
```

Вот я и спросил в чем смысл, было компактнее, можно оставить?

2024-07-23 16:55 UTC, tureck1y approved these changes

2024-07-23 18:02 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .withWeakCaptureOf(walletManager)
Ок, разобрался)

2024-07-23 18:02 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumWalletManager.swift
> +            .publisher
Я сразу не понял, что вся цепочка завернута во flatMap

2024-07-23 18:02 UTC, tureck1y approved these changes

2024-07-23 18:11 UTC, Balashov152 approved these changes

2024-07-23 18:20 UTC, dbaturin approved these changes

2024-07-23 18:22 UTC, merged