IOS-7228 Change the logic for Receive pageChange the logic for Receive page
tangem/blockchain-sdk-swift pull request #776
Opened 2024-07-21 21:01 UTC by amuraveinik

[IOS-7228](https://tangem.atlassian.net/browse/IOS-7228)

2024-07-22 09:45 UTC, tureck1y requested changes

2024-07-22 09:45 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        if case .ton = self {
Давай сделаем через switch/case для единообразия со всем файлом и для задела под расширение другими сетями

2024-07-22 12:00 UTC, tureck1y approved these changes

2024-07-22 14:49 UTC, skibinalexander approved these changes

2024-07-22 15:39 UTC, fedorov-d approved these changes

2024-07-23 10:02 UTC, dbaturin approved these changes
А ETH будем Ether называть? А XLM - Lumens? Надо будет подумать над этим.

2024-07-23 10:03 UTC, tureck1y commented
> А ETH будем Ether называть? А XLM - Lumens? Надо будет подумать над этим.

Пока только про тонкоин была задача 😀

2024-07-23 10:29 UTC, merged