Ios 7049 icp transaction build
tangem/blockchain-sdk-swift pull request #778
Opened 2024-07-22 12:11 UTC by fedorov-d

Добавил ICPSigner для генерации и подписи хешей. Отправляется 2 запроса: обычный send который возвращает пустой ответ если все нормально и read_state который трекает состояние предыдущего запроса, успех или ошибка возвращается уже в нем. Соотвественно для каждого из этих запросов нужен свой подписанный хеш.

2024-07-22 12:13 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let readStateRetryCount = 10
увеличил значения на случай плохой сети, когда все хорошо success обычно приходит на второй-третий повтор запроса.

2024-07-22 12:19 UTC, tureck1y commented
А есть тесты на сборку и размер транзакции?

2024-07-23 06:13 UTC, fedorov-d commented
> А есть тесты на сборку и размер транзакции?

добавил

2024-07-23 09:27 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +    init(blockchain: Blockchain) {
лучше передавать decimalValue, иначе получается что я могу собрать эбилдер с любым блокчейном

2024-07-23 19:38 UTC, dbaturin requested changes

2024-07-23 19:38 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    func buildTransaction(
signTransaction гораздо лучше подходит. И сразу понятно, почему не часть TransactionBuilder

2024-07-23 19:38 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    }
Это как-будто надо убрать в NetworkService, почему WalletManager управляет задержками и ретраями запросов?

2024-07-23 19:38 UTC, dbaturin commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let readStateRetryDelayMilliseconds = 750
Как и это, собственно

2024-07-24 11:00 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    func buildTransaction(
переименовал

2024-07-24 11:01 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    }
частично перенес

2024-07-24 11:01 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        static let readStateRetryDelayMilliseconds = 750
перенес

2024-07-24 13:09 UTC, m3g0byt3 reviewed
А как происходит очистка pending tx? Или это в другом пуле будет?

2024-07-24 13:09 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    private var signingOutput: ICPSigningOutput?
Такой стейт выглядит хрупковато - не будет работать несколько параллельных транз

Нет какого-то айдишника (хеш?), по которому можно было бы класть в словарь `signingOutput` для конкретной транзы?

2024-07-24 13:09 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
А разве будет работать в таком случае открытие pending tx?

2024-07-24 13:09 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .flatMap { walletManager, input in
Внутри этой кложуры self захвачен сильно

2024-07-25 05:47 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    private var signingOutput: ICPSigningOutput?
очистка просиходит внутри `private func updateWallet(with balance: Decimal)`. стейт убрал, вместо этого пробрасываю нужный объект вниз по цепочке.

2024-07-25 05:47 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +                                self?.signingOutput = nil
убрал это совсем

2024-07-25 06:52 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
немного поправил логику, теперь retry должен сработать только при получении пустого ответа (result == nil), при получении какой-то ошибки (например сетевой) - retry не сработает. насколько я понял retry применится ко всей цепочке, т.е. к поиску провайдера в том числе, но там сохраняется текущий индекс и будет переиспользован тот же провайдер что и на предыдущую попытку (в этом на 100% не уверен)

2024-07-25 06:52 UTC, fedorov-d commented on BlockchainSdkTests/ICP/ICPTests.swift
> +    func testTransactionBuild() throws {
да, по сути что сборка не фейлит на каком-либо из этапов.

2024-07-25 06:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +    ) throws -> ICPSigningInput {
идея была примерно повторить апи walletconnect, чтобы код был похож на аналогичный в других сетях, но с минусами согласен, не учел этот момент. если критично - можно попробовать переработать.

2024-07-25 06:54 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +    private var signingOutput: ICPSigningOutput?
убрал это

2024-07-25 06:56 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
тут на самом деле не знаю как правильно, результатом исполнения транзакции является некий индекс блока в блокчейне, валидно ли его использовать для формирования TransactionSendResult ?

2024-07-25 06:56 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .flatMap { walletManager, input in
поправил

2024-07-26 17:11 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
по идее нам нужен именно хэш, по нему уже будет работать преход в эсплорер, отправка хэша в эспресс и тп

2024-07-26 17:17 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +    ) throws -> ICPSigningInput {
А в чем идея была добавлять ICPSigner? Задумка разделения на сущености в бсдк была такая, что билдер ворочает байтиками и отдает данные,которые полетаят на карту, потом принимает в себя данные + подпись и возарвщает уже транзакцию, готовую к отправке в сеть. WalletManager просто дерижирует оркестром. Сейчас получается что появилась еще сущность сайнера, куда попала часть логики из бсдк и часть из билдера

2024-07-26 17:17 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
мы в целом начали выпиливать все лишние ретраи, по идее достаточно ретраев в мультинетворкпровайдере

2024-07-26 17:18 UTC, tureck1y commented on BlockchainSdkTests/ICP/ICPTests.swift
> +import IcpKit
+ за то, чтобы убрать

2024-07-29 08:47 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
в мультинетворкпровайдере ретрай сработает уже с новым провайдером, но в этом мало смысла, суть задачи - дождаться нужного ответа от текущего провайдера.

2024-07-29 09:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
В этом и суть, если что-то пошло не так, переключаемся к следующему провайдеру, чтобы не терять время на текущем, поэтому все и выпиливаем

2024-07-29 09:30 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
боюсь что хеш достать не получится

2024-07-29 09:31 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
а после отправки в сеть апишка хэш не возвращает?

2024-07-29 09:32 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
Тут надо разбираться. Сюда нужно передать инденификатор транзакции, наверняка есть такое понятие в этом блокчейне

2024-07-29 09:32 UTC, fedorov-d commented
сейчас сборка фейлит, т.к. внес локальные правки в либу IcpKit, не хочу создавать отдельный пр пока не устаканим апи

2024-07-29 10:33 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
тут ничего не идет не так, апи ожидаемо не возвращает нужное значение до каких-то пор, это не ошибка.

2024-07-29 10:52 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +    ) throws -> ICPSigningInput {
>насчет того что либа вылезает глобальный скоуп - боюсь что от этого не получится избавиться

Ну в хедере я например решил это оберткой `HederaTransactionBuilder.CompiledTransaction`, которая внутри себя скрывает юзание либы

Наверняка и в случае ICP можно сделать что-то подобное

2024-07-29 10:52 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +            }
Имхо проще читается если анврапить опционал в отдельных кейсах:
```
.success(.some(value)):
.success(nil):
.failure(let error):
```

2024-07-29 10:52 UTC, m3g0byt3 commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
А это будет работать, если во время ретраев конкретного прова он выйдет из строя? И провайдер вернет следующий провайдер

Хотя конечно вероятность такая не очень велика, можно и забить

2024-07-29 10:52 UTC, m3g0byt3 commented on BlockchainSdkTests/ICP/ICPTests.swift
> +    func testTransactionBuild() throws {
Я к тому, что если такая реальная транза есть - надо бы приложить на нее ссылку в эксплорере, указать откуда получен приватник (из какого сида, вообще для тестов юзается стандартный сид для этого - `tiny escape...`)

Чтобы тест был повторяем с другим набором тулз, платформ и т.д.

2024-07-29 12:56 UTC, fedorov-d commented on BlockchainSdkTests/ICP/ICPTests.swift
> +    func testTransactionBuild() throws {
а, нет, такой транзакции нет в реальности, это обязательное требование?

2024-07-29 12:56 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPTransactionBuilder.swift
> +    ) throws -> ICPSigningInput {
у меня есть подобные обертки ICPSigningInput и ICPSigningOutput, перенес их из IcpKit для наглядности, но на 100% процентов это проблему не решит, т.к. либа используется еще и на сетевом слое

2024-07-29 13:03 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/Network/ICPNetworkService.swift
> +        .retry(Constants.readStateRetryCount)
по идее должно, но к сожалению, проверить не выйдет, т.к. у нас только 1 эндпоинт (за ним скрывается 2 провайдера, это обсуждалось)

2024-07-30 05:21 UTC, fedorov-d commented on BlockchainSdkTests/ICP/ICPTests.swift
> +import IcpKit
убрал где можно

2024-07-30 05:23 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +            .map { _ in TransactionSendResult(hash: "") }
@dbaturin подсказал что вместо хеша можно использовать этот самый block index https://forum.dfinity.org/t/how-to-verify-icp-transactions/18374/6

2024-07-30 09:29 UTC, tureck1y commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        )
забыл в assembly унести, чет я сразу эту строчку не заметил, сорри

2024-07-30 09:29 UTC, tureck1y commented
Тесты падают еще

2024-07-30 09:50 UTC, fedorov-d commented on BlockchainSdk/Blockchains/ICP/ICPWalletManager.swift
> +        )
перенес

2024-07-30 09:51 UTC, fedorov-d commented
> Тесты падают еще

по тестам писал выше https://github.com/tangem/blockchain-sdk-swift/pull/778#issuecomment-2255450509 хочу сначала получить здесь аппрувы, прежде чем делать пр в IcpKit

2024-07-30 10:29 UTC, tureck1y approved these changes, later dismissed

2024-07-30 12:17 UTC, dbaturin approved these changes, later dismissed

2024-07-31 09:33 UTC, skibinalexander commented on BlockchainSdkTests/ICP/ICPTests.swift
> +    func testTransactionBuild() throws {
> а, нет, такой транзакции нет в реальности, это обязательное требование?

Ну желательно да, собрать данные транзакции которая теплой прошла, на тестовой мнемонике и ее тестировать. Потому как транзакции может не фейлиться, но при этом сборка будет не правильная

2024-07-31 14:36 UTC, skibinalexander approved these changes, later dismissed

2024-08-01 11:47 UTC, m3g0byt3 approved these changes

2024-08-01 11:56 UTC, tureck1y approved these changes

2024-08-01 11:56 UTC, merged