Bugfix/ios 7494 fix bitcoin fee
tangem/blockchain-sdk-swift pull request #785
Opened 2024-07-30 18:58 UTC by skibinalexander

Сделал приведение расчета Fee к Андроид

Проблема на первый взгляд была в нескольких местах. Одинаковый fee по трем значениям был из минимального rate 10 * 10 ^ -5

- Поставил 1
- Всегда бралось среднее значение из всех апишек, но по факту блоксайфер кидает чуть больше, значения которые сейчас берутся среди 3х апишек максимальное. **Тут надо проревьюить**
- Также убрал странную логику подмены фи, которой не было на андроид

2024-07-30 18:59 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Bitcoin/BitcoinWalletManager.swift
> +    var minimalFeePerByte: Decimal { 1 }
Из-за этого была одинаковая комиссия, значение теперь совпадает с андроид

2024-07-30 18:59 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Bitcoin/BitcoinWalletManager.swift
> -        let minimalFeeRate = (((minimalFee * Decimal(minRate)) / minFee).rounded(scale: 0, roundingMode: .up) as NSDecimalNumber).intValue
Логика отсутствует у Андроид, писал @dbaturin

2024-07-30 18:59 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Bitcoin/Network/BitcoinNetworkService.swift
> +                let minAvarage = feeList.map { $0.minimalSatoshiPerByte }.sorted().dropFirst().reduce(0, +) / divider
расчет средних оставил, так как max() дает опционал

2024-07-30 19:00 UTC, skibinalexander commented on BlockchainSdk/CommonNetworkServices/Blockcypher/BlockcypherNetworkProvider.swift
> +                let min = (Decimal(minKb)/kb).rounded(roundingMode: .up)
Округление в большую сторону, как во всех остальных местах

2024-07-31 11:48 UTC, dbaturin submitted a review, later dismissed

2024-07-31 13:31 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Bitcoin/Network/BitcoinNetworkService.swift
> +                    let prioritySatoshiPerByte = feeList.map({ $0.prioritySatoshiPerByte }).max(),
nit: можно использовать удобный синтаксический сахар `feeList.map(\.prioritySatoshiPerByte)`

2024-07-31 13:31 UTC, amuraveinik submitted a review, later dismissed

2024-08-01 11:05 UTC, m3g0byt3 reviewed
А каким образом исходный баг фиксится в этой задаче, если от апишки приходят три одинаковых значения?

>От гетблока для метода estimatesmartfee  для трех запросов приходит одинаковый ответ по комиссии

2024-08-01 16:01 UTC, tureck1y commented on BlockchainSdk/Blockchains/Bitcoin/BitcoinWalletManager.swift
> +    var minimalFeePerByte: Decimal { 1 }
@Andoran90 не помнишь откуда 10 взялось вообще? Судя по истории ты добавлял

2024-08-01 18:08 UTC, tureck1y requested changes

2024-08-01 18:08 UTC, tureck1y commented on BlockchainSdk/Blockchains/Bitcoin/Network/BitcoinNetworkService.swift
> +
Что-то не то, в андроиде же другая логика. Берется именно средняя, откидывается минимальная, как у нас и было реализовано

```
    override suspend fun getFee(): Result<BitcoinFee> {
        return coroutineScope {
            val resultsDeferred = multiProvider.providers.map { async { it.getFee() } }
            val results = resultsDeferred.map { it.await() }
            val fees = results.filterIsInstance<Result.Success<BitcoinFee>>().map { it.data }
            if (fees.isEmpty()) return@coroutineScope results.first()

            val bitcoinFee = if (fees.size > 2) {
                BitcoinFee(
                    minimalPerKb = fees.map { it.minimalPerKb }.sorted().drop(1).average(),
                    normalPerKb = fees.map { it.normalPerKb }.sorted().drop(1).average(),
                    priorityPerKb = fees.map { it.priorityPerKb }.sorted().drop(1).average(),
                )
            } else {
                BitcoinFee(
                    minimalPerKb = fees.map { it.minimalPerKb }.maxOrNull()!!,
                    normalPerKb = fees.map { it.normalPerKb }.maxOrNull()!!,
                    priorityPerKb = fees.map { it.priorityPerKb }.maxOrNull()!!,
                )
            }

            Result.Success(bitcoinFee)
        }
    }
```

2024-08-01 18:08 UTC, tureck1y commented on BlockchainSdk/Blockchains/Bitcoin/BitcoinWalletManager.swift
> -        let minimalFeeRate = (((minimalFee * Decimal(minRate)) / minFee).rounded(scale: 0, roundingMode: .up) as NSDecimalNumber).intValue
Вероятно в анлроиде либа не рассчитает фи меньше минимального за кб, а у нас может, для этого и был нужен этот код, его нельзя удалять. Было 10, стало 1. Почему 10 и почему 1?

@dbaturin какой у вас значение minimalFeePerKb?

2024-08-01 18:27 UTC, skibinalexander commented on BlockchainSdk/Blockchains/Bitcoin/Network/BitcoinNetworkService.swift
> +
> Что-то не то, в андроиде же другая логика. Берется именно средняя, откидывается минимальная, как у нас и было реализовано
> 
> ```
>     override suspend fun getFee(): Result<BitcoinFee> {
>         return coroutineScope {
>             val resultsDeferred = multiProvider.providers.map { async { it.getFee() } }
>             val results = resultsDeferred.map { it.await() }
>             val fees = results.filterIsInstance<Result.Success<BitcoinFee>>().map { it.data }
>             if (fees.isEmpty()) return@coroutineScope results.first()
> 
>             val bitcoinFee = if (fees.size > 2) {
>                 BitcoinFee(
>                     minimalPerKb = fees.map { it.minimalPerKb }.sorted().drop(1).average(),
>                     normalPerKb = fees.map { it.normalPerKb }.sorted().drop(1).average(),
>                     priorityPerKb = fees.map { it.priorityPerKb }.sorted().drop(1).average(),
>                 )
>             } else {
>                 BitcoinFee(
>                     minimalPerKb = fees.map { it.minimalPerKb }.maxOrNull()!!,
>                     normalPerKb = fees.map { it.normalPerKb }.maxOrNull()!!,
>                     priorityPerKb = fees.map { it.priorityPerKb }.maxOrNull()!!,
>                 )
>             }
> 
>             Result.Success(bitcoinFee)
>         }
>     }
> ```

Эта логика в андроиде, если >2 апи могу ревертнуть, но тогда комса будет расходится

2024-08-06 09:54 UTC, tureck1y reviewed
Пробегись плиз по перегрузкам, получается вот такие менеджеры теперь можно снести нафиг

`class LitecoinWalletManager: BitcoinWalletManager {
    override var minimalFeePerByte: Decimal { 1 }
}`

2024-08-06 11:59 UTC, skibinalexander commented
> Пробегись плиз по перегрузкам, получается вот такие менеджеры теперь можно снести нафиг
> 
> `class LitecoinWalletManager: BitcoinWalletManager { override var minimalFeePerByte: Decimal { 1 } }`

Йес принято

2024-08-06 20:31 UTC, skibinalexander commented on BlockchainSdk/Blockchains/BitcoinCash/BitcoinCashWalletManager.swift
> +class BitcoinCashWalletManager: BitcoinWalletManager {}
> Сань, не дожал) Удалить их нафиг и в ассембли поправить, а то и ассембли удалить, если она ничем кроме менеджера не отличается

Блин сори, побоялся, тащить эти изменения. Завтра все доделаю ...

2024-08-07 06:43 UTC, skibinalexander commented on BlockchainSdk/Blockchains/BitcoinCash/BitcoinCashWalletManager.swift
> +class BitcoinCashWalletManager: BitcoinWalletManager {}
Менеджеры потер, assembly не стал, а то там свои Network сервисы, их тогда тоже придется смотреть

2024-08-07 08:05 UTC, tureck1y approved these changes

2024-08-07 18:17 UTC, dbaturin approved these changes

2024-08-08 07:50 UTC, amuraveinik approved these changes

2024-08-08 09:15 UTC, m3g0byt3 approved these changes

2024-08-08 09:29 UTC, merged