IOS-7227 Update content for activation error on send screen
tangem/blockchain-sdk-swift pull request #789
Opened 2024-08-01 13:35 UTC by amuraveinik

[IOS-7227](https://tangem.atlassian.net/browse/IOS-7227)

2024-08-01 13:37 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +            }
Вот эта вся конструкция означает что если мы передаем флаг `checkForEmpty` (в нашем случае при запросе фи), то выполнится дополнительная проверка на пустое тело ответа (что свидетельствует о том что адрес неактивен в данный момент), и в таком случае кидаем ошибку валидации `ValidationError.accountNotActivated`

2024-08-01 15:57 UTC, tureck1y requested changes

2024-08-01 15:57 UTC, tureck1y commented on BlockchainSdk/Common/API/MultiNetworkProvider.swift
> +                if case ValidationError.accountNotActivated = error {
Предлагаю положить в WalletError, потому что ValidationError это ошибки валидаторов

2024-08-01 15:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +    private func requestPublisher<T: Codable>(for target: TronTarget.TronTargetType, checkForEmpty: Bool = false) -> AnyPublisher<T, Error> {
Что-то я совсем не понимаю что здесь происходит. Eсли такая проверка нужна только в getAccountResource, то почему бы ее там и не сделать, зачем менять общий паблишер?

2024-08-01 15:57 UTC, tureck1y commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +    private func requestPublisher<T: Codable>(for target: TronTarget.TronTargetType, checkForEmpty: Bool = false) -> AnyPublisher<T, Error> {
Сам код проверки крайне желательно либо упростить, либо снабдить комментами

2024-08-02 09:20 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +    private func requestPublisher<T: Codable>(for target: TronTarget.TronTargetType, checkForEmpty: Bool = false) -> AnyPublisher<T, Error> {
Попробую как-то упростить

2024-08-02 09:25 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +    private func requestPublisher<T: Codable>(for target: TronTarget.TronTargetType, checkForEmpty: Bool = false) -> AnyPublisher<T, Error> {
Возможно я не прав в первом утверждении

2024-08-02 10:28 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Tron/TronJsonRpcProvider.swift
> +    private func requestPublisher<T: Codable>(for target: TronTarget.TronTargetType, checkForEmpty: Bool = false) -> AnyPublisher<T, Error> {
В итоге для сделал проверку по WalletError.failedToParseNetworkResponse, в который как раз маппится ошибка десериализации .objectMapping

2024-08-02 15:53 UTC, dbaturin submitted a review, later dismissed

2024-08-02 17:29 UTC, tureck1y commented on BlockchainSdk/Blockchains/Tron/TronNetworkService.swift
> +                    if case WalletError.failedToParseNetworkResponse = error {
Вижу коммент

Но в общем случае у нас нет гарантии того что десериализация не прошла именно из-за того что тело пустое (аккаунт не активирован)

2024-08-02 17:31 UTC, tureck1y commented on BlockchainSdk/Blockchains/Tron/TronNetworkService.swift
> +                    if case WalletError.failedToParseNetworkResponse = error {
Как вариант взять Response из  case objectMapping(Swift.Error, Response), прокинуть в WalletError.failedToParseNetworkResponse и проверить на пустоту

2024-08-05 09:21 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Tron/TronNetworkService.swift
> +                    if case WalletError.failedToParseNetworkResponse = error {
Добавил доп проверку

2024-08-05 09:26 UTC, tureck1y approved these changes

2024-08-05 12:25 UTC, fedorov-d approved these changes

2024-08-05 17:28 UTC, Andoran90 approved these changes

2024-08-06 09:56 UTC, dbaturin approved these changes

2024-08-06 12:24 UTC, merged