BSS-198 solana pending transaction panel
tangem/blockchain-sdk-swift pull request #82
Opened 2022-02-02 14:11 UTC by megakoko

2022-02-02 15:54 UTC, tureck1y requested changes
Еще заметил, что публичная getFee не на месте, надо ее поднять к публичным собратьям)

2022-02-02 15:54 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            networkService.confirmedTransactions(among: transactionIDs)
Это нужно сделать внутри SolanaNetworkService. Как правило у нас есть метод getInfo, который возвращает структуру, в которой есть все что нужно (см. Стеллар)

2022-02-02 15:54 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +                var sentTransaction = transaction
new line потерялся

2022-02-03 05:37 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +                var sentTransaction = transaction
Исправил

2022-02-03 05:37 UTC, megakoko commented on BlockchainSdk/WalletManagers/Solana/SolanaWalletManager.swift
> +            networkService.confirmedTransactions(among: transactionIDs)
Исправил

2022-02-03 05:38 UTC, megakoko commented
Еще в рамках этого ПР исправил ошибку с округлением при отправке токенов (до этого исправил только для валюты).

2022-02-03 06:45 UTC, tureck1y approved these changes

2022-02-03 09:20 UTC, lazutkin-andrey approved these changes

2022-02-03 09:21 UTC, merged