IOS-7834 [Staking] Use energy in fee calculation
tangem/blockchain-sdk-swift pull request #831
Opened 2024-09-06 06:08 UTC by fedorov-d

2024-09-06 06:10 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Tron/TronWalletManager.swift
> +                let consumedEnergyFee = max(.zero, Decimal(energyFee) - remainingEnergy)
вычитаем из ожидаемой fee часть которая будет покрыта энергией юзера

2024-09-06 06:29 UTC, tureck1y approved these changes, later dismissed
Удалось проверить?

2024-09-06 07:43 UTC, fedorov-d commented
> Удалось проверить?

отправку транзы - нет, я только продебажил и убедился что данные прилетают корректно и фи отображается с их учетом.

2024-09-06 18:11 UTC, dbaturin requested changes

2024-09-06 18:11 UTC, dbaturin commented on BlockchainSdk/Blockchains/Tron/TronWalletManager.swift
> +                let consumedEnergyFee = max(.zero, Decimal(energyFee) - remainingEnergy)
Ты чистую энергию вычитаешь из уже помноженной на её стоимость в TRX. На строчке 152 перемножается.

2024-09-06 20:23 UTC, skibinalexander commented
Я не очень в контексте, посмотрел бегло

2024-09-09 06:20 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Tron/TronWalletManager.swift
> +                let consumedEnergyFee = max(.zero, Decimal(energyFee) - remainingEnergy)
поправил, теперь умножаем на sunPerEnergyUnit уже после вычитания

2024-09-09 07:06 UTC, tureck1y approved these changes

2024-09-09 12:49 UTC, dbaturin approved these changes

2024-09-09 13:10 UTC, ba1ashov approved these changes

2024-09-09 13:45 UTC, skibinalexander approved these changes

2024-09-09 15:27 UTC, merged