BSS-185 adding polkadot
tangem/blockchain-sdk-swift pull request #84
Opened 2022-02-07 13:20 UTC by megakoko

2022-02-07 13:23 UTC, megakoko commented on BlockchainSdk/Common/Blockchain.swift
> +        case .polkadot: return 354
Деривация "m/44'/354'/0'/0'/0'", стандартная ведь подойдет?

2022-02-08 08:26 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .polkadot: return 354
Насколько я понял, такой путь используют Леджер и Трастволлет. А вообще у польки собственный стандарт, в котором помимо пути отличается еще и способ генерации сид-ключа. Они генерируют его напрямую из сид фразы, без pbkdf2. Исходя из этого у нас в любом случае не получится сгенерировать адрес, идентичный официальному кошельку. Упоминаний о stellar-like подходе я нигде не встретил. Поэтому да, оставляем стандартную. @lazutkin-andrey fyi

2022-02-08 11:04 UTC, tureck1y requested changes

2022-02-08 11:04 UTC, tureck1y commented on BlockchainSdkTests/AddressTests.swift
> +    func testSubstrateNetwork(_ network: PolkadotNetwork, publicKey: Data, expectedAddress: String) {
 Этот метод будет светиться как отдельный тест, может его достаточно приватным сделать? Или еще нужно  test убрать из названия?

2022-02-08 11:04 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetworkService.swift
> +//
Здесь тоже захватов нигде нет. Если решим выпиливать, то проверим на всех доступных иосах и разных кейсах и выпилим везде, а пока лучше чтоб было все одинаково)

2022-02-08 11:05 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotTransactionBuilder.swift
> +            // TODO: RPC error is returned: "Transaction has a bad signature".
Нет, мы это не используем. Оставил на всякий случай.

2022-02-08 11:06 UTC, megakoko commented on BlockchainSdkTests/AddressTests.swift
> +    func testSubstrateNetwork(_ network: PolkadotNetwork, publicKey: Data, expectedAddress: String) {
Не подсвечивается в тестах, скорее всего из-за того что у него есть аргументы.

2022-02-08 11:07 UTC, tureck1y commented on BlockchainSdkTests/AddressTests.swift
> +    func testSubstrateNetwork(_ network: PolkadotNetwork, publicKey: Data, expectedAddress: String) {
окай

2022-02-09 05:42 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetworkService.swift
> +//
Добавил

2022-02-09 05:42 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotResponse.swift
> +        // self.feeFrozen = try decoder.decode(BigUInt.self, .b256)
Почистил

2022-02-09 05:42 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotWalletManager.swift
> +//
Добавил

2022-02-09 05:42 UTC, megakoko commented
Также добавил currentHost

2022-02-09 08:07 UTC, tureck1y requested changes

2022-02-09 08:07 UTC, tureck1y commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetworkService.swift
> +            .tryMap { _ in
Тут осталось, может стоит прямо в just запихнуть?

2022-02-09 08:25 UTC, megakoko commented on BlockchainSdk/WalletManagers/Polkadot/PolkadotNetworkService.swift
> +            .tryMap { _ in
Исправил

2022-02-09 08:25 UTC, tureck1y approved these changes

2022-02-09 10:04 UTC, lazutkin-andrey approved these changes

2022-02-09 10:06 UTC, lazutkin-andrey approved these changes

2022-02-09 10:10 UTC, merged