IOS-7807 SUI
tangem/blockchain-sdk-swift pull request #844
Opened 2024-09-16 16:19 UTC by siblockchaina

2024-09-17 14:18 UTC, tureck1y requested changes

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/784'/0'/0/0"
Кажется проблема тут. edslip запрещает non-hardened деривацию. Нужно сравнить адреса с трастом

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Sui.swift
> +public struct Sui {
Обычно называем что-то типа SUIUtils. Аббревиатуры пишем капсом.

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiAddress.swift
> +            throw WalletCoreAddressService.TWError.makeAddressFailed
Давай кинем ошибку из нашего бсдк, надо поискать есть ли подоходящие

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiAddress.swift
> +        let string = "0x" + hashed.hexString
можно юзать addHexPrefix тут и ниже, может еще где-то есть

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    private var publicKey: Wallet.PublicKey
думаю тут должно быть let, ключ же не меняется, по остальным тоже пробегись плиз. По дефолту все ставим let

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +
лишняя строка

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    public func update(coins: [SuiCoinObject]) {
лучше сделать билдер stateless и запрашивать все нужное для транзакции прямо перед отправкой, в методе send, если конечно эта инфа не приходит из апдейта баланса и не является статичной

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +        self.transactionBuilder = SuiTransactionBuilder(publicKey: wallet.publicKey, decimals: wallet.blockchain.decimalValue)
должен создаваться в ассембли

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                    self?.wallet.clearPendingTransaction()
нужно какое-то условие, как определять, что транзакция прошла, причем на успешном апдейте, а не на ошибке, лучше посмотреть как референс какой-нибудь другой воллет менеджер, SEI из последних например. 

обработку после receiveValue нужно вынести в отдельный метод updateWallet по аналогии с другими менеджерами

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                manager.networkService.getReferenceGasPrice()
можно же с этого начать, пропустив все выше

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                return try manager.transactionBuilder.buildForInspect(amount: amount, destination: destination, referenceGasPrice: referenceGasPrice)
тут и далее по файлу, можно написать как 

 Result { try manager.transactionBuilder.buildForInspect ... }
            .publisher

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdkTests/Sui/SUITest.swift
> +    func testBuildTransaction() throws {
нужны тесты на генерацию, валидацию адреса и размер транзакции

2024-09-17 14:18 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +    public typealias BuildRequestPublisher = (_ address: String, _ coin: String, _ cursor: String?) -> AnyPublisher<SuiGetCoins, Error>
расскажи плиз подробнее, зачем понадобилось делать отдельную штуку такую? Какая-то сложная логика запроса баланса, что нельзя просто функцией в networkservice обойтись?

2024-09-17 14:22 UTC, siblockchaina commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "0xd185afd5171875605562a1bf7d2216c4bec2fcaea0be7e23cfb80ac5819e4617"
подставил тестовый адрес свой, эту группу ключей и адрес использовал для формирования тестовых данных

2024-09-18 09:06 UTC, siblockchaina commented on BlockchainSdk/Common/Blockchain.swift
> +            return .ed25519_slip0010
исправлено

2024-09-18 09:06 UTC, siblockchaina commented on BlockchainSdkTests/Extensions/TWPublicKeyType+.swift
> +        case .sui:
исправлено

2024-09-18 09:06 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiTarget.swift
> +public struct SuiTarget: TargetType {
исправлено

2024-09-18 09:07 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiFeeParameters.swift
> +    }
удалено

2024-09-18 09:07 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                    self?.wallet.clearPendingTransaction()
добавлено

2024-09-18 09:07 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                manager.networkService.getReferenceGasPrice()
исправлено

2024-09-18 09:07 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +                return try manager.transactionBuilder.buildForInspect(amount: amount, destination: destination, referenceGasPrice: referenceGasPrice)
исправлено

2024-09-18 09:08 UTC, siblockchaina commented on BlockchainSdkTests/Sui/SUITest.swift
> +    func testBuildTransaction() throws {
добавлено

2024-09-18 09:25 UTC, siblockchaina commented on BlockchainSdk/Common/Derivations/DerivationConfigV3.swift
> +            return "m/44'/784'/0'/0/0"
исправлено

2024-09-18 09:42 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    private var publicKey: Wallet.PublicKey
+

2024-09-18 09:42 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiAddress.swift
> +        let string = "0x" + hashed.hexString
исправлено

2024-09-18 09:43 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +
исправлено

2024-09-18 09:44 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    public func update(coins: [SuiCoinObject]) {
верно второе утверждение

2024-09-18 09:44 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +        self.transactionBuilder = SuiTransactionBuilder(publicKey: wallet.publicKey, decimals: wallet.blockchain.decimalValue)
исправлено

2024-09-18 10:07 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Sui.swift
> +public struct Sui {
переименовано

2024-09-18 17:47 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +public class SuiBalanceFetcher {
тут тоже думаю нужно паблик подчистить

2024-09-18 17:47 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Network/SuiNetworkProvider.swift
> +    public func getBalance(address: String, coin: String, cursor: String?) -> AnyPublisher<SuiGetCoins, Error> {
Функции в провайдере тоже паблик не нужны, я уж в остальных файлах не буду однотипные комменты писать, пробегись сам плиз

2024-09-18 17:47 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletAssembly.swift
> +        let transactionBuilder = SuiTransactionBuilder(publicKey: input.wallet.publicKey,
все ли тут правильно? decimals это число знаков после запятой, а decimalValue - 10 в степени decimals

2024-09-20 13:48 UTC, tureck1y commented
тут ветку тоже надо будет поправить

2024-10-10 11:04 UTC, closed without merging