IOS-7807 SUI
tangem/blockchain-sdk-swift pull request #849
Opened 2024-09-20 09:38 UTC by siblockchaina

Prev PR https://github.com/tangem/blockchain-sdk-swift/pull/844

2024-09-20 13:48 UTC, tureck1y reviewed
В целом все ок

2024-09-20 13:48 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Network/SuiResponse.swift
> +//MARK: Balance
nit: 

// MARK: - Balance

и отступ снизу, тогда будут в селекторе сверху норм отображаться

2024-09-20 13:48 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/Network/SuiResponse.swift
> +        struct SuiTransactions: Codable {
лишнее?

2024-09-20 13:48 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SUIUtils.swift
> +    static var SuiGasBudgetScaleUpConstant = Decimal(1000000)
static let везде, если константа

2024-09-20 13:48 UTC, tureck1y commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +            wallet.clearPendingTransaction()
в sui быстро транзы ходят? Есть кейс, когдя в захожу в приложение и у меня есть входящая пендинг транзакция. Можно ли ее наличие как-то определить? В таком случае обычно дамми добавляем, если не можем детали транзакции узнать. Если ходят быстро, то ладно наверное

2024-09-20 13:48 UTC, tureck1y commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return "0xd185afd5171875605562a1bf7d2216c4bec2fcaea0be7e23cfb80ac5819e4617"
спрашивал уже, не помню ответ, адрес Леша сгенерировал?

2024-09-20 13:55 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +            wallet.clearPendingTransaction()
ходят достаточно быстро

2024-09-20 14:10 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiResponse.swift
> +//MARK: Balance
обновлено

2024-09-20 14:11 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiResponse.swift
> +        struct SuiTransactions: Codable {
удалено

2024-09-23 17:01 UTC, dbaturin requested changes

2024-09-24 12:36 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiNetworkProvider.swift
> +    func devInspectTransaction(sender: String, transaction raw: String, referenceGasPrice: String?) -> AnyPublisher<SuiInspectTransaction, Error> {
убрал

2024-09-24 12:36 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +        let signer = try WalletCoreAddressService(coin: .sui).makeAddress(for: publicKey, with: .default)
перенес в инит билдера

2024-09-24 12:37 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    func buildForInspect(amount: Amount, destination: String, referenceGasPrice: Decimal) throws -> String {
обновил реализацию

2024-09-24 12:37 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +            wallet.clearPendingTransaction()
сделал как обычно

2024-09-24 14:21 UTC, tureck1y submitted a review, later dismissed

2024-09-24 14:25 UTC, dbaturin approved these changes, later dismissed

2024-09-25 19:04 UTC, Balashov152 commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            return ""
сюда бы задачку что бы не забыть )

2024-09-26 08:20 UTC, Andoran90 requested changes

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiCoinObject.swift
> +                             balance: balance)
лучше так, чтобы не было огромных пустот
```suggestion
        return SuiCoinObject(
            coinType: response.coinType,
            coinObjectId: response.coinObjectId,
            version: version,
            digest: response.digest,
            balance: balance
        )
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiError.swift
> +}
гораздо лучше отражает о чем речь.
```suggestion
struct SuiError {
    enum CodingError: Error {
        case failedEncoding
        case failedDecoding
    }
}
```

Но в целом можно и не вкладывать в структуру, а сразу, если нет каких-то ещё планов с добавлением ошибок

```suggestion
enum SuiError: Error {
    case failedEncoding
    case failedDecoding
}
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    private let signer: any Address
поддерживаю, непонятно получается, что за сайнер, почему он является адресом. Было бы хорошо ещё пояснить что это за адрес - исходный или целевой

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +                                                                     publicKeys: publicKey.blockchainKey.asDataVector())
то же самое, так проще читается
```suggestion
        let compiled = try TransactionCompiler.compileWithSignatures(
            coinType: .sui,
            txInputData: input.serializedData(),
            signatures: signatureMock.asDataVector(),
            publicKeys: publicKey.blockchainKey.asDataVector()
        )
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +        let useCoins = coins
похоже забыл удалить, нигде не используется в функции

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +        if preSigningOutput.error != .ok {
nit: без отрицания проще читается
```suggestion
        guard preSigningOutput.error == .ok else {
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +        let compiled = try TransactionCompiler.compileWithSignaturesAndPubKeyType(coinType: .sui,
тоже форматирование с новой строки

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +        let useCoins = getCoins(for: decimalAmount + fee.gasBudget)
nit:  кажется такое название понятнее будет, не настаиваю.
```suggestion
        let сoinsToUse = getCoins(for: decimalAmount + fee.gasBudget)
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    private func input(amount: Decimal, destination: String, fee: SuiFeeParameters) throws -> WalletCore.SuiSigningInput {
nit:
```suggestion
    private func makeInput(amount: Decimal, destination: String, fee: SuiFeeParameters) throws -> WalletCore.SuiSigningInput {
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +        Result {
```suggestion
        return Result {
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Blockchains/Sui/SuiWalletManager.swift
> +        networkService.getReferenceGasPrice()
ну как и до этого и в других функциях то же самое
```suggestion
        return networkService.getReferenceGasPrice()
```

2024-09-26 08:20 UTC, Andoran90 commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                ]
```suggestion
            return [
                .init(url: URL(string: "https://fullnode.testnet.sui.io")!)
            ]
```

2024-09-26 08:49 UTC, Balashov152 commented
Вообще по код стайлу хорошо бы форматер нам как то заюзать, или хотя бы прогонять его раз в месяц
или на CI сделать его, но он тогда комитить будет, не факт что удобно будет

2024-09-26 09:21 UTC, tureck1y commented
мы же будем переносить бсдк в репу приложения, форматер тогда сможем юзать

2024-09-26 16:20 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/SuiTransactionBuilder.swift
> +    private let signer: any Address
тогда walletAddress подойдет

2024-09-26 16:21 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +    func requestPublisher(with:  @escaping BuildRequestPublisher) -> Self {
обновил

2024-09-26 16:21 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +    func fetchBalanceRequestPublisher(address: String, coin: String, cursor: String?) -> AnyPublisher<[SuiGetCoins.Coin], Error> {
обновил

2024-09-26 16:21 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +    private func load(address: String, coin: String, cursor: String?, requestPublisher: AnyPublisher<SuiGetCoins, Error>) {
ok

2024-09-27 11:15 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiBalanceFetcher.swift
> +                        self.subject.send(completion: .failure(WalletError.empty))
исправил

2024-09-27 11:15 UTC, siblockchaina commented on BlockchainSdk/Blockchains/Sui/Network/SuiNetworkService.swift
> +    let balanceFetcher = SuiBalanceFetcher()
исправил

2024-09-27 12:03 UTC, Balashov152 submitted a review, later dismissed

2024-09-30 08:52 UTC, Andoran90 approved these changes, later dismissed

2024-10-01 17:08 UTC, tureck1y approved these changes

2024-10-02 07:04 UTC, Andoran90 approved these changes

2024-10-02 09:24 UTC, Balashov152 approved these changes

2024-10-02 17:00 UTC, dbaturin approved these changes

2024-10-02 17:01 UTC, merged