IOS-7619 [Staking] MATIC token in Ethereum
tangem/blockchain-sdk-swift pull request #853
Opened 2024-09-26 09:50 UTC by Balashov152

Проверил

- Апрув USDT in Polygon network
- Swap USDT to Polygon
- Send USDT in network
- Send Polygon

2024-09-26 09:51 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +                case .transfer(let user, let coinValue, let data):
По факту `transfer` и `generic` одно и тоже делает, просто называется по разному, но пока решил оставить два типа

2024-09-26 10:07 UTC, tureck1y requested changes
Что-то не то, зачем вообще эти изменения? Лучше особо не стало и потребует огромного регресса

2024-09-26 10:07 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        guard let compiledTransactionData = stakingTransaction.unsignedData.data(using: .utf8) else {
был хекс, а стал UTF8, зачем?

2024-09-26 10:07 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        let priorityFee = BigUInt(Data(hex: compiledTransaction.maxPriorityFeePerGas))
а в чем смысл изменений? Просто зачем переделывать рабочий код и перетещивать его

2024-09-26 10:07 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +            destination: .generic(contract: compiledTransaction.to, coinValue: .zero, data: data),
был amount, стал zero, зачем передавать хардкод, когда есть готовая собранная транзакция?

2024-09-26 10:07 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +                destination: .transfer(user: destination, coinValue: valueData, data: data),
чет не то, при трансфере коина не может же быть даты, а вот при трансфере токена, коин быть может, как в свопе

2024-09-26 12:17 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        guard let compiledTransactionData = stakingTransaction.unsignedData.data(using: .utf8) else {
Так не работало, там приходит `string json` а не `hex`

2024-09-26 12:17 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        let priorityFee = BigUInt(Data(hex: compiledTransaction.maxPriorityFeePerGas))
и тут тоже `BigUInt == 0` был при старом коде

2024-09-26 12:18 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +            destination: .generic(contract: compiledTransaction.to, coinValue: .zero, data: data),
amount был токена, и так же опять не работало, так как тут не верно использовать amount. при стейкинге 1 MATIC, мы собираем транзакцию где хотим отправить 1 ETH

2024-09-26 12:21 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +                destination: .transfer(user: destination, coinValue: valueData, data: data),
> трансфере коина не может же быть даты

Может, у нас так DEX / Bridge работает, там coinValue + data. 

По крайней мере сейчас так работет, что это идет `transfer` который вместе с `data`, так как мы собираем транзакцию в `TransactionCreator+:19` и юзаем там `feeTokenItem`, и потом здесь он по `amount` маппится в  `transfer`. Это да, не очень логично,  но живет )

2024-09-26 12:23 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        case generic(contract: String, coinValue: BigUInt, data: Data)
По факту, можно вообще нафиг убрать `erc20Transfer ` это то где WalletCore создает за нас дата, и использовать свою data. 

и тогда можно убрать enum, и все под одну гребенку завести )

2024-09-26 12:28 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        guard let compiledTransactionData = stakingTransaction.unsignedData.data(using: .utf8) else {
```
"unsignedTransaction" : "{\"from\":\"0x29010F8F91B980858EB298A0843264cfF21Fd9c9\",\"gasLimit\":\"0x04ca78\",\"to\":\"0xF30Cf4ed712D3734161fDAab5B1DBb49Fd2D0E5c\",\"data\":\"0x6ab150710000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000000000\",\"nonce\":13,\"type\":2,\"maxFeePerGas\":\"0x07e2cf2f80\",\"maxPriorityFeePerGas\":\"0x042c1d80\",\"chainId\":1}"
```

2024-09-27 07:05 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        guard let compiledTransactionData = stakingTransaction.unsignedData.data(using: .utf8) else {
а он тут всегда в json будет? я для bsс там логику вкорячил если что

2024-09-29 07:56 UTC, Metalicia approved these changes

2024-10-03 11:59 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumStakeKitTransactionHelper.swift
> +        guard let compiledTransactionData = stakingTransaction.unsignedData.data(using: .utf8) else {
> а он тут всегда в json будет? я для bsс там логику вкорячил если что

Ну StakeKit так шлет, надеюсь не поменяет )

2024-10-03 17:40 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +    func buildSigningInput(destination: String, coinAmount: BigUInt, fee: Fee, nonce: Int?, data: Data?) throws -> EthereumSigningInput {
так а нонс не нужен тут опциональный

2024-10-03 17:40 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let parameters = transaction.params as? EthereumTransactionParams ?? .empty
лучше оставить как было throw EthereumTransactionBuilderError.feeParametersNotFound

2024-10-03 17:40 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let nonce = parameters.nonce
а нонс тут развернуть тогда тоже

2024-10-04 07:32 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/EthereumTransactionBuilder.swift
> +        let parameters = transaction.params as? EthereumTransactionParams ?? .empty
Тут не сосем `feeParametersNotFound` по этому добавил еще один тип ошибки

2024-10-04 07:34 UTC, Balashov152 commented on BlockchainSdk/Blockchains/Ethereum/Models/EthereumTransactionParams.swift
> -    static var empty: EthereumTransactionParams {
Не используется, да и не нужны такие пустые параметры

2024-10-04 07:59 UTC, tureck1y approved these changes

2024-10-04 08:39 UTC, fedorov-d approved these changes

2024-10-04 08:41 UTC, Andoran90 approved these changes

2024-10-04 09:05 UTC, merged