IOS-7967 Enenrgy WEB EVM/X
tangem/blockchain-sdk-swift pull request #854
Opened 2024-09-30 08:31 UTC by amuraveinik

[IOS-7967](https://tangem.atlassian.net/browse/IOS-7967)

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return Data(hexString: "0x0500")
?

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return false
?

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Polkadot/SubstrateRuntimeVersionProvider.swift
>              return .v14
?

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> -            return 9
Переместил aptos и bittensor в уже существующие кейсы, где было 8 и 9 соответственно

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain/Blockchain+AllCases.swift
> +            .energyWebX(curve: .ed25519_slip0010, testnet: false) // TODO: [Energy Web X] Questionable
В чем разница ed25519 и ed25519_slip0010?
Почему здесь, например, для joystream и bittensor указывается ed25519_slip0010

2024-09-30 08:36 UTC, amuraveinik commented on BlockchainSdkTests/Extensions/TWPublicKeyType+.swift
> +            case .ed25519, .ed25519_slip0010:
Тут тоже не уверен что правильно кейс написан

2024-09-30 08:48 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return Data(hexString: "0x0500")
для joystream и bittensor просто брал польковскую, экспериментальным путем проверялось, если транзакции ходят - все ок

2024-09-30 08:49 UTC, fedorov-d commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return false
тут тоже экспериментальным путем подбиралось значение

2024-09-30 10:04 UTC, amuraveinik commented
В общем, тут есть спорные моменты по Energy Web X, в которых я не уверен. 
Во всех таких местах оставил TODO.
Смогу поправить когда проверю что все работает или не работает, но уже после того как дадут денег на тесты (Леша на дейлике сказал что его добавили в чатик разрабов)

2024-09-30 10:05 UTC, amuraveinik commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                .init(url: URL(string: "")!) // TODO: [Energy Web X] Add testnet address
Про это запросил инфу в слаке
https://tangem.slack.com/archives/GMXC6PP71/p1727690207961099

2024-09-30 10:05 UTC, amuraveinik commented on BlockchainSdk/Common/Factories/EstimationFeeAddressFactory.swift
> +            // TODO: [Energy Web X] Need to generate
Запросил инфу в слаке
https://tangem.slack.com/archives/GMXC6PP71/p1727690207961099

2024-10-01 11:26 UTC, m3g0byt3 reviewed
В целом все ответы по константам можно получить, распарсив метадату
Метадату можно получить дернув ручка metadata в тулзе https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpublic-rpc.mainnet.energywebx.com%2F#/runtime

А вот с парсингом сложнее - я нашел только на расте, но сам его не тестил https://docs.rs/substrate_parser/latest/substrate_parser/

2024-10-01 11:26 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +            return isTestnet ? "VT" : "EWT"
А разве ассет в тестнете парачейна будет VT?
У польки например это все тот же DOT

VT наверное это ассет только в EVM тестнете?

2024-10-01 11:26 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebX: return "energyWebX"
Предложил бы прям над каждым кейсом написать коммент что это - парачейн польки или же EVM
Очень сбивают кейсы, из нейминга сетей это понять невозможно

2024-10-01 11:26 UTC, m3g0byt3 commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +            return "m/44'/246'/0'/0'/0'"
А откуда это значение?

2024-10-01 11:26 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebChain: return false
А это проверялось? Насчет EIP1559

2024-10-01 11:26 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain/Blockchain+AllCases.swift
> +            .energyWebX(curve: .ed25519_slip0010, testnet: false) // TODO: [Energy Web X] Questionable
Тут @tureck1y может хорошо объяснить) Насколько помню это для совместимости с трастом в v2+ картах

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/EnergyWebX/EnergyWebXExternalLinkProvider.swift
> +    var testnetFaucetURL: URL? {
в целом у нас в приле это сейчас не поддерживается, запланируем выпил

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/PolkadotNetwork.swift
> +            return .zeroCoin(for: .energyWebX(curve: curve, testnet: false))
да, это критичный момент, потому что вывод без учета депозита уничтожает аккаунт, надо разобраться, задал вопрос аналитикам

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return Data(hexString: "0x0500")
нужно попробовать отправить транзакцию обязательно

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/PolkadotTransactionBuilder.swift
>              return false
допиши плиз в код комменты про экспериментальный подбор тут и в других аналогичных местах

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/SubstrateRuntimeVersionProvider.swift
>              return .v14
тут мы обновляли через баг, потому что непонятно, опять же отправить транзакцию нужно, с неправильным спеком не пройдет

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                .init(url: URL(string: "")!) // TODO: [Energy Web X] Add testnet address
Вообще, тестнет штука желательная, но не обязательная, если есть пробелмы, то не нужно добавлять

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain/Blockchain+AllCases.swift
> +            .energyWebX(curve: .ed25519_slip0010, testnet: false) // TODO: [Energy Web X] Questionable
Да, это другой тип кривой для совместимости адресов. По факту, если говорить про воллет2, то если блокчейн на ed, то юзаем ed25519_slip0010. Версия ed25519 сделана исключительно под cardano. На более старых картах только один вариант - ed25519. Конкретно тут - значения не имеет по большому счету

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdkExample/config
подтяни плиз сразу на самый актуальный

2024-10-02 16:26 UTC, tureck1y commented on BlockchainSdkTests/Extensions/TWPublicKeyType+.swift
> +            case .ed25519, .ed25519_slip0010:
его надо переместить под список блокчейнов на ed25519. 
Тут возможны варианты
- секп
- секп extended (разжатый ключ)
- ed25519
- особняком, блокчейны, которые могут работать на разных кривых (secp и еd).

Если говорить про воллет 2, то ed25519_slip0010, это просто ed25519 в воллет кор, а ed25519 у нас это ed25519Cardano в воллет кор.

2024-10-04 08:33 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Polkadot/PolkadotNetwork.swift
> +            return .zeroCoin(for: .energyWebX(curve: curve, testnet: false))
Обсудили [тут](https://tangem.slack.com/archives/C06RVEB5G21/p1727973256893989?thread_ts=1727885355.569809&cid=C06RVEB5G21), делаем копейке

2024-10-04 08:40 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebX: return "energyWebX"
Можно сделать и названия `energyWebEVM/energyWebX` и комменты над кейсами оставить, чтобы точно ничего не перепуталось

>Мы добавили kavaEVM как kava. А вот для другой кавы придется придумывать теперь.

Как вариант `kavaNative`, вроде норм)

2024-10-04 09:06 UTC, amuraveinik commented on BlockchainSdk/Common/API/TestnetAPINodeInfoProvider.swift
> +                .init(url: URL(string: "")!) // TODO: [Energy Web X] Add testnet address
В итоге выпилил тестнет для Energy Web X, т.к. по запросу все заглохло

2024-10-04 09:06 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +            return isTestnet ? "VT" : "EWT"
В итоге выпилил тестнет для Energy Web X, т.к. по запросу все заглохло

2024-10-04 09:14 UTC, amuraveinik commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +            return "m/44'/246'/0'/0'/0'"
В slip-0044 есть Energy Web, по идее это к EVM относится.
Уточню еще про energy web x

2024-10-04 10:07 UTC, amuraveinik commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +            return "m/44'/246'/0'/0'/0'"
Но вообще для X это указано в [ресерче на ноушене](https://www.notion.so/tangem/Energy-Web-71639a30c64444f4bf113e71bf802884?pvs=4#38939c71bfeb4ebe8e7e082466f5800b)

`Путь деривации - "m/44'/246'/0'/0’/0’”
Данные взяты из [документации](https://energy-web-foundation.gitbook.io/energy-web/foundational-concepts/wallets-and-exchanges/hierarchical-deterministic-hd-wallets#derivation-path-components), совпадают со SLIP-0044
В документации последние ноды не hardened, что не актуально для ed25519`

2024-10-04 10:25 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebChain: return false
🟠 12:21:29:443: Response: https://rpc.energyweb.org/
🟠 12:21:29:444: body: 
```json
{
  "jsonrpc" : "2.0",
  "result" : {
    "reward" : [
      [
        "0x0",
        "0x0",
        "0x0"
      ],
      [
        "0x0",
        "0x0",
        "0x0"
      ],
      [
        "0x0",
        "0x0",
        "0x0"
      ],
      [
        "0x0",
        "0x0",
        "0x0"
      ],
      [
        "0x0",
        "0x0",
        "0x0"
      ]
    ],
    "baseFeePerGas" : [
      "0x7",
      "0x7",
      "0x7",
      "0x7",
      "0x7",
      "0x7"
    ],
    "gasUsedRatio" : [
      0,
      0,
      0,
      0,
      0
    ],
    "oldestBlock" : "0x1ead70d"
  },
  "id" : 21
}
```

Что маппится в объект
```
EthereumFeeHistory(
    baseFee: 0, 
    lowBaseFee: 0, 
    marketBaseFee: 0, 
    fastBaseFee: 0, 
    lowPriorityFee: 8, 
    marketPriorityFee: 9, 
    fastPriorityFee: 12
)
```

2024-10-04 10:27 UTC, amuraveinik commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebChain: return false
Со включенным EIP1559 транзакции не отправляются

2024-10-04 10:30 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumTarget.swift
> +            return AnyEncodable([AnyEncodable("0x5"), AnyEncodable("latest"), AnyEncodable([25,50,75])])
Пришлось тут добавить так, потому что у меня запрос фи хистори для EWC падал

🟠 12:17:45:563: Response: https://energy-web-chain.rpc.thirdweb.com/
🟠 12:17:45:563: body: 
```json
{
  "jsonrpc": "2.0",
  "error": {
    "message": "Invalid params: invalid type: integer 5, expected a 0x-prefixed hex string with length between (0; 64].",
    "code": -32602
  },
  "id": 25
}
```

2024-10-04 10:42 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumTarget.swift
> +            return AnyEncodable([AnyEncodable("0x5"), AnyEncodable("latest"), AnyEncodable([25,50,75])])
Откатил. По видимому разные сети по разному обрабатывают. 

@tureck1y Вроде нам же этот запрос не нужен здесь, т.к. можно пренебречь что он будет падать для EWC?

2024-10-04 11:08 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +        case .energyWebChain: return false
ну все, значит не поддерживается

2024-10-04 11:10 UTC, tureck1y commented on BlockchainSdk/Blockchains/Ethereum/Network/EthereumTarget.swift
> +            return AnyEncodable([AnyEncodable("0x5"), AnyEncodable("latest"), AnyEncodable([25,50,75])])
да, допиши плиз этот коммент напротив тоггла eip1559 у этой сети. Что в целом присылает нули и вот этот момент с энкодингом

2024-10-09 08:51 UTC, amuraveinik commented
Жду денег на проверку транзакций

2024-10-09 10:34 UTC, tureck1y commented on BlockchainSdk/Blockchains/Polkadot/SubstrateRuntimeVersionProvider.swift
>              return .v14
ставим тут v15?

2024-10-09 10:34 UTC, tureck1y reviewed
В целом только остался адрес для естимейта

2024-10-09 13:30 UTC, amuraveinik commented on BlockchainSdk/Blockchains/Polkadot/SubstrateRuntimeVersionProvider.swift
>              return .v14
Оставил 14, транзакция ушла

2024-10-09 14:45 UTC, tureck1y approved these changes

2024-10-09 17:43 UTC, m3g0byt3 approved these changes
А вывод скрипта как выглядит? Он норм парсит и польку и парачейны?

2024-10-09 17:43 UTC, m3g0byt3 commented on BlockchainSdk/Common/Blockchain.swift
> +            case .coin: return "energy-web-token"
Тут одинаковые coin ids - это будет вообще работать?
В плане показа цены, синхры на бэке и т.д.

2024-10-09 17:56 UTC, dbaturin requested changes

2024-10-09 17:56 UTC, dbaturin commented on BlockchainSdk/Common/Derivations/DerivationConfigV1.swift
> +            return "m/44'/246'/0'/0'/0'"
Для EVM надо стандартную EVM деривацию

2024-10-09 18:01 UTC, tureck1y commented
> Для EVM надо стандартную EVM деривацию

так это же в1, там мы поддерживаем разные, если они есть в слипе

2024-10-09 18:01 UTC, tureck1y commented on BlockchainSdk/Common/Blockchain.swift
> +            case .coin: return "energy-web-token"
Я вот тоже засомневался, но у бинанся сейчас так, завел задачу провести ревизию использования айдишников

2024-10-09 18:26 UTC, dbaturin approved these changes

2024-10-09 18:53 UTC, fedorov-d approved these changes

2024-10-09 21:14 UTC, merged